//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 11:14:39 AM CST 
//


package com.ibm.commerce.order.entities;

import com.ibm.commerce.copyright.IBMCopyright;



/**
 * <p>Java class for InventoryStatusEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="InventoryStatusEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="Available"/>
 *     &lt;enumeration value="Unavailable"/>
 *     &lt;enumeration value="Future"/>
 *     &lt;enumeration value="Allocated"/>
 *     &lt;enumeration value="Unallocated"/>
 *     &lt;enumeration value="Backorderable"/>
 *     &lt;enumeration value="Backordered"/>
 *     &lt;enumeration value="Released"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
public enum InventoryStatusEnumeration {

    AVAILABLE("Available"),
    UNAVAILABLE("Unavailable"),
    FUTURE("Future"),
    ALLOCATED("Allocated"),
    UNALLOCATED("Unallocated"),
    BACKORDERABLE("Backorderable"),
    BACKORDERED("Backordered"),
    RELEASED("Released");
    private final String value;

    /**
	 * IBM copyright notice field.
	 */
	@SuppressWarnings("unused")
	private static final String COPYRIGHT = IBMCopyright.SHORT_COPYRIGHT;
	
    InventoryStatusEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static InventoryStatusEnumeration fromValue(String v) {
        for (InventoryStatusEnumeration c: InventoryStatusEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
