//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 11:14:39 AM CST 
//


package com.ibm.commerce.order.entities;

/*
 *-----------------------------------------------------------------
 * IBM Confidential
 *
 * OCO Source Materials
 *
 * WebSphere Commerce
 *
 * (C) Copyright IBM Corp. 2016
 *
 * The source code for this program is not published or otherwise
 * divested of its trade secrets, irrespective of what has
 * been deposited with the U.S. Copyright Office.
 *-----------------------------------------------------------------
 */

import java.util.ArrayList;
import java.util.List;

import javax.xml.datatype.XMLGregorianCalendar;

import com.ibm.commerce.copyright.IBMCopyright;
import com.ibm.commerce.foundation.common.entities.ContactInfo;
import com.ibm.commerce.foundation.common.entities.ContactInfoIdentifier;
import com.ibm.commerce.foundation.common.entities.OrderCharges;
import com.ibm.commerce.foundation.common.entities.OrderIdentifier;
import com.ibm.commerce.foundation.common.entities.OrganizationIdentifier;
import com.ibm.commerce.foundation.common.entities.PersonIdentifier;
import com.ibm.commerce.foundation.common.entities.QuoteIdentifier;
import com.ibm.commerce.foundation.common.entities.ShippingMode;
import com.ibm.commerce.foundation.common.entities.StoreIdentifier;
import com.ibm.commerce.foundation.common.entities.SubscriptionInfo;
import com.ibm.commerce.foundation.common.entities.UserData;


/**
 * <p>Java class for Order complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Order">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrderIdentifier" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}OrderIdentifier" minOccurs="0"/>
 *         &lt;element name="StoreIdentifier" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}StoreIdentifier" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/order}Channel" minOccurs="0"/>
 *         &lt;element name="QuoteID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="QuoteIdentifier" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}QuoteIdentifier" minOccurs="0"/>
 *         &lt;element name="BuyerPONumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OrganizationIdentifier" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}OrganizationIdentifier" minOccurs="0"/>
 *         &lt;element name="BuyerIdentifier" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}PersonIdentifier" minOccurs="0"/>
 *         &lt;element name="BuyerBillInfo" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}ContactInfo" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/order}CouponCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/order}PromotionCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/order}RewardOption" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AdjustmentRequirement" type="{http://www.ibm.com/xmlns/prod/commerce/9/order}AdjustmentRequirement" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/order}OrderAmount" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/order}UsableShippingAddress" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/order}OrderPaymentInfo" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/order}UsablePaymentInformation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/order}UsableShippingMode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/order}OrderStatus" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/order}OrderEditor" minOccurs="0"/>
 *         &lt;element name="BLockInfo" type="{http://www.ibm.com/xmlns/prod/commerce/9/order}OrderBLockInfo" minOccurs="0"/>
 *         &lt;element name="OrderDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/order}CSRComments" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="LastUpdateDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="PlacedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/order}OrderItem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/order}OrderNotificationInfo" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/order}OrderShippingInfo" minOccurs="0"/>
 *         &lt;element name="OrderScheduleInfo" type="{http://www.ibm.com/xmlns/prod/commerce/9/order}OrderScheduleInfo" minOccurs="0"/>
 *         &lt;element name="OrderGiftInfo" type="{http://www.ibm.com/xmlns/prod/commerce/9/order}GiftItemInfo" minOccurs="0"/>
 *         &lt;element name="OrderCode" type="{http://www.ibm.com/xmlns/prod/commerce/9/order}OrderCode" minOccurs="0"/>
 *         &lt;element name="ParentInfo" type="{http://www.ibm.com/xmlns/prod/commerce/9/order}ParentInfo" minOccurs="0"/>
 *         &lt;element name="SubscriptionInfo" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}SubscriptionInfo" minOccurs="0"/>
 *         &lt;element name="CalculationInfo" type="{http://www.ibm.com/xmlns/prod/commerce/9/order}CalculationInfo" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}UserData" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="orderVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="shipAsComplete" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class Order {

	/**
	 * IBM copyright notice field.
	 */
	@SuppressWarnings("unused")
	private static final String COPYRIGHT = IBMCopyright.SHORT_COPYRIGHT;
	
    protected OrderIdentifier orderIdentifier;
    protected StoreIdentifier storeIdentifier;
    protected Channel channel;
    protected String quoteID;
    protected QuoteIdentifier quoteIdentifier;
    protected String buyerPONumber;
    protected OrganizationIdentifier organizationIdentifier;
    protected PersonIdentifier buyerIdentifier;
    protected ContactInfo buyerBillInfo;
    protected List<CouponCode> couponCode;
    protected List<PromotionCode> promotionCode;
    protected List<RewardOption> rewardOption;
    protected List<AdjustmentRequirement> adjustmentRequirement;
    protected OrderCharges orderAmount;
    protected List<ContactInfoIdentifier> usableShippingAddress;
    protected OrderPaymentInfo orderPaymentInfo;
    protected List<PaymentInformation> usablePaymentInformation;
    protected List<ShippingMode> usableShippingMode;
    protected OrderStatus orderStatus;
    protected PersonIdentifier orderEditor;
    protected OrderBLockInfo bLockInfo;
    protected String orderDescription;
    protected String comments;
    protected List<CSRComments> csrComments;
    protected XMLGregorianCalendar lastUpdateDate;
    protected XMLGregorianCalendar placedDate;
    protected List<OrderItem> orderItem;
    protected OrderNotificationInfo orderNotificationInfo;
    protected OrderShippingInfo orderShippingInfo;
    protected OrderScheduleInfo orderScheduleInfo;
    protected GiftItemInfo orderGiftInfo;
    protected String orderTypeCode;
    protected ParentInfo parentInfo;
    protected SubscriptionInfo subscriptionInfo;
    protected CalculationInfo calculationInfo;
    protected UserData userData;
    protected List<ExtendAttribute> orderExtendAttribute;
    protected String orderVersion;
    protected Boolean shipAsComplete;

    /**
     * Gets the value of the orderIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link OrderIdentifier }
     *     
     */
    public OrderIdentifier getOrderIdentifier() {
        return orderIdentifier;
    }

    /**
     * Sets the value of the orderIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderIdentifier }
     *     
     */
    public void setOrderIdentifier(OrderIdentifier value) {
        this.orderIdentifier = value;
    }

    /**
     * Gets the value of the storeIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link StoreIdentifier }
     *     
     */
    public StoreIdentifier getStoreIdentifier() {
        return storeIdentifier;
    }

    /**
     * Sets the value of the storeIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link StoreIdentifier }
     *     
     */
    public void setStoreIdentifier(StoreIdentifier value) {
        this.storeIdentifier = value;
    }

    /**
     * The channel.
     * 
     * @return
     *     possible object is
     *     {@link Channel }
     *     
     */
    public Channel getChannel() {
        return channel;
    }

    /**
     * Sets the value of the channel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Channel }
     *     
     */
    public void setChannel(Channel value) {
        this.channel = value;
    }

    /**
     * Gets the value of the quoteID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuoteID() {
        return quoteID;
    }

    /**
     * Sets the value of the quoteID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuoteID(String value) {
        this.quoteID = value;
    }

    /**
     * Gets the value of the quoteIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link QuoteIdentifier }
     *     
     */
    public QuoteIdentifier getQuoteIdentifier() {
        return quoteIdentifier;
    }

    /**
     * Sets the value of the quoteIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuoteIdentifier }
     *     
     */
    public void setQuoteIdentifier(QuoteIdentifier value) {
        this.quoteIdentifier = value;
    }

    /**
     * Gets the value of the buyerPONumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuyerPONumber() {
        return buyerPONumber;
    }

    /**
     * Sets the value of the buyerPONumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuyerPONumber(String value) {
        this.buyerPONumber = value;
    }

    /**
     * Gets the value of the organizationIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationIdentifier }
     *     
     */
    public OrganizationIdentifier getOrganizationIdentifier() {
        return organizationIdentifier;
    }

    /**
     * Sets the value of the organizationIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationIdentifier }
     *     
     */
    public void setOrganizationIdentifier(OrganizationIdentifier value) {
        this.organizationIdentifier = value;
    }

    /**
     * Gets the value of the buyerIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link PersonIdentifier }
     *     
     */
    public PersonIdentifier getBuyerIdentifier() {
        return buyerIdentifier;
    }

    /**
     * Sets the value of the buyerIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonIdentifier }
     *     
     */
    public void setBuyerIdentifier(PersonIdentifier value) {
        this.buyerIdentifier = value;
    }

    /**
     * Gets the value of the buyerBillInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ContactInfo }
     *     
     */
    public ContactInfo getBuyerBillInfo() {
        return buyerBillInfo;
    }

    /**
     * Sets the value of the buyerBillInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactInfo }
     *     
     */
    public void setBuyerBillInfo(ContactInfo value) {
        this.buyerBillInfo = value;
    }

    /**
     * The coupon codes.Gets the value of the couponCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the couponCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCouponCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CouponCode }
     * 
     * 
     */
    public List<CouponCode> getCouponCode() {
        if (couponCode == null) {
            couponCode = new ArrayList<CouponCode>();
        }
        return this.couponCode;
    }

    /**
     * The promotion codes entered.Gets the value of the promotionCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the promotionCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPromotionCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PromotionCode }
     * 
     * 
     */
    public List<PromotionCode> getPromotionCode() {
        if (promotionCode == null) {
            promotionCode = new ArrayList<PromotionCode>();
        }
        return this.promotionCode;
    }

    /**
     * The promotion reward options.Gets the value of the rewardOption property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rewardOption property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRewardOption().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RewardOption }
     * 
     * 
     */
    public List<RewardOption> getRewardOption() {
        if (rewardOption == null) {
            rewardOption = new ArrayList<RewardOption>();
        }
        return this.rewardOption;
    }

    /**
     * Gets the value of the adjustmentRequirement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the adjustmentRequirement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdjustmentRequirement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdjustmentRequirement }
     * 
     * 
     */
    public List<AdjustmentRequirement> getAdjustmentRequirement() {
        if (adjustmentRequirement == null) {
            adjustmentRequirement = new ArrayList<AdjustmentRequirement>();
        }
        return this.adjustmentRequirement;
    }

    /**
     * Total amount of the order.
     * 
     * @return
     *     possible object is
     *     {@link OrderCharges }
     *     
     */
    public OrderCharges getOrderAmount() {
        return orderAmount;
    }

    /**
     * Sets the value of the orderAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderCharges }
     *     
     */
    public void setOrderAmount(OrderCharges value) {
        this.orderAmount = value;
    }

    /**
     * Usable Shipping addresses for the order item.Gets the value of the usableShippingAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the usableShippingAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUsableShippingAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactInfoIdentifier }
     * 
     * 
     */
    public List<ContactInfoIdentifier> getUsableShippingAddress() {
        if (usableShippingAddress == null) {
            usableShippingAddress = new ArrayList<ContactInfoIdentifier>();
        }
        return this.usableShippingAddress;
    }

    /**
     * Payment information of the order.
     * 
     * @return
     *     possible object is
     *     {@link OrderPaymentInfo }
     *     
     */
    public OrderPaymentInfo getOrderPaymentInfo() {
        return orderPaymentInfo;
    }

    /**
     * Sets the value of the orderPaymentInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderPaymentInfo }
     *     
     */
    public void setOrderPaymentInfo(OrderPaymentInfo value) {
        this.orderPaymentInfo = value;
    }

    /**
     * The usable payment methods information for this order.Gets the value of the usablePaymentInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the usablePaymentInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUsablePaymentInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentInformation }
     * 
     * 
     */
    public List<PaymentInformation> getUsablePaymentInformation() {
        if (usablePaymentInformation == null) {
            usablePaymentInformation = new ArrayList<PaymentInformation>();
        }
        return this.usablePaymentInformation;
    }

    /**
     * Usable Shipping modes for the order.Gets the value of the usableShippingMode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the usableShippingMode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUsableShippingMode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ShippingMode }
     * 
     * 
     */
    public List<ShippingMode> getUsableShippingMode() {
        if (usableShippingMode == null) {
            usableShippingMode = new ArrayList<ShippingMode>();
        }
        return this.usableShippingMode;
    }

    /**
     * Status of the order.
     * 
     * @return
     *     possible object is
     *     {@link OrderStatus }
     *     
     */
    public OrderStatus getOrderStatus() {
        return orderStatus;
    }

    /**
     * Sets the value of the orderStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderStatus }
     *     
     */
    public void setOrderStatus(OrderStatus value) {
        this.orderStatus = value;
    }

    /**
     * Identifier of the CSR who is editing the order.
     * 
     * @return
     *     possible object is
     *     {@link PersonIdentifier }
     *     
     */
    public PersonIdentifier getOrderEditor() {
        return orderEditor;
    }

    /**
     * Sets the value of the orderEditor property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonIdentifier }
     *     
     */
    public void setOrderEditor(PersonIdentifier value) {
        this.orderEditor = value;
    }

    /**
     * Gets the value of the bLockInfo property.
     * 
     * @return
     *     possible object is
     *     {@link OrderBLockInfo }
     *     
     */
    public OrderBLockInfo getBLockInfo() {
        return bLockInfo;
    }

    /**
     * Sets the value of the bLockInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderBLockInfo }
     *     
     */
    public void setBLockInfo(OrderBLockInfo value) {
        this.bLockInfo = value;
    }

    /**
     * Gets the value of the orderDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderDescription() {
        return orderDescription;
    }

    /**
     * Sets the value of the orderDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderDescription(String value) {
        this.orderDescription = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Comments made by customer service representatives.Gets the value of the csrComments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the csrComments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCSRComments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CSRComments }
     * 
     * 
     */
    public List<CSRComments> getCSRComments() {
        if (csrComments == null) {
            csrComments = new ArrayList<CSRComments>();
        }
        return this.csrComments;
    }

    /**
     * Gets the value of the lastUpdateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * Sets the value of the lastUpdateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastUpdateDate(XMLGregorianCalendar value) {
        this.lastUpdateDate = value;
    }

    /**
     * Gets the value of the placedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPlacedDate() {
        return placedDate;
    }

    /**
     * Sets the value of the placedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPlacedDate(XMLGregorianCalendar value) {
        this.placedDate = value;
    }

    /**
     * The order items.Gets the value of the orderItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderItem }
     * 
     * 
     */
    public List<OrderItem> getOrderItem() {
        if (orderItem == null) {
            orderItem = new ArrayList<OrderItem>();
        }
        return this.orderItem;
    }

    /**
     * Order notification info.
     * 
     * @return
     *     possible object is
     *     {@link OrderNotificationInfo }
     *     
     */
    public OrderNotificationInfo getOrderNotificationInfo() {
        return orderNotificationInfo;
    }

    /**
     * Sets the value of the orderNotificationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderNotificationInfo }
     *     
     */
    public void setOrderNotificationInfo(OrderNotificationInfo value) {
        this.orderNotificationInfo = value;
    }

    /**
     * Order shipping info.
     * 
     * @return
     *     possible object is
     *     {@link OrderShippingInfo }
     *     
     */
    public OrderShippingInfo getOrderShippingInfo() {
        return orderShippingInfo;
    }

    /**
     * Sets the value of the orderShippingInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderShippingInfo }
     *     
     */
    public void setOrderShippingInfo(OrderShippingInfo value) {
        this.orderShippingInfo = value;
    }

    /**
     * Gets the value of the orderScheduleInfo property.
     * 
     * @return
     *     possible object is
     *     {@link OrderScheduleInfo }
     *     
     */
    public OrderScheduleInfo getOrderScheduleInfo() {
        return orderScheduleInfo;
    }

    /**
     * Sets the value of the orderScheduleInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderScheduleInfo }
     *     
     */
    public void setOrderScheduleInfo(OrderScheduleInfo value) {
        this.orderScheduleInfo = value;
    }

    /**
     * Gets the value of the orderGiftInfo property.
     * 
     * @return
     *     possible object is
     *     {@link GiftItemInfo }
     *     
     */
    public GiftItemInfo getOrderGiftInfo() {
        return orderGiftInfo;
    }

    /**
     * Sets the value of the orderGiftInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link GiftItemInfo }
     *     
     */
    public void setOrderGiftInfo(GiftItemInfo value) {
        this.orderGiftInfo = value;
    }

    /**
     * Gets the value of the orderTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderCode() {
        return orderTypeCode;
    }

    /**
     * Sets the value of the orderTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderCode(String value) {
        this.orderTypeCode = value;
    }

    /**
     * Gets the value of the parentInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ParentInfo }
     *     
     */
    public ParentInfo getParentInfo() {
        return parentInfo;
    }

    /**
     * Sets the value of the parentInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParentInfo }
     *     
     */
    public void setParentInfo(ParentInfo value) {
        this.parentInfo = value;
    }

    /**
     * Gets the value of the subscriptionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SubscriptionInfo }
     *     
     */
    public SubscriptionInfo getSubscriptionInfo() {
        return subscriptionInfo;
    }

    /**
     * Sets the value of the subscriptionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscriptionInfo }
     *     
     */
    public void setSubscriptionInfo(SubscriptionInfo value) {
        this.subscriptionInfo = value;
    }

    /**
     * Gets the value of the calculationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CalculationInfo }
     *     
     */
    public CalculationInfo getCalculationInfo() {
        return calculationInfo;
    }

    /**
     * Sets the value of the calculationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalculationInfo }
     *     
     */
    public void setCalculationInfo(CalculationInfo value) {
        this.calculationInfo = value;
    }

    /**
     * The user data area.
     * 
     * @return
     *     possible object is
     *     {@link UserData }
     *     
     */
    public UserData getUserData() {
        return userData;
    }

    /**
     * Sets the value of the userData property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserData }
     *     
     */
    public void setUserData(UserData value) {
        this.userData = value;
    }
    
    /**
     * Gets the value of the orderExtendAttribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderExtendAttribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderExtendAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtendAttribute }
     * 
     * 
     */
    public List<ExtendAttribute> getOrderExtendAttribute() {
        if (orderExtendAttribute == null) {
            orderExtendAttribute = new ArrayList<ExtendAttribute>();
        }
        return this.orderExtendAttribute;
    }

    /**
     * Gets the value of the orderVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderVersion() {
        return orderVersion;
    }

    /**
     * Sets the value of the orderVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderVersion(String value) {
        this.orderVersion = value;
    }

    /**
     * Gets the value of the shipAsComplete property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShipAsComplete() {
        return shipAsComplete;
    }

    /**
     * Sets the value of the shipAsComplete property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShipAsComplete(Boolean value) {
        this.shipAsComplete = value;
    }

}
