//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 11:14:39 AM CST 
//


package com.ibm.commerce.order.entities;

import java.util.ArrayList;
import java.util.List;

import com.ibm.commerce.copyright.IBMCopyright;
import com.ibm.commerce.foundation.common.entities.EmailAddress;
import com.ibm.commerce.foundation.common.entities.MobilePhone;
import com.ibm.commerce.foundation.common.entities.UserData;


/**
 * Type definition of the order notification.
 * 
 * <p>Java class for OrderNotificationInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderNotificationInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EMail" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}EmailAddress" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SMS" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}MobilePhone" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AllEMailsRecipient" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}EmailAddress" minOccurs="0"/>
 *         &lt;element name="OrderReceivedEMailRecipient" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}EmailAddress" minOccurs="0"/>
 *         &lt;element name="OrderCancelEMailRecipient" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}EmailAddress" minOccurs="0"/>
 *         &lt;element name="OrderCancelForMerchantEMailRecipient" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}EmailAddress" minOccurs="0"/>
 *         &lt;element name="OrderChangedEMailRecipient" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}EmailAddress" minOccurs="0"/>
 *         &lt;element name="ReleaseShipNotifyEMailRecipient" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}EmailAddress" minOccurs="0"/>
 *         &lt;element name="MerchantNotify" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShopperNotify" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OrderSubmittedNotify" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}UserData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class OrderNotificationInfo {

	/**
	 * IBM copyright notice field.
	 */
	@SuppressWarnings("unused")
	private static final String COPYRIGHT = IBMCopyright.SHORT_COPYRIGHT;
	
    protected List<EmailAddress> eMail;
    protected List<MobilePhone> sms;
    protected EmailAddress allEMailsRecipient;
    protected EmailAddress orderReceivedEMailRecipient;
    protected EmailAddress orderCancelEMailRecipient;
    protected EmailAddress orderCancelForMerchantEMailRecipient;
    protected EmailAddress orderChangedEMailRecipient;
    protected EmailAddress releaseShipNotifyEMailRecipient;
    protected String merchantNotify;
    protected String shopperNotify;
    protected String orderSubmittedNotify;
    protected UserData userData;

    /**
     * Gets the value of the eMail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eMail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEMail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EmailAddress }
     * 
     * 
     */
    public List<EmailAddress> getEMail() {
        if (eMail == null) {
            eMail = new ArrayList<EmailAddress>();
        }
        return this.eMail;
    }

    /**
     * Gets the value of the sms property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sms property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSMS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MobilePhone }
     * 
     * 
     */
    public List<MobilePhone> getSMS() {
        if (sms == null) {
            sms = new ArrayList<MobilePhone>();
        }
        return this.sms;
    }

    /**
     * Gets the value of the allEMailsRecipient property.
     * 
     * @return
     *     possible object is
     *     {@link EmailAddress }
     *     
     */
    public EmailAddress getAllEMailsRecipient() {
        return allEMailsRecipient;
    }

    /**
     * Sets the value of the allEMailsRecipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmailAddress }
     *     
     */
    public void setAllEMailsRecipient(EmailAddress value) {
        this.allEMailsRecipient = value;
    }

    /**
     * Gets the value of the orderReceivedEMailRecipient property.
     * 
     * @return
     *     possible object is
     *     {@link EmailAddress }
     *     
     */
    public EmailAddress getOrderReceivedEMailRecipient() {
        return orderReceivedEMailRecipient;
    }

    /**
     * Sets the value of the orderReceivedEMailRecipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmailAddress }
     *     
     */
    public void setOrderReceivedEMailRecipient(EmailAddress value) {
        this.orderReceivedEMailRecipient = value;
    }

    /**
     * Gets the value of the orderCancelEMailRecipient property.
     * 
     * @return
     *     possible object is
     *     {@link EmailAddress }
     *     
     */
    public EmailAddress getOrderCancelEMailRecipient() {
        return orderCancelEMailRecipient;
    }

    /**
     * Sets the value of the orderCancelEMailRecipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmailAddress }
     *     
     */
    public void setOrderCancelEMailRecipient(EmailAddress value) {
        this.orderCancelEMailRecipient = value;
    }

    /**
     * Gets the value of the orderCancelForMerchantEMailRecipient property.
     * 
     * @return
     *     possible object is
     *     {@link EmailAddress }
     *     
     */
    public EmailAddress getOrderCancelForMerchantEMailRecipient() {
        return orderCancelForMerchantEMailRecipient;
    }

    /**
     * Sets the value of the orderCancelForMerchantEMailRecipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmailAddress }
     *     
     */
    public void setOrderCancelForMerchantEMailRecipient(EmailAddress value) {
        this.orderCancelForMerchantEMailRecipient = value;
    }

    /**
     * Gets the value of the orderChangedEMailRecipient property.
     * 
     * @return
     *     possible object is
     *     {@link EmailAddress }
     *     
     */
    public EmailAddress getOrderChangedEMailRecipient() {
        return orderChangedEMailRecipient;
    }

    /**
     * Sets the value of the orderChangedEMailRecipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmailAddress }
     *     
     */
    public void setOrderChangedEMailRecipient(EmailAddress value) {
        this.orderChangedEMailRecipient = value;
    }

    /**
     * Gets the value of the releaseShipNotifyEMailRecipient property.
     * 
     * @return
     *     possible object is
     *     {@link EmailAddress }
     *     
     */
    public EmailAddress getReleaseShipNotifyEMailRecipient() {
        return releaseShipNotifyEMailRecipient;
    }

    /**
     * Sets the value of the releaseShipNotifyEMailRecipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmailAddress }
     *     
     */
    public void setReleaseShipNotifyEMailRecipient(EmailAddress value) {
        this.releaseShipNotifyEMailRecipient = value;
    }

    /**
     * Gets the value of the merchantNotify property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantNotify() {
        return merchantNotify;
    }

    /**
     * Sets the value of the merchantNotify property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantNotify(String value) {
        this.merchantNotify = value;
    }

    /**
     * Gets the value of the shopperNotify property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShopperNotify() {
        return shopperNotify;
    }

    /**
     * Sets the value of the shopperNotify property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShopperNotify(String value) {
        this.shopperNotify = value;
    }

    /**
     * Gets the value of the orderSubmittedNotify property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderSubmittedNotify() {
        return orderSubmittedNotify;
    }

    /**
     * Sets the value of the orderSubmittedNotify property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderSubmittedNotify(String value) {
        this.orderSubmittedNotify = value;
    }

    /**
     * The user data area.
     * 
     * @return
     *     possible object is
     *     {@link UserData }
     *     
     */
    public UserData getUserData() {
        return userData;
    }

    /**
     * Sets the value of the userData property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserData }
     *     
     */
    public void setUserData(UserData value) {
        this.userData = value;
    }

}
