//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 11:14:39 AM CST 
//


package com.ibm.commerce.order.entities;

import com.ibm.commerce.copyright.IBMCopyright;



/**
 * <p>Java class for OrderEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OrderEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="STD"/>
 *     &lt;enumeration value="QUT"/>
 *     &lt;enumeration value="PRL"/>
 *     &lt;enumeration value="SRL"/>
 *     &lt;enumeration value="TMP"/>
 *     &lt;enumeration value="QUK"/>
 *     &lt;enumeration value="ORD"/>
 *     &lt;enumeration value="QOT"/>
 *     &lt;enumeration value="REC"/>
 *     &lt;enumeration value="SUB"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
public enum OrderEnumeration {

    STD,
    QUT,
    PRL,
    SRL,
    TMP,
    QUK,
    ORD,
    QOT,
    REC,
    SUB;

    /**
	 * IBM copyright notice field.
	 */
	@SuppressWarnings("unused")
	private static final String COPYRIGHT = IBMCopyright.SHORT_COPYRIGHT;
	
    public String value() {
        return name();
    }

    public static OrderEnumeration fromValue(String v) {
        return valueOf(v);
    }

}
