//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 11:14:39 AM CST 
//


package com.ibm.commerce.order.entities;

/*
 *-----------------------------------------------------------------
 * IBM Confidential
 *
 * OCO Source Materials
 *
 * WebSphere Commerce
 *
 * (C) Copyright IBM Corp. 2016
 *
 * The source code for this program is not published or otherwise
 * divested of its trade secrets, irrespective of what has
 * been deposited with the U.S. Copyright Office.
 *-----------------------------------------------------------------
 */

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.xml.datatype.XMLGregorianCalendar;

import com.ibm.commerce.copyright.IBMCopyright;
import com.ibm.commerce.foundation.common.entities.CatalogEntryIdentifier;
import com.ibm.commerce.foundation.common.entities.ContactInfoIdentifier;
import com.ibm.commerce.foundation.common.entities.ContractIdentifier;
import com.ibm.commerce.foundation.common.entities.OrderItemCharges;
import com.ibm.commerce.foundation.common.entities.OrderItemIdentifier;
import com.ibm.commerce.foundation.common.entities.PolicyIdentifier;
import com.ibm.commerce.foundation.common.entities.Quantity;
import com.ibm.commerce.foundation.common.entities.ShippingMode;
import com.ibm.commerce.foundation.common.entities.UserData;


/**
 * Type definition of an order item.
 * 
 * <p>Java class for OrderItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrderItemIdentifier" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}OrderItemIdentifier" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/order}CatalogEntryIdentifier" minOccurs="0"/>
 *         &lt;element name="ItemAttributes" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}Map"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/order}OrderItemComponent" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Quantity" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}Quantity" minOccurs="0"/>
 *         &lt;element name="ConfigurationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OrderItemConfiguration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ContractIdentifier" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}ContractIdentifier" minOccurs="0"/>
 *         &lt;element name="OfferID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AdjustmentRequirement" type="{http://www.ibm.com/xmlns/prod/commerce/9/order}AdjustmentRequirement" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/order}OrderItemAmount" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/order}UsableShippingAddress" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/order}UsableShippingMode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/order}OrderItemShippingInfo" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/order}OrderItemStatus" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/order}OrderItemFulfillmentInfo" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/order}FulfillmentCenter" minOccurs="0"/>
 *         &lt;element name="CorrelationGroup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OrderItemDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CreateDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="LastUpdateDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="UsableShippingChargePolicy" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}PolicyIdentifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="GiftItemInfo" type="{http://www.ibm.com/xmlns/prod/commerce/9/order}GiftItemInfo" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}UserData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class OrderItem {

	/**
	 * IBM copyright notice field.
	 */
	@SuppressWarnings("unused")
	private static final String COPYRIGHT = IBMCopyright.SHORT_COPYRIGHT;
	
    protected OrderItemIdentifier orderItemIdentifier;
    protected CatalogEntryIdentifier catalogEntryIdentifier;
    protected Map<String, String> itemAttributes;
    protected List<OrderItemComponent> orderItemComponent;
    protected Quantity quantity;
    protected java.lang.String configurationID;
    protected java.lang.String orderItemConfiguration;
    protected ContractIdentifier contractIdentifier;
    protected java.lang.String offerID;
    protected List<AdjustmentRequirement> adjustmentRequirement;
    protected OrderItemCharges orderItemAmount;
    protected List<ContactInfoIdentifier> usableShippingAddress;
    protected List<ShippingMode> usableShippingMode;
    protected OrderItemShippingInfo orderItemShippingInfo;
    protected OrderItemStatus orderItemStatus;
    protected OrderItemFulfillmentInfo orderItemFulfillmentInfo;
    protected FulfillmentCenter fulfillmentCenter;
    protected java.lang.String correlationGroup;
    protected java.lang.String orderItemDescription;
    protected java.lang.String comments;
    protected XMLGregorianCalendar createDate;
    protected XMLGregorianCalendar lastUpdateDate;
    protected List<PolicyIdentifier> usableShippingChargePolicy;
    protected GiftItemInfo giftItemInfo;
    protected UserData userData;
    protected List<ExtendAttribute> orderItemExtendAttribute;

    /**
     * Gets the value of the orderItemIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link OrderItemIdentifier }
     *     
     */
    public OrderItemIdentifier getOrderItemIdentifier() {
        return orderItemIdentifier;
    }

    /**
     * Sets the value of the orderItemIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderItemIdentifier }
     *     
     */
    public void setOrderItemIdentifier(OrderItemIdentifier value) {
        this.orderItemIdentifier = value;
    }

    /**
     * The catalog entry identifier.
     * 
     * @return
     *     possible object is
     *     {@link CatalogEntryIdentifier }
     *     
     */
    public CatalogEntryIdentifier getCatalogEntryIdentifier() {
        return catalogEntryIdentifier;
    }

    /**
     * Sets the value of the catalogEntryIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogEntryIdentifier }
     *     
     */
    public void setCatalogEntryIdentifier(CatalogEntryIdentifier value) {
        this.catalogEntryIdentifier = value;
    }

    /**
     * Gets the value of the itemAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link Map }
     *     
     */
    public Map<String, String> getItemAttributes() {
        return itemAttributes;
    }

    /**
     * Sets the value of the itemAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Map }
     *     
     */
    public void setItemAttributes(Map<String, String> value) {
        this.itemAttributes = value;
    }

    /**
     * Components of the product if it is a kit.Gets the value of the orderItemComponent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderItemComponent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderItemComponent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderItemComponent }
     * 
     * 
     */
    public List<OrderItemComponent> getOrderItemComponent() {
        if (orderItemComponent == null) {
            orderItemComponent = new ArrayList<OrderItemComponent>();
        }
        return this.orderItemComponent;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link Quantity }
     *     
     */
    public Quantity getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quantity }
     *     
     */
    public void setQuantity(Quantity value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the configurationID property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getConfigurationID() {
        return configurationID;
    }

    /**
     * Sets the value of the configurationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setConfigurationID(java.lang.String value) {
        this.configurationID = value;
    }

    /**
     * Gets the value of the orderItemConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getOrderItemConfiguration() {
        return orderItemConfiguration;
    }

    /**
     * Sets the value of the orderItemConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setOrderItemConfiguration(java.lang.String value) {
        this.orderItemConfiguration = value;
    }

    /**
     * Gets the value of the contractIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link ContractIdentifier }
     *     
     */
    public ContractIdentifier getContractIdentifier() {
        return contractIdentifier;
    }

    /**
     * Sets the value of the contractIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractIdentifier }
     *     
     */
    public void setContractIdentifier(ContractIdentifier value) {
        this.contractIdentifier = value;
    }

    /**
     * Gets the value of the offerID property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getOfferID() {
        return offerID;
    }

    /**
     * Sets the value of the offerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setOfferID(java.lang.String value) {
        this.offerID = value;
    }

    /**
     * Gets the value of the adjustmentRequirement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the adjustmentRequirement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdjustmentRequirement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdjustmentRequirement }
     * 
     * 
     */
    public List<AdjustmentRequirement> getAdjustmentRequirement() {
        if (adjustmentRequirement == null) {
            adjustmentRequirement = new ArrayList<AdjustmentRequirement>();
        }
        return this.adjustmentRequirement;
    }

    /**
     * Amounts of the order item.
     * 
     * @return
     *     possible object is
     *     {@link OrderItemCharges }
     *     
     */
    public OrderItemCharges getOrderItemAmount() {
        return orderItemAmount;
    }

    /**
     * Sets the value of the orderItemAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderItemCharges }
     *     
     */
    public void setOrderItemAmount(OrderItemCharges value) {
        this.orderItemAmount = value;
    }

    /**
     * Usable Shipping addresses for the order item.Gets the value of the usableShippingAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the usableShippingAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUsableShippingAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactInfoIdentifier }
     * 
     * 
     */
    public List<ContactInfoIdentifier> getUsableShippingAddress() {
        if (usableShippingAddress == null) {
            usableShippingAddress = new ArrayList<ContactInfoIdentifier>();
        }
        return this.usableShippingAddress;
    }

    /**
     * Usable Shipping modes for the order item.Gets the value of the usableShippingMode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the usableShippingMode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUsableShippingMode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ShippingMode }
     * 
     * 
     */
    public List<ShippingMode> getUsableShippingMode() {
        if (usableShippingMode == null) {
            usableShippingMode = new ArrayList<ShippingMode>();
        }
        return this.usableShippingMode;
    }

    /**
     * Shipping information of the order item.
     * 
     * @return
     *     possible object is
     *     {@link OrderItemShippingInfo }
     *     
     */
    public OrderItemShippingInfo getOrderItemShippingInfo() {
        return orderItemShippingInfo;
    }

    /**
     * Sets the value of the orderItemShippingInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderItemShippingInfo }
     *     
     */
    public void setOrderItemShippingInfo(OrderItemShippingInfo value) {
        this.orderItemShippingInfo = value;
    }

    /**
     * Status of the order item.
     * 
     * @return
     *     possible object is
     *     {@link OrderItemStatus }
     *     
     */
    public OrderItemStatus getOrderItemStatus() {
        return orderItemStatus;
    }

    /**
     * Sets the value of the orderItemStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderItemStatus }
     *     
     */
    public void setOrderItemStatus(OrderItemStatus value) {
        this.orderItemStatus = value;
    }

    /**
     * Fulfillment information of the order item.
     * 
     * @return
     *     possible object is
     *     {@link OrderItemFulfillmentInfo }
     *     
     */
    public OrderItemFulfillmentInfo getOrderItemFulfillmentInfo() {
        return orderItemFulfillmentInfo;
    }

    /**
     * Sets the value of the orderItemFulfillmentInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderItemFulfillmentInfo }
     *     
     */
    public void setOrderItemFulfillmentInfo(OrderItemFulfillmentInfo value) {
        this.orderItemFulfillmentInfo = value;
    }

    /**
     * The fulfillment center.
     * 
     * @return
     *     possible object is
     *     {@link FulfillmentCenter }
     *     
     */
    public FulfillmentCenter getFulfillmentCenter() {
        return fulfillmentCenter;
    }

    /**
     * Sets the value of the fulfillmentCenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link FulfillmentCenter }
     *     
     */
    public void setFulfillmentCenter(FulfillmentCenter value) {
        this.fulfillmentCenter = value;
    }

    /**
     * Gets the value of the correlationGroup property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getCorrelationGroup() {
        return correlationGroup;
    }

    /**
     * Sets the value of the correlationGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setCorrelationGroup(java.lang.String value) {
        this.correlationGroup = value;
    }

    /**
     * Gets the value of the orderItemDescription property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getOrderItemDescription() {
        return orderItemDescription;
    }

    /**
     * Sets the value of the orderItemDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setOrderItemDescription(java.lang.String value) {
        this.orderItemDescription = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setComments(java.lang.String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the createDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreateDate() {
        return createDate;
    }

    /**
     * Sets the value of the createDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreateDate(XMLGregorianCalendar value) {
        this.createDate = value;
    }

    /**
     * Gets the value of the lastUpdateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * Sets the value of the lastUpdateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastUpdateDate(XMLGregorianCalendar value) {
        this.lastUpdateDate = value;
    }

    /**
     * Gets the value of the usableShippingChargePolicy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the usableShippingChargePolicy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUsableShippingChargePolicy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PolicyIdentifier }
     * 
     * 
     */
    public List<PolicyIdentifier> getUsableShippingChargePolicy() {
        if (usableShippingChargePolicy == null) {
            usableShippingChargePolicy = new ArrayList<PolicyIdentifier>();
        }
        return this.usableShippingChargePolicy;
    }

    /**
     * Gets the value of the giftItemInfo property.
     * 
     * @return
     *     possible object is
     *     {@link GiftItemInfo }
     *     
     */
    public GiftItemInfo getGiftItemInfo() {
        return giftItemInfo;
    }

    /**
     * Sets the value of the giftItemInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link GiftItemInfo }
     *     
     */
    public void setGiftItemInfo(GiftItemInfo value) {
        this.giftItemInfo = value;
    }

    /**
     * The user data area.
     * 
     * @return
     *     possible object is
     *     {@link UserData }
     *     
     */
    public UserData getUserData() {
        return userData;
    }

    /**
     * Sets the value of the userData property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserData }
     *     
     */
    public void setUserData(UserData value) {
        this.userData = value;
    }
    
    /**
     * Gets the value of the orderItemExtendAttribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderItemExtendAttribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderItemExtendAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtendAttribute }
     * 
     * 
     */
    public List<ExtendAttribute> getOrderItemExtendAttribute() {
        if (orderItemExtendAttribute == null) {
            orderItemExtendAttribute = new ArrayList<ExtendAttribute>();
        }
        return this.orderItemExtendAttribute;
    }

}
