//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 11:14:39 AM CST 
//


package com.ibm.commerce.order.entities;

import com.ibm.commerce.copyright.IBMCopyright;
import com.ibm.commerce.foundation.common.entities.OrderIdentifier;
import com.ibm.commerce.foundation.common.entities.OrderItemIdentifier;
import com.ibm.commerce.foundation.common.entities.UserData;



/**
 * The parent order or parent order item of this order.
 * 
 * <p>Java class for ParentInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ParentInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ParentOrderIdentifier" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}OrderIdentifier" minOccurs="0"/>
 *         &lt;element name="ParentOrderItemIdentifier" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}OrderItemIdentifier" minOccurs="0"/>
 *         &lt;element name="RelationTypeCode" type="{http://www.ibm.com/xmlns/prod/commerce/9/order}RelationTypeCode" minOccurs="0"/>
 *         &lt;element name="UserData" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}UserData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class ParentInfo {

	/**
	 * IBM copyright notice field.
	 */
	@SuppressWarnings("unused")
	private static final String COPYRIGHT = IBMCopyright.SHORT_COPYRIGHT;
	
    protected OrderIdentifier parentOrderIdentifier;
    protected OrderItemIdentifier parentOrderItemIdentifier;
    protected String relationTypeCode;
    protected UserData userData;

    /**
     * Gets the value of the parentOrderIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link OrderIdentifier }
     *     
     */
    public OrderIdentifier getParentOrderIdentifier() {
        return parentOrderIdentifier;
    }

    /**
     * Sets the value of the parentOrderIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderIdentifier }
     *     
     */
    public void setParentOrderIdentifier(OrderIdentifier value) {
        this.parentOrderIdentifier = value;
    }

    /**
     * Gets the value of the parentOrderItemIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link OrderItemIdentifier }
     *     
     */
    public OrderItemIdentifier getParentOrderItemIdentifier() {
        return parentOrderItemIdentifier;
    }

    /**
     * Sets the value of the parentOrderItemIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderItemIdentifier }
     *     
     */
    public void setParentOrderItemIdentifier(OrderItemIdentifier value) {
        this.parentOrderItemIdentifier = value;
    }

    /**
     * Gets the value of the relationTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelationTypeCode() {
        return relationTypeCode;
    }

    /**
     * Sets the value of the relationTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelationTypeCode(String value) {
        this.relationTypeCode = value;
    }

    /**
     * Gets the value of the userData property.
     * 
     * @return
     *     possible object is
     *     {@link UserData }
     *     
     */
    public UserData getUserData() {
        return userData;
    }

    /**
     * Sets the value of the userData property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserData }
     *     
     */
    public void setUserData(UserData value) {
        this.userData = value;
    }

}
