//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 11:14:39 AM CST 
//


package com.ibm.commerce.order.entities;

import com.ibm.commerce.copyright.IBMCopyright;
import com.ibm.commerce.foundation.common.entities.Adjustment;
import com.ibm.commerce.foundation.common.entities.RewardOptionIdentifier;
import com.ibm.commerce.foundation.common.entities.UserData;



/**
 * Type definition of a promotion reward option type.
 * 			
 * 
 * <p>Java class for RewardOption complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RewardOption">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RewardOptionIdentifier" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}RewardOptionIdentifier"/>
 *         &lt;element name="Adjustment" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}Adjustment" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/order}RewardChoice" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/order}RewardSpecification" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}UserData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class RewardOption {

	/**
	 * IBM copyright notice field.
	 */
	@SuppressWarnings("unused")
	private static final String COPYRIGHT = IBMCopyright.SHORT_COPYRIGHT;
	
    protected RewardOptionIdentifier rewardOptionIdentifier;
    protected Adjustment adjustment;
    protected RewardChoice rewardChoice;
    protected RewardSpecification rewardSpecification;
    protected UserData userData;

    /**
     * Gets the value of the rewardOptionIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link RewardOptionIdentifier }
     *     
     */
    public RewardOptionIdentifier getRewardOptionIdentifier() {
        return rewardOptionIdentifier;
    }

    /**
     * Sets the value of the rewardOptionIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link RewardOptionIdentifier }
     *     
     */
    public void setRewardOptionIdentifier(RewardOptionIdentifier value) {
        this.rewardOptionIdentifier = value;
    }

    /**
     * Gets the value of the adjustment property.
     * 
     * @return
     *     possible object is
     *     {@link Adjustment }
     *     
     */
    public Adjustment getAdjustment() {
        return adjustment;
    }

    /**
     * Sets the value of the adjustment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Adjustment }
     *     
     */
    public void setAdjustment(Adjustment value) {
        this.adjustment = value;
    }

    /**
     * 
     * 						This element represents the shopper selection
     * 						based on the option specification.
     * 					
     * 
     * @return
     *     possible object is
     *     {@link RewardChoice }
     *     
     */
    public RewardChoice getRewardChoice() {
        return rewardChoice;
    }

    /**
     * Sets the value of the rewardChoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link RewardChoice }
     *     
     */
    public void setRewardChoice(RewardChoice value) {
        this.rewardChoice = value;
    }

    /**
     * 
     * 						This element represents the option specification
     * 						for shopper to choice from.
     * 					
     * 
     * @return
     *     possible object is
     *     {@link RewardSpecification }
     *     
     */
    public RewardSpecification getRewardSpecification() {
        return rewardSpecification;
    }

    /**
     * Sets the value of the rewardSpecification property.
     * 
     * @param value
     *     allowed object is
     *     {@link RewardSpecification }
     *     
     */
    public void setRewardSpecification(RewardSpecification value) {
        this.rewardSpecification = value;
    }

    /**
     * User data area.
     * 
     * @return
     *     possible object is
     *     {@link UserData }
     *     
     */
    public UserData getUserData() {
        return userData;
    }

    /**
     * Sets the value of the userData property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserData }
     *     
     */
    public void setUserData(UserData value) {
        this.userData = value;
    }

}
