//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 11:14:39 AM CST 
//


package com.ibm.commerce.order.entities;

import com.ibm.commerce.copyright.IBMCopyright;



/**
 * <p>Java class for TransactionEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TransactionEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="Approve"/>
 *     &lt;enumeration value="Deposit"/>
 *     &lt;enumeration value="ApproveAndDeposit"/>
 *     &lt;enumeration value="Credit"/>
 *     &lt;enumeration value="ReverseApprove"/>
 *     &lt;enumeration value="ReverseDeposit"/>
 *     &lt;enumeration value="ReverseCredit"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
public enum TransactionEnumeration {

    APPROVE("Approve"),
    DEPOSIT("Deposit"),
    APPROVE_AND_DEPOSIT("ApproveAndDeposit"),
    CREDIT("Credit"),
    REVERSE_APPROVE("ReverseApprove"),
    REVERSE_DEPOSIT("ReverseDeposit"),
    REVERSE_CREDIT("ReverseCredit");
    private final String value;

    /**
	 * IBM copyright notice field.
	 */
	@SuppressWarnings("unused")
	private static final String COPYRIGHT = IBMCopyright.SHORT_COPYRIGHT;
	
    TransactionEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TransactionEnumeration fromValue(String v) {
        for (TransactionEnumeration c: TransactionEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
