CKEDITOR.plugins.add("ibmlanguagedropdown",{lang:"ar,ca,cs,da,de,el,en,es,eu,fi,fr,he,hr,hu,it,iw,ja,kk,ko,nb,nl,no,pl,pt,pt-br,ro,ru,sk,sl,sv,th,tr,uk,zh,zh-cn,zh-tw",beforeInit:function(a){if(!a.config.language_list){var d={ar:a.lang.ibmlanguagedropdown.arabic+":rtl",eu:a.lang.ibmlanguagedropdown.basque,bg:a.lang.ibmlanguagedropdown.bulgarian,ca:a.lang.ibmlanguagedropdown.catalan,zh:a.lang.ibmlanguagedropdown.chinese_simplified,"zh-tw":a.lang.ibmlanguagedropdown.chinese_traditional,hr:a.lang.ibmlanguagedropdown.croation,
cs:a.lang.ibmlanguagedropdown.czech,da:a.lang.ibmlanguagedropdown.danish,nl:a.lang.ibmlanguagedropdown.dutch,en:a.lang.ibmlanguagedropdown.english,fi:a.lang.ibmlanguagedropdown.finnish,fr:a.lang.ibmlanguagedropdown.french,de:a.lang.ibmlanguagedropdown.german,el:a.lang.ibmlanguagedropdown.greek,iw:a.lang.ibmlanguagedropdown.hebrew+":rtl",hu:a.lang.ibmlanguagedropdown.hungarian,id:a.lang.ibmlanguagedropdown.indonesian,it:a.lang.ibmlanguagedropdown.italian,ja:a.lang.ibmlanguagedropdown.japanese,kk:a.lang.ibmlanguagedropdown.kazakh,
ko:a.lang.ibmlanguagedropdown.korean,no:a.lang.ibmlanguagedropdown.norwegian_bokmal,pl:a.lang.ibmlanguagedropdown.polish,pt:a.lang.ibmlanguagedropdown.portuguese,"pt-br":a.lang.ibmlanguagedropdown.portuguese_brazilian,ro:a.lang.ibmlanguagedropdown.romanian,ru:a.lang.ibmlanguagedropdown.russian,sk:a.lang.ibmlanguagedropdown.slovak,sl:a.lang.ibmlanguagedropdown.slovenian,es:a.lang.ibmlanguagedropdown.spanish,sv:a.lang.ibmlanguagedropdown.swedish,th:a.lang.ibmlanguagedropdown.thai,tr:a.lang.ibmlanguagedropdown.turkish},
b=[a.lang.ibmlanguagedropdown.arabic+":rtl",a.lang.ibmlanguagedropdown.basque,a.lang.ibmlanguagedropdown.bulgarian,a.lang.ibmlanguagedropdown.catalan,a.lang.ibmlanguagedropdown.chinese_simplified,a.lang.ibmlanguagedropdown.chinese_traditional,a.lang.ibmlanguagedropdown.croation,a.lang.ibmlanguagedropdown.czech,a.lang.ibmlanguagedropdown.danish,a.lang.ibmlanguagedropdown.dutch,a.lang.ibmlanguagedropdown.english,a.lang.ibmlanguagedropdown.finnish,a.lang.ibmlanguagedropdown.french,a.lang.ibmlanguagedropdown.german,
a.lang.ibmlanguagedropdown.greek,a.lang.ibmlanguagedropdown.hebrew+":rtl",a.lang.ibmlanguagedropdown.hungarian,a.lang.ibmlanguagedropdown.indonesian,a.lang.ibmlanguagedropdown.italian,a.lang.ibmlanguagedropdown.japanese,a.lang.ibmlanguagedropdown.kazakh,a.lang.ibmlanguagedropdown.korean,a.lang.ibmlanguagedropdown.norwegian_bokmal,a.lang.ibmlanguagedropdown.polish,a.lang.ibmlanguagedropdown.portuguese,a.lang.ibmlanguagedropdown.portuguese_brazilian,a.lang.ibmlanguagedropdown.romanian,a.lang.ibmlanguagedropdown.russian,
a.lang.ibmlanguagedropdown.slovak,a.lang.ibmlanguagedropdown.slovenian,a.lang.ibmlanguagedropdown.spanish,a.lang.ibmlanguagedropdown.swedish,a.lang.ibmlanguagedropdown.thai,a.lang.ibmlanguagedropdown.turkish];b.sort(function(a,b){var c=0,a=a.toLowerCase(),b=b.toLowerCase();a>b&&(c=1);a<b&&(c=-1);return c});a.config.language_list=[];for(var f=0;f<b.length;f++)for(key in d)if(d[key]===b[f]){a.config.language_list.push(key+":"+b[f]);break}}},init:function(a){var d=a.config.language_list||["ar:Arabic:rtl",
"fr:French","es:Spanish"];for(i=0;i<d.length;i++)parts=d[i].split(":"),curLanguageId=parts[0],languageButtonId="language_"+curLanguageId,a.getMenuItem(languageButtonId).style.getDefinition().attributes.style="font-size:14px;font-family:courier new,courier,monospace;";a.on("menuShow",function(b){for(var b=(b.data[0]||b.data).element.getElementsByTag("iframe").getItem(0),f=b.getFrameDocument(),d=f.getBody().getElementsByTag("div"),e=0;e<d.count();e++){var c=d.getItem(e),g=c.getAttribute("style");if("cke_panel_block"==
c.getAttribute("class")&&(!g||"display: none;"!=g))if(c=c.getElementsByTag("div").getItem(0),"cke_menu"==c.getAttribute("class")||c.getAttribute("class").replace(/ /g,"")=="cke_menu cke_mixed_dir_content".replace(/ /g,"")){c=c.getElementsByTag("a").getItem(0).getAttribute("class");g=b.getParent();b.removeClass("cke_language_menu_iframe");g.removeClass("cke_language_menu_div");for(var j=f.getBody().getElementsByTag("span"),e=0;e<j.count();e++){var h=j.getItem(e);(h&&h.getAttribute("class")&&-1<h.getAttribute("class").indexOf("cke_button_icon cke_button__language_")||
"cke_button_icon cke_button__language_remove_icon"==h.getAttribute("class"))&&h.setAttribute("style","display: none;")}b.getFrameDocument().getBody().getParent().getStyle("overflow")||b.getFrameDocument().getBody().getParent().setAttribute("style","overflow: hidden;");if(0<c.indexOf("language")){a.config.language_list&&9<a.config.language_list.length&&(b.getFrameDocument().getBody().getParent().removeStyle("overflow"),b.setAttribute("class",b.getAttribute("class")+" cke_language_menu_iframe"));g.setAttribute("class",
g.getAttribute("class")+" cke_language_menu_div");break}}}})}});