<!--********************************************************************-->
<!--  Licensed Materials - Property of IBM                              -->
<!--                                                                    -->
<!--  WebSphere Commerce                                                -->
<!--                                                                    -->
<!--  (c) Copyright IBM Corp. 2011                                      -->
<!--                                                                    -->
<!--  US Government Users Restricted Rights - Use, duplication or       -->
<!--  disclosure restricted by GSA ADP Schedule Contract with IBM Corp. -->
<!--                                                                    -->
<!--********************************************************************-->
BEGIN_SYMBOL_DEFINITIONS
  COLS:POINTOFINTEREST_KEY_COL = POINTOFINTEREST:POINTOFINTEREST_ID
  COLS:POINTOFINTEREST_IBM_All_AP_COLS = POINTOFINTEREST:*
  COLS:POINTOFINTEREST_IBM_Details_AP_COLS = POINTOFINTEREST:*
  COLS:POINTOFINTEREST_IBM_Summary_AP_COLS = POINTOFINTEREST:POINTOFINTEREST_ID,OPTCOUNTER
  COLS:POIDESC_KEY_COL = POIDESC:POIDESC_ID
  COLS:POIDESC_IBM_All_AP_COLS = POIDESC:*
  COLS:POIDESC_IBM_Details_AP_COLS = POIDESC:*
  COLS:POIDESC_IBM_Summary_AP_COLS = POIDESC:POIDESC_ID,OPTCOUNTER,POINTOFINTEREST_ID
END_SYMBOL_DEFINITIONS


BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest
  base_table=POINTOFINTEREST
  sql=
    SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_KEY_COL$
    FROM
      POINTOFINTEREST
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest[PointOfInterestIdentifier[(UniqueID=)]]
  base_table=POINTOFINTEREST
  sql=
    SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_KEY_COL$
    FROM
      POINTOFINTEREST
    WHERE
      POINTOFINTEREST.POINTOFINTEREST_ID = ?UniqueID?
END_XPATH_TO_SQL_STATEMENT
<!-- Generic search -->
BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest[search()]
  base_table=POINTOFINTEREST
  sql=
    SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_KEY_COL$
    FROM
      POINTOFINTEREST, $ATTR_TBLS$
    WHERE
      ( $ATTR_CNDS$ )
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
  name=/POIDESC[(POIDESC_ID=)]
  base_table=POIDESC
  sql=
    SELECT DISTINCT
      POIDESC.$COLS:POIDESC_KEY_COL$
    FROM
      POIDESC
    WHERE
      POIDESC.POIDESC_ID = ?POIDESC_ID?
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
  name=/POINTOFINTEREST[(POINTOFINTEREST_ID=)]
  base_table=POINTOFINTEREST
  sql=
    SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_KEY_COL$
    FROM
      POINTOFINTEREST
    WHERE
      POINTOFINTEREST.POINTOFINTEREST_ID = ?POINTOFINTEREST_ID?
END_XPATH_TO_SQL_STATEMENT


<!-- ------------------------------------- -->
<!-- BEGIN INSERTION OF CUSTOM TPL SCRIPTS -->
<!-- ------------------------------------- -->


<!-- FIND_ALL_XPATH -->
BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest[(StoreID=)]+IBM_All
  base_table=POINTOFINTEREST
  sql=
  SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_IBM_All_AP_COLS$, POIDESC.$COLS:POIDESC_IBM_All_AP_COLS$
    FROM
      POINTOFINTEREST
    JOIN
      POIDESC ON ( POINTOFINTEREST.POINTOFINTEREST_ID = POIDESC.POINTOFINTEREST_ID )
    WHERE
      POINTOFINTEREST.STORE_ID = ?StoreID?
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest[(StoreID=)]
  base_table=POINTOFINTEREST
  sql=
    SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_KEY_COL$
    FROM
      POINTOFINTEREST
    WHERE
      POINTOFINTEREST.STORE_ID = ?StoreID?
END_XPATH_TO_SQL_STATEMENT

<!-- FIND_BY_POINTOFINTERESTID_XPATH -->
BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest[(PointOfInterestIdentifier[(UniqueID=)] and StoreID=)]+IBM_All
  base_table=POINTOFINTEREST
  sql=
    SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_IBM_All_AP_COLS$, POIDESC.$COLS:POIDESC_IBM_All_AP_COLS$
    FROM
      POINTOFINTEREST
    JOIN
      POIDESC ON ( POINTOFINTEREST.POINTOFINTEREST_ID = POIDESC.POINTOFINTEREST_ID )
    WHERE
      POINTOFINTEREST.POINTOFINTEREST_ID = ?UniqueID? AND
      POINTOFINTEREST.STORE_ID = ?StoreID?
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest[(PointOfInterestIdentifier[(UniqueID=)] and StoreID=)]
  base_table=POINTOFINTEREST
  sql=
    SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_KEY_COL$
    FROM
      POINTOFINTEREST
    WHERE
      POINTOFINTEREST.POINTOFINTEREST_ID = ?UniqueID? AND
      POINTOFINTEREST.STORE_ID = ?StoreID?
END_XPATH_TO_SQL_STATEMENT


<!-- FIND_BY_STATUS_XPATH -->
BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest[(Status= and StoreID=)]+IBM_All
  base_table=POINTOFINTEREST
  sql=
    SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_IBM_All_AP_COLS$, POIDESC.$COLS:POIDESC_IBM_All_AP_COLS$
    FROM
      POINTOFINTEREST
    JOIN
      POIDESC ON ( POINTOFINTEREST.POINTOFINTEREST_ID = POIDESC.POINTOFINTEREST_ID )
    WHERE
      POINTOFINTEREST.STATUS = ?Status? AND
      POINTOFINTEREST.STORE_ID = ?StoreID?
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest[(Status= and StoreID=)]
  base_table=POINTOFINTEREST
  sql=
    SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_KEY_COL$
    FROM
      POINTOFINTEREST
    WHERE
      POINTOFINTEREST.STATUS = ?Status? AND
      POINTOFINTEREST.STORE_ID = ?StoreID?
END_XPATH_TO_SQL_STATEMENT

<!-- FIND_BY_POITYPE_XPATH -->
BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest[(POIType= and StoreID=)]+IBM_All
  base_table=POINTOFINTEREST
  sql=
    SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_IBM_All_AP_COLS$, POIDESC.$COLS:POIDESC_IBM_All_AP_COLS$
    FROM
      POINTOFINTEREST
    JOIN
      POIDESC ON ( POINTOFINTEREST.POINTOFINTEREST_ID = POIDESC.POINTOFINTEREST_ID )
    WHERE
      POINTOFINTEREST.POITYPE = ?POIType? AND
      POINTOFINTEREST.STORE_ID = ?StoreID?
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest[(POIType= and StoreID=)]
  base_table=POINTOFINTEREST
  sql=
    SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_KEY_COL$
    FROM
      POINTOFINTEREST
    WHERE
      POINTOFINTEREST.POITYPE = ?POIType? AND
      POINTOFINTEREST.STORE_ID = ?StoreID?
END_XPATH_TO_SQL_STATEMENT



<!-- FIND_BY_REGIONID_XPATH -->
BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest[(RegionID= and StoreID=)]+IBM_All
  base_table=POINTOFINTEREST
  sql=
    SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_IBM_All_AP_COLS$, POIDESC.$COLS:POIDESC_IBM_All_AP_COLS$
    FROM
      POINTOFINTEREST
    JOIN
      POIDESC ON ( POINTOFINTEREST.POINTOFINTEREST_ID = POIDESC.POINTOFINTEREST_ID )
    WHERE
      POINTOFINTEREST.REGION_ID = ?RegionID? AND
      POINTOFINTEREST.STORE_ID = ?StoreID?
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest[(RegionID= and StoreID=)]
  base_table=POINTOFINTEREST
  sql=
    SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_KEY_COL$
    FROM
      POINTOFINTEREST
    WHERE
      POINTOFINTEREST.REGION_ID = ?RegionID? AND
      POINTOFINTEREST.STORE_ID = ?StoreID?
END_XPATH_TO_SQL_STATEMENT


<!-- FIND_BY_ZONEID_XPATH -->
BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest[(StoreID= and ZoneID=)]+IBM_All
  base_table=POINTOFINTEREST
  sql=
    SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_IBM_All_AP_COLS$, POIDESC.$COLS:POIDESC_IBM_All_AP_COLS$
    FROM
      POINTOFINTEREST
    JOIN
      POIDESC ON ( POINTOFINTEREST.POINTOFINTEREST_ID = POIDESC.POINTOFINTEREST_ID )
    WHERE
      POINTOFINTEREST.ZONE_ID = ?ZoneID? AND
      POINTOFINTEREST.STORE_ID = ?StoreID?
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest[(StoreID= and ZoneID=)]
  base_table=POINTOFINTEREST
  sql=
    SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_KEY_COL$
    FROM
      POINTOFINTEREST
    WHERE
      POINTOFINTEREST.ZONE_ID = ?ZoneID? AND
      POINTOFINTEREST.STORE_ID = ?StoreID?
END_XPATH_TO_SQL_STATEMENT

<!-- FIND_BY_CELLID_XPATH -->
BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest[(CellID= and StoreID=)]+IBM_All
  base_table=POINTOFINTEREST
  sql=
    SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_IBM_All_AP_COLS$, POIDESC.$COLS:POIDESC_IBM_All_AP_COLS$
    FROM
      POINTOFINTEREST
    JOIN
      POIDESC ON ( POINTOFINTEREST.POINTOFINTEREST_ID = POIDESC.POINTOFINTEREST_ID )
    WHERE
      POINTOFINTEREST.CELL_ID = ?CellID? AND
      POINTOFINTEREST.STORE_ID = ?StoreID?
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest[(CellID= and StoreID=)]
  base_table=POINTOFINTEREST
  sql=
    SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_KEY_COL$
    FROM
      POINTOFINTEREST
    WHERE
      POINTOFINTEREST.CELL_ID = ?CellID? AND
      POINTOFINTEREST.STORE_ID = ?StoreID?
END_XPATH_TO_SQL_STATEMENT


<!-- FIND_BY_TAG_XPATH -->
BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest[StoreID= and search()]
  base_table=POINTOFINTEREST
  sql=
    SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_KEY_COL$
    FROM
      POINTOFINTEREST, $ATTR_TBLS$
    WHERE
      POINTOFINTEREST.STORE_ID = ?StoreID? AND
      POINTOFINTEREST.$ATTR_CNDS$
END_XPATH_TO_SQL_STATEMENT


<!-- FIND_BY_TAG_XPATH -->
BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest[POIType= and StoreID= and search()]
  base_table=POINTOFINTEREST
  sql=
    SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_KEY_COL$
    FROM
      POINTOFINTEREST, $ATTR_TBLS$
    WHERE
      POINTOFINTEREST.STORE_ID = ?StoreID? AND
      POINTOFINTEREST.POIType = ?POIType? AND
      POINTOFINTEREST.$ATTR_CNDS$
END_XPATH_TO_SQL_STATEMENT



<!-- FIND_BY_REGIONID_AND_POITYPE_XPATH -->
BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest[(POIType= and RegionID= and StoreID=)]+IBM_All
  base_table=POINTOFINTEREST
  sql=
    SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_IBM_All_AP_COLS$, POIDESC.$COLS:POIDESC_IBM_All_AP_COLS$
    FROM
      POINTOFINTEREST
    JOIN
      POIDESC ON ( POINTOFINTEREST.POINTOFINTEREST_ID = POIDESC.POINTOFINTEREST_ID )
    WHERE
      POINTOFINTEREST.POITYPE = ?POIType? AND
      POINTOFINTEREST.REGION_ID = ?RegionID? AND
      POINTOFINTEREST.STORE_ID = ?StoreID?
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest[(POIType= and RegionID= and StoreID=)]
  base_table=POINTOFINTEREST
  sql=
    SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_KEY_COL$
    FROM
      POINTOFINTEREST
    WHERE
      POINTOFINTEREST.POITYPE = ?POIType? AND
      POINTOFINTEREST.REGION_ID = ?RegionID? AND
      POINTOFINTEREST.STORE_ID = ?StoreID?
END_XPATH_TO_SQL_STATEMENT


<!-- ----------------------------------- -->
<!-- END INSERTION OF CUSTOM TPL SCRIPTS -->
<!-- ----------------------------------- -->


BEGIN_ASSOCIATION_SQL_STATEMENT
  name=IBM_POINTOFINTEREST_Access_Profile_IBM_All
  base_table=POINTOFINTEREST
  sql =
    SELECT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_IBM_All_AP_COLS$
    FROM
      POINTOFINTEREST
    WHERE
      POINTOFINTEREST.POINTOFINTEREST_ID IN ( $ENTITY_PKS$ )
END_ASSOCIATION_SQL_STATEMENT

BEGIN_ASSOCIATION_SQL_STATEMENT
  name=IBM_POIDESC_Access_Profile_IBM_All
  base_table=POIDESC
  sql =
    SELECT
      POIDESC.$COLS:POIDESC_IBM_All_AP_COLS$
    FROM
      POIDESC
    WHERE
      POIDESC.POIDESC_ID IN ( $ENTITY_PKS$ )
END_ASSOCIATION_SQL_STATEMENT

BEGIN_ASSOCIATION_SQL_STATEMENT
  name=IBM_POINTOFINTEREST_Access_Profile_IBM_Details
  base_table=POINTOFINTEREST
  sql =
    SELECT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_IBM_Details_AP_COLS$
    FROM
      POINTOFINTEREST
    WHERE
      POINTOFINTEREST.POINTOFINTEREST_ID IN ( $ENTITY_PKS$ )
END_ASSOCIATION_SQL_STATEMENT

BEGIN_ASSOCIATION_SQL_STATEMENT
  name=IBM_POIDESC_Access_Profile_IBM_Details
  base_table=POIDESC
  sql =
    SELECT
      POIDESC.$COLS:POIDESC_IBM_Details_AP_COLS$
    FROM
      POIDESC
    WHERE
      POIDESC.POIDESC_ID IN ( $ENTITY_PKS$ )
END_ASSOCIATION_SQL_STATEMENT

BEGIN_ASSOCIATION_SQL_STATEMENT
  name=IBM_POINTOFINTEREST_Access_Profile_IBM_Summary
  base_table=POINTOFINTEREST
  sql =
    SELECT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_IBM_Summary_AP_COLS$
    FROM
      POINTOFINTEREST
    WHERE
      POINTOFINTEREST.POINTOFINTEREST_ID IN ( $ENTITY_PKS$ )
END_ASSOCIATION_SQL_STATEMENT

BEGIN_ASSOCIATION_SQL_STATEMENT
  name=IBM_POIDESC_Access_Profile_IBM_Summary
  base_table=POIDESC
  sql =
    SELECT
      POIDESC.$COLS:POIDESC_IBM_Summary_AP_COLS$
    FROM
      POIDESC
    WHERE
      POIDESC.POIDESC_ID IN ( $ENTITY_PKS$ )
END_ASSOCIATION_SQL_STATEMENT

BEGIN_PROFILE
  name=IBM_All
  BEGIN_ENTITY
    base_table=POINTOFINTEREST
    associated_sql_statement=IBM_POINTOFINTEREST_Access_Profile_IBM_All
  END_ENTITY
END_PROFILE

BEGIN_PROFILE
  name=IBM_POINTOFINTEREST_Access_Profile_IBM_All
  BEGIN_ENTITY
    base_table=POINTOFINTEREST
    associated_sql_statement=IBM_POINTOFINTEREST_Access_Profile_IBM_All
  END_ENTITY
END_PROFILE

BEGIN_PROFILE
  name=IBM_POIDESC_Access_Profile_IBM_All
  BEGIN_ENTITY
    base_table=POIDESC
    associated_sql_statement=IBM_POIDESC_Access_Profile_IBM_All
  END_ENTITY
END_PROFILE

BEGIN_PROFILE
  name=IBM_Details
  BEGIN_ENTITY
    base_table=POINTOFINTEREST
    associated_sql_statement=IBM_POINTOFINTEREST_Access_Profile_IBM_Details
  END_ENTITY
END_PROFILE

BEGIN_PROFILE
  name=IBM_POINTOFINTEREST_Access_Profile_IBM_Details
  BEGIN_ENTITY
    base_table=POINTOFINTEREST
    associated_sql_statement=IBM_POINTOFINTEREST_Access_Profile_IBM_Details
  END_ENTITY
END_PROFILE

BEGIN_PROFILE
  name=IBM_POIDESC_Access_Profile_IBM_Details
  BEGIN_ENTITY
    base_table=POIDESC
    associated_sql_statement=IBM_POIDESC_Access_Profile_IBM_Details
  END_ENTITY
END_PROFILE

BEGIN_PROFILE
  name=IBM_Summary
  BEGIN_ENTITY
    base_table=POINTOFINTEREST
    associated_sql_statement=IBM_POINTOFINTEREST_Access_Profile_IBM_Summary
  END_ENTITY
END_PROFILE

BEGIN_PROFILE
  name=IBM_POINTOFINTEREST_Access_Profile_IBM_Summary
  BEGIN_ENTITY
    base_table=POINTOFINTEREST
    associated_sql_statement=IBM_POINTOFINTEREST_Access_Profile_IBM_Summary
  END_ENTITY
END_PROFILE

BEGIN_PROFILE
  name=IBM_POIDESC_Access_Profile_IBM_Summary
  BEGIN_ENTITY
    base_table=POIDESC
    associated_sql_statement=IBM_POIDESC_Access_Profile_IBM_Summary
  END_ENTITY
END_PROFILE

