<!--********************************************************************-->
<!--  Licensed Materials - Property of IBM                              -->
<!--                                                                    -->
<!--  WebSphere Commerce                                                -->
<!--                                                                    -->
<!--  (c) Copyright IBM Corp. 2011                                      -->
<!--                                                                    -->
<!--  US Government Users Restricted Rights - Use, duplication or       -->
<!--  disclosure restricted by GSA ADP Schedule Contract with IBM Corp. -->
<!--                                                                    -->
<!--********************************************************************-->

BEGIN_SYMBOL_DEFINITIONS
  COLS:POINTOFINTEREST_KEY_COL = POINTOFINTEREST:POINTOFINTEREST_ID
  COLS:POINTOFINTEREST_IBM_Update_AP_COLS = POINTOFINTEREST:*
  COLS:POINTOFINTEREST_IBM_All_AP_COLS = POINTOFINTEREST:*
  COLS:POINTOFINTEREST_IBM_Summary_AP_COLS = POINTOFINTEREST:POINTOFINTEREST_ID,OPTCOUNTER
  COLS:POIDESC_KEY_COL = POIDESC:POIDESC_ID
  COLS:POIDESC_IBM_Update_AP_COLS = POIDESC:*
  COLS:POIDESC_IBM_All_AP_COLS = POIDESC:*
  COLS:POIDESC_IBM_Summary_AP_COLS = POIDESC:POIDESC_ID,OPTCOUNTER,POINTOFINTEREST_ID
END_SYMBOL_DEFINITIONS


BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest
  base_table=POINTOFINTEREST
  sql=
    SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_KEY_COL$
    FROM
      POINTOFINTEREST
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest[PointOfInterestIdentifier[(UniqueID=)]]
  base_table=POINTOFINTEREST
  sql=
    SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_KEY_COL$
    FROM
      POINTOFINTEREST
    WHERE
      POINTOFINTEREST.POINTOFINTEREST_ID = ?UniqueID?
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
  name=/POIDESC[(POIDESC_ID=)]
  base_table=POIDESC
  sql=
    SELECT DISTINCT
      POIDESC.$COLS:POIDESC_KEY_COL$
    FROM
      POIDESC
    WHERE
      POIDESC.POIDESC_ID = ?POIDESC_ID?
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
  name=/POINTOFINTEREST[(POINTOFINTEREST_ID=)]
  base_table=POINTOFINTEREST
  sql=
    SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_KEY_COL$
    FROM
      POINTOFINTEREST
    WHERE
      POINTOFINTEREST.POINTOFINTEREST_ID = ?POINTOFINTEREST_ID?
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
  name=/POINTOFINTEREST/POIDESC[(POINTOFINTEREST_ID=)]
  base_table=POIDESC
  sql=
    SELECT DISTINCT
      POIDESC.$COLS:POIDESC_KEY_COL$
    FROM
      POIDESC
    WHERE
      POIDESC.POINTOFINTEREST_ID = ?POINTOFINTEREST_ID?
END_XPATH_TO_SQL_STATEMENT

<!-- ------------------------------------- -->
<!-- BEGIN INSERTION OF CUSTOM TPL SCRIPTS -->
<!-- ------------------------------------- -->

BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest+IBM_All
  base_table=POINTOFINTEREST
  sql=
  SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_IBM_All_AP_COLS$, POIDESC.$COLS:POIDESC_IBM_All_AP_COLS$
    FROM
      POINTOFINTEREST
    JOIN
      POIDESC ON ( POINTOFINTEREST.POINTOFINTEREST_ID = POIDESC.POINTOFINTEREST_ID )
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest+IBM_Update
  base_table=POINTOFINTEREST
  sql=
  SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_IBM_Update_AP_COLS$, POIDESC.$COLS:POIDESC_IBM_Update_AP_COLS$
    FROM
      POINTOFINTEREST
    JOIN
      POIDESC ON ( POINTOFINTEREST.POINTOFINTEREST_ID = POIDESC.POINTOFINTEREST_ID )
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest+IBM_Summary
  base_table=POINTOFINTEREST
  sql=
  SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_IBM_Summary_AP_COLS$, POIDESC.$COLS:POIDESC_IBM_Summary_AP_COLS$
    FROM
      POINTOFINTEREST
    JOIN
      POIDESC ON ( POINTOFINTEREST.POINTOFINTEREST_ID = POIDESC.POINTOFINTEREST_ID )
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest[PointOfInterestIdentifier[(UniqueID=)]]+IBM_All
  base_table=POINTOFINTEREST
  sql=
    SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_IBM_All_AP_COLS$, POIDESC.$COLS:POIDESC_IBM_All_AP_COLS$
    FROM
      POINTOFINTEREST
    JOIN
      POIDESC ON ( POINTOFINTEREST.POINTOFINTEREST_ID = POIDESC.POINTOFINTEREST_ID )
    WHERE
      POINTOFINTEREST.POINTOFINTEREST_ID = ?UniqueID?
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest[PointOfInterestIdentifier[(UniqueID=)]]+IBM_Update
  base_table=POINTOFINTEREST
  sql=
    SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_IBM_Update_AP_COLS$, POIDESC.$COLS:POIDESC_IBM_Update_AP_COLS$
    FROM
      POINTOFINTEREST
    JOIN
      POIDESC ON ( POINTOFINTEREST.POINTOFINTEREST_ID = POIDESC.POINTOFINTEREST_ID )
    WHERE
      POINTOFINTEREST.POINTOFINTEREST_ID = ?UniqueID?
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest[PointOfInterestIdentifier[(UniqueID=)]]+IBM_Summary
  base_table=POINTOFINTEREST
  sql=
    SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_IBM_Summary_AP_COLS$, POIDESC.$COLS:POIDESC_IBM_Summary_AP_COLS$
    FROM
      POINTOFINTEREST
    JOIN
      POIDESC ON ( POINTOFINTEREST.POINTOFINTEREST_ID = POIDESC.POINTOFINTEREST_ID )
    WHERE
      POINTOFINTEREST.POINTOFINTEREST_ID = ?UniqueID?
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
  name=/PointOfInterest[search()]
  base_table=POINTOFINTEREST
  sql=
    SELECT DISTINCT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_IBM_Update_AP_COLS$, POIDESC.$COLS:POIDESC_IBM_Update_AP_COLS$
    FROM
      POINTOFINTEREST, $ATTR_TBLS$, POIDESC
    WHERE
      POINTOFINTEREST.POINTOFINTEREST_ID = POIDESC.POINTOFINTEREST_ID AND
      POINTOFINTEREST.$ATTR_CNDS$
END_XPATH_TO_SQL_STATEMENT



<!-- ------------------------------------- -->
<!-- END INSERTION OF CUSTOM TPL SCRIPTS   -->
<!-- ------------------------------------- -->

BEGIN_ASSOCIATION_SQL_STATEMENT
  name=IBM_POINTOFINTEREST_Access_Profile_IBM_Update
  base_table=POINTOFINTEREST
  sql =
    SELECT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_IBM_Update_AP_COLS$
    FROM
      POINTOFINTEREST
    WHERE
      POINTOFINTEREST.POINTOFINTEREST_ID IN ( $ENTITY_PKS$ )
END_ASSOCIATION_SQL_STATEMENT

BEGIN_ASSOCIATION_SQL_STATEMENT
  name=IBM_POIDESC_Access_Profile_IBM_Update
  base_table=POIDESC
  sql =
    SELECT
      POIDESC.$COLS:POIDESC_IBM_Update_AP_COLS$
    FROM
      POIDESC
    WHERE
      POIDESC.POIDESC_ID IN ( $ENTITY_PKS$ )
END_ASSOCIATION_SQL_STATEMENT

BEGIN_ASSOCIATION_SQL_STATEMENT
  name=IBM_POINTOFINTEREST_Access_Profile_IBM_All
  base_table=POINTOFINTEREST
  sql =
    SELECT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_IBM_All_AP_COLS$
    FROM
      POINTOFINTEREST
    WHERE
      POINTOFINTEREST.POINTOFINTEREST_ID IN ( $ENTITY_PKS$ )
END_ASSOCIATION_SQL_STATEMENT

BEGIN_ASSOCIATION_SQL_STATEMENT
  name=IBM_POIDESC_Access_Profile_IBM_All
  base_table=POIDESC
  sql =
    SELECT
      POIDESC.$COLS:POIDESC_IBM_All_AP_COLS$
    FROM
      POIDESC
    WHERE
      POIDESC.POIDESC_ID IN ( $ENTITY_PKS$ )
END_ASSOCIATION_SQL_STATEMENT

BEGIN_ASSOCIATION_SQL_STATEMENT
  name=IBM_POINTOFINTEREST_Access_Profile_IBM_Summary
  base_table=POINTOFINTEREST
  sql =
    SELECT
      POINTOFINTEREST.$COLS:POINTOFINTEREST_IBM_Summary_AP_COLS$
    FROM
      POINTOFINTEREST
    WHERE
      POINTOFINTEREST.POINTOFINTEREST_ID IN ( $ENTITY_PKS$ )
END_ASSOCIATION_SQL_STATEMENT

BEGIN_ASSOCIATION_SQL_STATEMENT
  name=IBM_POIDESC_Access_Profile_IBM_Summary
  base_table=POIDESC
  sql =
    SELECT
      POIDESC.$COLS:POIDESC_IBM_Summary_AP_COLS$
    FROM
      POIDESC
    WHERE
      POIDESC.POIDESC_ID IN ( $ENTITY_PKS$ )
END_ASSOCIATION_SQL_STATEMENT

BEGIN_PROFILE
  name=IBM_Update
  BEGIN_ENTITY
    base_table=POINTOFINTEREST
    associated_sql_statement=IBM_POINTOFINTEREST_Access_Profile_IBM_Update
  END_ENTITY
END_PROFILE

BEGIN_PROFILE
  name=IBM_POINTOFINTEREST_Access_Profile_IBM_Update
  BEGIN_ENTITY
    base_table=POINTOFINTEREST
    associated_sql_statement=IBM_POINTOFINTEREST_Access_Profile_IBM_Update
  END_ENTITY
END_PROFILE

BEGIN_PROFILE
  name=IBM_POIDESC_Access_Profile_IBM_Update
  BEGIN_ENTITY
    base_table=POIDESC
    associated_sql_statement=IBM_POIDESC_Access_Profile_IBM_Update
  END_ENTITY
END_PROFILE

BEGIN_PROFILE
  name=IBM_All
  BEGIN_ENTITY
    base_table=POINTOFINTEREST
    associated_sql_statement=IBM_POINTOFINTEREST_Access_Profile_IBM_All
  END_ENTITY
END_PROFILE

BEGIN_PROFILE
  name=IBM_POINTOFINTEREST_Access_Profile_IBM_All
  BEGIN_ENTITY
    base_table=POINTOFINTEREST
    associated_sql_statement=IBM_POINTOFINTEREST_Access_Profile_IBM_All
  END_ENTITY
END_PROFILE

BEGIN_PROFILE
  name=IBM_POIDESC_Access_Profile_IBM_All
  BEGIN_ENTITY
    base_table=POIDESC
    associated_sql_statement=IBM_POIDESC_Access_Profile_IBM_All
  END_ENTITY
END_PROFILE

BEGIN_PROFILE
  name=IBM_Summary
  BEGIN_ENTITY
    base_table=POINTOFINTEREST
    associated_sql_statement=IBM_POINTOFINTEREST_Access_Profile_IBM_Summary
  END_ENTITY
END_PROFILE

BEGIN_PROFILE
  name=IBM_POINTOFINTEREST_Access_Profile_IBM_Summary
  BEGIN_ENTITY
    base_table=POINTOFINTEREST
    associated_sql_statement=IBM_POINTOFINTEREST_Access_Profile_IBM_Summary
  END_ENTITY
END_PROFILE

BEGIN_PROFILE
  name=IBM_POIDESC_Access_Profile_IBM_Summary
  BEGIN_ENTITY
    base_table=POIDESC
    associated_sql_statement=IBM_POIDESC_Access_Profile_IBM_Summary
  END_ENTITY
END_PROFILE

