CKEDITOR.plugins.add("ibmtoolbars",{lang:"ar,ca,cs,da,de,el,en,es,fi,fr,he,hr,hu,it,iw,ja,kk,ko,nb,nl,no,pl,pt,pt-br,ro,ru,sk,sl,sv,th,tr,uk,zh,zh-cn,zh-tw",requires:["menubutton","toolbar"],init:function(a){function b(){e.$.removeEventListener?(e.$.removeEventListener("scroll",k,!1),e.$.removeEventListener("resize",r,!1)):e.$.detachEvent&&(e.$.detachEvent("onscroll",k),e.$.detachEvent("onresize",r))}function c(){e.$.addEventListener?(e.$.addEventListener("scroll",k,!1),e.$.addEventListener("resize",
r,!1)):e.$.attachEvent&&(e.$.attachEvent("onscroll",k),e.$.attachEvent("onresize",r))}function g(){d.removeClass("cke_floating_toolbox");d.removeStyle("width");j.removeStyle("width");s.remove()}function f(a,b){b&&(d.removeStyle("width"),j.removeStyle("width"));var e=CKEDITOR.env.ie?a.$.clientWidth:parseInt(a.getComputedStyle("width"),10);d.setStyle("width",e+"px");j.setStyle("width",e+"px")}function i(){var a=l.getDocumentPosition().x,b=e.getScrollPosition().x;d.setStyle("left",a-b+"px")}a.config.blockedKeystrokes.push(CKEDITOR.SHIFT+
CKEDITOR.ALT+73);a.config.blockedKeystrokes.push(CKEDITOR.SHIFT+CKEDITOR.ALT+79);a.setKeystroke(CKEDITOR.SHIFT+CKEDITOR.ALT+73,"indent");a.setKeystroke(CKEDITOR.SHIFT+CKEDITOR.ALT+79,"outdent");if(a.config.ibmFloatToolbar&&!(CKEDITOR.env.quirks&&CKEDITOR.env.ie||a.elementMode==CKEDITOR.ELEMENT_MODE_INLINE)){var d,j,l,t,e,p,u,m=!1,q=!1,s=new CKEDITOR.dom.element("div"),v=/^(\d+(?:\.\d+)?)%$/,n=a.ui.items,o;for(o in n)if("panelbutton"==n[o].type||"richcombo"==n[o].type)n[o].args[0].onOpen&&(n[o].args[0].origOnOpen=
n[o].args[0].onOpen),n[o].args[0].onOpen=function(){this.origOnOpen&&this.origOnOpen();q=true};var k=function(){if("wysiwyg"==a.mode&&a.container.isVisible()){if(!l||null==l.getParent())l=a.container.getElementsByTag("iframe").getItem(0);var b=m?30:0;p=l.getDocumentPosition().y+b;var b=e.getViewPaneSize().height,h=e.getScrollPosition().y}if("wysiwyg"!=a.mode||p>h&&p<h+b)g(),m&&(e.$.dojo&&w(),m=!1);else if(h>p){for(var b=-1,c,h=0;h<d.getChildCount();h++)c=d.getChild(h),"cke_toolbar"==c.getAttribute("class")&&
(c=CKEDITOR.env.ie?c.$.clientWidth:parseInt(c.getComputedStyle("width"),10),c>b&&(b=c));-1!=b&&s.setStyle("width",b+"px");h=CKEDITOR.env.ie?d.$.clientHeight:parseInt(d.getComputedStyle("height"),10);s.setStyle("height",h+"px");t.append(s);m||(e.$.dojo&&w(),m=!0);a.config.width?(h=a.config.width,v.exec(h)?f(j):parseInt(CKEDITOR.tools.convertToPx(h),10)<b?f(j):d.setStyle("width",h)):CKEDITOR.env.webkit?f(j):f(t);i();d.addClass("cke_floating_toolbox")}},r=function(){m&&(a.config.width?v.exec(a.config.width)&&
f(j,!0):CKEDITOR.env.chrome?f(d):CKEDITOR.env.webkit?f(j,!0):f(d,!0),i())},w=function(){var a=d.$;dojo.style(a,"opacity","0");dojo.fadeIn({node:a,duration:500}).play()};a.on("destroy",function(){l=null});a.on("mode",function(){e&&("wysiwyg"==a.mode?(l=a.container.getElementsByTag("iframe").getItem(0),c()):(k(),b()))});a.on("blur",function(){setTimeout(function(){b();"wysiwyg"==a.mode&&!q&&(g(),m=!1)},100)});a.on("focus",function(){if(!d){for(var b=a.container.getElementsByTag("span"),h=0;h<b.count();h++)if("cke_toolbox"==
b.getItem(h).getAttribute("class")){d=b.getItem(h);break}if(!d)return;t=d.getParent();e=d.getWindow();j=d.getParent().getNext();u=a.element.getSize("height")}q=!1;k();"wysiwyg"==a.mode&&c()});a.on("resize",function(){if(CKEDITOR.env.ie){var b=a.element.getSize("height");b<u&&k();u=b}});a.on("dialogShow",function(a){q="find"==a.data.getName()?!1:!0});a.on("dialogHide",function(a){setTimeout(function(){if("find"==a.data.getName()){var b=a.editor,f=b.getSelection(),c=f.getStartElement().getDocumentPosition().y;
CKEDITOR.env.ie&&(c+=1);p=l.getDocumentPosition().y;var b=p+c-b.window.getScrollPosition().y,c=d.getParent().getSize("height",!0),g=e.getScrollPosition().y,j=g+c,i=e.getViewPaneSize().height,k=i-c;b<g||b>g+i?f.scrollIntoView():b>j&&b<j+k||(f=e.getScrollPosition().y-c-10,e.$.scrollTo(e.getScrollPosition().x,f))}},0)});a.on("menuShow",function(){q=!0});a.on("beforeCommandExec",function(a){if("toolbarFocus"===a.data.name||"elementsPathFocus"===a.data.name)q=!0})}},afterInit:function(a){a.config.menus&&
this.createConfigCommandMenus(a)},createConfigCommandMenus:function(a){var b,c=a.config.menus;for(b in c){var g=c[b];if(!("string"!=typeof g.buttonClass||"undefined"===typeof g.commands)){var f;if("string"===typeof g.label){f=a.lang;for(var i=g.label.split("."),d=0,j=i.length;d<j;++d)f=f[i[d]]}else f=a.lang.ibmtoolbars.menu[b];i="menu"+b;"string"===typeof g.groupName&&(i=g.groupName);(new CKEDITOR.ibm.menus(a,i)).createCommandMenu("Menu"+b.substr(0,1).toUpperCase()+b.substr(1),f,g.buttonClass,g.commands,
g.toolbar,b)}}},replaceLinkButtonWithMenu:function(a){var b=a.config;if(b.menus&&b.menus.link){a=b.toolbar instanceof Array?a.config.toolbar:a.config["toolbar_"+a.config.toolbar];Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){null==b?b=0:0>b&&(b=Math.max(0,this.length+b));for(var c=b,d=this.length;c<d;c++)if(this[c]===a)return c;return-1});for(b=0;b<a.length;b++)if("object"===typeof a[b]){if(c=a[b].items.indexOf("Link"),-1!==c){a[b].items[c]="MenuLink";break}}else{var c=a[b].indexOf("Link");
if(-1!==c){a[b][c]="MenuLink";break}}}}});"undefined"===typeof CKEDITOR.ibm&&(CKEDITOR.ibm={});
CKEDITOR.ibm.menus=CKEDITOR.tools.createClass({$:function(a,b){this.editor=a;this._.menuGroup=b;this._.menuItemOrder=0;typeof this.editor._.menuGroups[b]==="undefined"&&this.editor.addMenuGroup(b)},privates:{getCommandLabel:function(a){for(var b in this.editor.ui.items)if(this.editor.ui.items[b].command===a)return this.editor.ui.items[b].args[0].label;return""},getMenuItemOrder:function(){return++this._.menuItemOrder},getMenuItemState:function(a){a=this.editor.getMenuItem(a);if(typeof a==="undefined")return CKEDITOR.TRISTATE_OFF;
a=this.editor.getCommand(a.cmdName);return typeof a==="undefined"?CKEDITOR.TRISTATE_OFF:a.state}},proto:{getIconPath:function(){return this._.iconPath},getMenuGroup:function(){return this._.menuGroup},addMenuItem:function(a,b){typeof this.editor.getCommand(a)==="object"&&this.editor.addMenuItem(b+"_"+a,{cmdName:a,onClick:function(){this.editor.getCommand(this.cmdName).exec()},icon:a,group:this.getMenuGroup(),label:this._.getCommandLabel(a),order:this._.getMenuItemOrder(),className:"toolbarContextMenu"})},
createCommandMenu:function(a,b,c,g,f,i){var d=this;this.createMenu(a,{label:b,title:b,className:c,icon:i=="paste"?"pastetext":i,toolbar:f,requiredContent:i=="link"?"a[href]":"",modes:{wysiwyg:1},onRender:function(){for(var b=0;b<g.length;++b)d.addMenuItem(g[b],a)},onMenu:function(){for(var b={},c=0;c<g.length;++c){var f=a+"_"+g[c];b[f]=d._.getMenuItemState(f)}return b}})},createMenu:function(a,b){this.editor.getCommand("link")!=="undefined"&&this.editor.getCommand("link")!=null&&this.editor.ui.add(a,
CKEDITOR.UI_MENUBUTTON,b)}}});CKEDITOR.tools.extend(CKEDITOR.config,{ibmFloatToolbar:!1});CKEDITOR.config.toolbar_Slim=["Bold Italic Underline Strike TextColor NumberedList BulletedList BidiLtr BidiRtl Language Image Link Smiley".split(" ")];
CKEDITOR.config.toolbar_Medium=[{name:"tools",items:["Undo","Redo","MenuPaste","IbmSpellChecker"]},{name:"styles",items:"Font FontSize Bold Italic Underline Strike TextColor BGColor".split(" ")},{name:"paragraph",items:"JustifyLeft JustifyCenter JustifyRight JustifyBlock NumberedList BulletedList Indent Outdent BidiLtr BidiRtl Language".split(" ")},{name:"insert",items:["Table","Image","MenuLink","Anchor","Smiley"]}];
CKEDITOR.config.toolbar_Large=[{name:"tools",items:"Undo Redo MenuPaste Find IbmSpellChecker ShowBlocks IbmPermanentPen".split(" ")},{name:"styles",items:"Format Font FontSize Bold Italic Underline Strike TextColor BGColor Subscript Superscript RemoveFormat".split(" ")},{name:"paragraph",items:"JustifyLeft JustifyCenter JustifyRight JustifyBlock NumberedList BulletedList Indent Outdent Blockquote BidiLtr BidiRtl Language".split(" ")},{name:"insert",items:"Table Image MenuLink Anchor Iframe Flash PageBreak HorizontalRule SpecialChar Smiley".split(" ")}];
CKEDITOR.config.toolbar="Large";