CKEDITOR.dialog.add("tablesort",function(b){function m(){for(var a=0;a<n().getChildCount();a++)for(var c=n().getChildren().getItem(a),b=0;b<c.getChildCount();b++)if(c.getChild&&c.getChild(b).getAttribute&&1<c.getChild(b).getAttribute("rowspan"))return!0;return!1}var o,n=function(){var a=b.getSelection().getSelectedElement();if(a&&"table"==a.getName())for(var c=0;c<a.getChildCount();c++)if("tbody"==a.getChild(c).getName())return a.getChild(c)},u=function(a,c,i){function w(a){for(var b=0;b<a.length;b++)if(!isNaN(a[b].val))return!0;
return!1}function m(a){return function(b,c){return 1*(b[a]<c[a]?-1:b[a]>c[a]?1:0)}}function u(a){return function(b,c){return 1*(c[a]<b[a]?-1:c[a]>b[a]?1:0)}}function x(a){return function(b,c){return p(c[a])-p(b[a])}}function p(a){a=parseFloat(a);return a=isNaN(a)?-1:a}function y(a){return function(b,c){return p(b[a])-p(c[a])}}var k,d=[],q={},e={},g=n();k=g.getChildren();for(var j=0;j<g.getChildCount();j++){var f=k.getItem(j);q[j]=f;for(var l=[],s=0;s<f.getChildCount();s++){var h=f.getChild(s);if(h)if(1<
h.getAttribute("colspan"))for(var v=0;v<h.getAttribute("colspan");v++)h.getText&&h.getText()?l.push(h.getText()):l.push(h.getHtml());else h.getText&&h.getText()?l.push(h.getText()):l.push(h.getHtml())}e[j]=l}for(var t in e)e.hasOwnProperty(t)&&(f=e[t],d.push({id:t,val:f[a-1]}));"txt"==i?"desc"==c?d.sort(u("val")):d.sort(m("val")):w(d)&&("desc"==c?d.sort(x("val")):d.sort(y("val")));if(a=0<d.length?k.getItem(0).$.parentNode:null){for(var r=[],c=function(a,b){for(var c=b||0,d=r.length;c<d;c++)if(r[c]===
a)return!0;return!1},i=function(a,b){for(var c=0;c<b.length;c++)if(b[c].id===a)return c;return null},e=0;e<d.length;e++)if(g=d[e].id,(!c(e)||!c(g))&&e!=g)j=k.getItem(g).$,f=q[e].$,l=j.cloneNode(!0),f=a.replaceChild(l,f),a.replaceChild(f,j),q[e].$=l,q[g].$=f,k.getItem(e).$=l,k.getItem(g).$=f,f=i(g,d),j=i(e.toString(),d),d[f].id=e.toString(),d[j].id=g,r.push(e),r.push(g);b.getSelection();k=new CKEDITOR.dom.element(a);d=new CKEDITOR.dom.range(k.getParent());d.moveToElementEditablePosition(k);d.select();
o=b.getSelection().getCommonAncestor()}};return{title:b.lang.ibmtabletools.sortTable,minWidth:220,minHeight:50,onShow:function(){o=b.getSelection().getCommonAncestor();this.getParentEditor().execCommand("selectTable");m()?(this.getContentElement("info","mergedCells").getElement().show(),this.getButton("closeButton").getElement().show(),this.getButton("ok").getElement().hide(),this.getButton("cancel").getElement().hide(),this.getContentElement("info","column").getElement().hide(),this.getContentElement("info",
"type").getElement().hide(),this.getContentElement("info","order").getElement().hide()):(this.getContentElement("info","mergedCells").getElement().hide(),this.getButton("closeButton").getElement().hide(),this.getButton("ok").getElement().show(),this.getButton("cancel").getElement().show(),this.getContentElement("info","column").getElement().show(),this.getContentElement("info","type").getElement().show(),this.getContentElement("info","order").getElement().show())},onOk:function(){var a=this.getValueOf("info",
"column"),b=this.getValueOf("info","order"),i=this.getValueOf("info","type");u(a,b,i)},buttons:[CKEDITOR.dialog.cancelButton(b,{label:b.lang.common.close,id:"closeButton"}),CKEDITOR.dialog.okButton,CKEDITOR.dialog.cancelButton],contents:[{id:"info",style:"width: 100%",elements:[{type:"vbox",children:[{type:"hbox",children:[{label:b.lang.ibmtabletools.colNumber,type:"select",id:"column",items:[],onShow:function(){this.clear();for(var a=n(),c=0,i=0;i<a.getChildCount();i++){var m=a.getChildren().getItem(i);
c<m.getChildCount()&&(c=m.getChildCount())}for(a=0;a<c;a++)this.add(b.lang.ibmtabletools.colNumber+" "+(a+1),[a+1])},setup:function(a){a&&a[1]&&this.setValue(a[1])}},{type:"select",id:"type",label:b.lang.ibmtabletools.sortType,"default":"txt",items:[[b.lang.ibmtabletools.textType,"txt"],[b.lang.ibmtabletools.numericType,"num"]],setup:function(a){a&&a[2]&&this.setValue(a[2])}},{type:"select",id:"order",label:b.lang.ibmtabletools.sortOrder,"default":"asc",items:[[b.lang.ibmtabletools.sortOrderAsc,"asc"],
[b.lang.ibmtabletools.sortOrderDesc,"desc"]],setup:function(a){a&&a[3]&&this.setValue(a[3])}}]},{type:"html",id:"mergedCells",style:"text-align: center;",html:"<div>"+CKEDITOR.tools.htmlEncode(b.lang.ibmtabletools.mergedCells)+"</div>",focus:!1,onShow:function(){if(m()){var a=this.getDialog().parts.dialog.getParent();this.getElement().show();a.setAttribute("aria-describedby",this.domId)}},onHide:function(){var a=this.getDialog().parts.dialog.getParent();this.getElement().hide();a.hasAttribute("aria-describedby")&&
a.removeAttribute("aria-describedby");a=b.createRange();a.setStartAt(o,CKEDITOR.POSITION_BEFORE_END);a.setEndAt(o,CKEDITOR.POSITION_BEFORE_END);a.select()}}]}]}]}});