CKEDITOR.dialog.add("permanentpen",function(a){function q(c,b){if(Object.keys){var a=Object.keys(c),f=Object.keys(b);if(a.length!=f.length)return!1}for(var e in c)if("undefined"!==typeof b[e]){if("textColor"==e||"bgColor"==e)c[e]=CKEDITOR.tools.convertRgbToHex(c[e]),b[e]=CKEDITOR.tools.convertRgbToHex(b[e]);if(c[e]!==b[e])return!1}else return!1;return!0}function l(c){var b=c.substring(4,c.length-1).split(",");if(0<=b[0]&&255>=b[0]&&0<=b[1]&&255>=b[1]&&0<=b[2]&&255>=b[2]){c=parseInt(b[0]).toString(16);
"0"==c&&(c="00");var a=parseInt(b[1]).toString(16);"0"==a&&(a="00");b=parseInt(b[2]).toString(16);"0"==b&&(b="00");return"#"+c+a+b}return!1}function n(c,b){var d=function(){this.removeListener("show",d);b(this,this._.parentDialog)};if(a._.storedDialogs.colordialog)a._.storedDialogs.colordialog.on("show",d);else CKEDITOR.on("dialogDefinition",function(b){if(b.data.name==c){var a=b.data.definition;b.removeListener();a.onLoad=CKEDITOR.tools.override(a.onLoad,function(b){return function(){this.on("show",
d);a.onLoad=b;"function"==typeof b&&b.call(this)}})}})}for(var k=a.config.fontSize_sizes.split(";"),o=[[a.lang.common.notSet,""]],f=0;f<k.length;f++){var g=k[f];g&&(g=g.split("/"),o.push(g))}for(var p=a.config.font_names.split(";"),k=[[a.lang.common.notSet,""]],f=0;f<p.length;f++)if(g=p[f])g=g.split("/"),k.push(g);var f=function(){var c=a.lang,b=c.colorbutton.colors,c=[[c.common.notSet,""]];div=CKEDITOR.document.createElement("div");for(var d in b)div.setStyle("color","#"+d),c.push([b[d],div.getStyle("color")]);
return c.sort(function(b,c){return b[0]>c[0]})}(),m=function(c,b){var b=b.toLowerCase(),a;"rgb"==b.substring(0,3)?a=l(b):"#"==b.substring(0,1)&&4==b.length&&(a=convertTo6DigitHex(b));for(var f=null==c?this:c,e=f.getInputElement().$,g=e.length;g--;){var h=e.options[g].value.toLowerCase();if(h===b||h===a||l(h)===b){e.options[g].selected="selected";break}}-1==g&&(f.add(b,b),e.options[e.length-1].selected="selected")},i=CKEDITOR.tools.getNextId()+"_bgcolorswatch",j=CKEDITOR.tools.getNextId()+"_textcolorswatch",
h=function(a,b){!("rgb"==a.substring(0,3)&&18>=a.length)&&!("#"==a.substring(0,1)&&7>=a.length)&&0<=a.indexOf(" ")&&(a="");a?CKEDITOR.document.getById(b).setStyle("background-color",a):CKEDITOR.document.getById(b).removeStyle("background-color")};return{title:a.lang.ibmpermanentpen.title,minWidth:220,minHeight:50,onOk:function(){this.commitContent();a.config.styleDefined=!0;var c={bgColor:this.getValueOf("info","bgColorList"),textColor:this.getValueOf("info","textColorList"),fontName:this.getValueOf("info",
"font"),fontSize:this.getValueOf("info","size"),boldValue:this.getValueOf("info","bold"),italicValue:this.getValueOf("info","italic"),underlineValue:this.getValueOf("info","underline"),strikethroughValue:this.getValueOf("info","strikethrough")};a.config.ibmPermanentPenStyle&&!q(a.config.ibmPermanentPenStyle,c)&&a.fire("permanentPenStyleUpdated",c,a)},onShow:function(){this.setupContent()},contents:[{id:"info",label:a.lang.ibmpermanentpen.title,elements:[{type:"vbox",widths:["40%","5%","40%"],children:[{type:"hbox",
children:[{type:"select",id:"font",style:"width : 100%;",label:a.lang.ibmpermanentpen.font,items:k,requiredContent:"span{font-family}",setup:function(){this.setValue(a.config.fontName)},commit:function(){a.config.fontName=this.getValue()}},{type:"select",id:"size",style:"width : 100%;",label:a.lang.ibmpermanentpen.size,items:o,requiredContent:"span{font-size}",setup:function(){this.setValue(a.config.fontSize)},commit:function(){a.config.fontSize=this.getValue()}}]},{type:"hbox",children:[{type:"checkbox",
id:"bold",label:a.lang.ibmpermanentpen.bold,requiredContent:["strong","b"],setup:function(){this.setValue(a.config.boldValue)},commit:function(){a.config.boldValue=this.getValue()}},{type:"checkbox",id:"italic",requiredContent:["em","i"],label:a.lang.ibmpermanentpen.italic,setup:function(){this.setValue(a.config.italicValue)},commit:function(){a.config.italicValue=this.getValue()}},{type:"checkbox",id:"underline",requiredContent:"u",label:a.lang.ibmpermanentpen.underline,setup:function(){this.setValue(a.config.underlineValue)},
commit:function(){a.config.underlineValue=this.getValue()}},{type:"checkbox",id:"strikethrough",requiredContent:"s",label:a.lang.ibmpermanentpen.strikethrough,setup:function(){this.setValue(a.config.strikethroughValue)},commit:function(){a.config.strikethroughValue=this.getValue()}}]},{type:"vbox",padding:0,requiredContent:"span{color}",children:[{type:"hbox",widths:["70%","5%","25%"],children:[{type:"select",id:"textColorList",items:f,label:a.lang.ibmpermanentpen.textcolor,style:"width : 100%;",
onShow:function(){a.config.textColor&&m.call(this,null,a.config.textColor)},onChange:function(){h(this.getValue(),j)},onKeyUp:function(){h(this.getValue(),j)},commit:function(){a.config.textColor=this.getValue()}},{type:"html",html:'<div id="'+j+'" style="border: 1px solid #A0A0A0; height: 20px; width: 20px;"></div>',onLoad:function(){var a=CKEDITOR.document.getById(j);CKEDITOR.env.hc?a.hide():(a.show(),a.getParent().setStyle("vertical-align","bottom"))}},{type:"button",id:"textColorToChoose","class":"colorChooser",
label:a.lang.ibmpermanentpen.color,onLoad:function(){this.getElement().getParent().setStyle("vertical-align","bottom");CKEDITOR.env.hc?this.getElement().hide():(this.getElement().show(),this.origOnLoad&&this.origOnLoad(),this.getElement().getParent().setStyle("padding-bottom","5px"))},onClick:function(){a.getColorFromDialog(function(a){a&&this.getDialog().getContentElement("info","setTextColor").setValue(a);this.focus()},this);var c=this;n("colordialog",function(a){var d=c.getDialog().getContentElement("info",
"textColorList").getValue();d&&("rgb"==d.substring(0,3)?d=l(d):"#"==d.substring(0,1)&&4==d.length&&(d=convertTo6DigitHex(d)),d&&a.getContentElement("picker","currentColor").setValue(d))})}},{type:"text",id:"setTextColor",style:"display : none;","default":"",onChange:function(){this.origOnChange&&this.origOnChange(element);var a=this.getValue(),b=CKEDITOR.document.createElement("div");b.setStyle("color",a);b.getStyle("color")||(a="");m(this.getDialog().getContentElement("info","textColorList"),a);
h(a,j)},setup:function(){this.getElement().hide();h(a.config.textColor,j)}}]},{type:"hbox",widths:["70%","5%","25%"],requiredContent:"span{background-color}",children:[{type:"select",id:"bgColorList",label:a.lang.ibmpermanentpen.background,items:f,style:"width : 100%;",onShow:function(){a.config.bgColor&&m.call(this,null,a.config.bgColor)},onChange:function(){h(this.getValue(),i)},onKeyUp:function(){h(this.getValue(),i)},commit:function(){a.config.bgColor=this.getValue()}},{type:"html",html:'<div id="'+
i+'" style="border: 1px solid #A0A0A0; height: 20px; width: 20px;"></div>',onLoad:function(){var a=CKEDITOR.document.getById(i);CKEDITOR.env.hc?a.hide():(a.show(),a.getParent().setStyle("vertical-align","bottom"))}},{type:"button",id:"bgColorChoose","class":"colorChooser",label:a.lang.ibmpermanentpen.color,onLoad:function(){CKEDITOR.env.hc?this.getElement().hide():(this.getElement().show(),this.getElement().getParent().setStyle("vertical-align","bottom"),this.getElement().getParent().setStyle("padding-bottom",
"5px"))},onClick:function(){a.getColorFromDialog(function(a){a&&this.getDialog().getContentElement("info","bgColor").setValue(a);this.focus()},this);var c=this;n("colordialog",function(a){var d=c.getDialog().getContentElement("info","bgColorList").getValue();d&&("rgb"==d.substring(0,3)?d=l(d):"#"==d.substring(0,1)&&4==d.length&&(d=convertTo6DigitHex(d)),d&&a.getContentElement("picker","currentColor").setValue(d))})}},{type:"text",id:"bgColor",style:"display : none;","default":"",onChange:function(){var a=
this.getValue(),b=CKEDITOR.document.createElement("div");b.setStyle("background-color",a);b.getStyle("background-color")||(a="");m(this.getDialog().getContentElement("info","bgColorList"),a);h(a,i)},setup:function(){this.getElement().hide();h(a.config.bgColor,i)}}]}]}]}]}]}});