<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:oa="http://www.openapplications.org/oagis/9"
	xmlns:ord="http://www.ibm.com/xmlns/prod/commerce/order"
	targetNamespace="http://www.ibm.com/xmlns/prod/commerce/order"
	name="WebSphereCommerce-InventoryServices">

	<wsdl:types>
		<xsd:schema elementFormDefault="qualified"
			targetNamespace="http://www.openapplications.org/oagis/9">
			<xsd:include schemaLocation="../../xsd/OAGIS/9.0/BODs/Developer/ConfirmBOD.xsd" />
		</xsd:schema>
		<xsd:schema elementFormDefault="qualified"
			targetNamespace="http://www.ibm.com/xmlns/prod/commerce/order">
			<xsd:include
				schemaLocation="../../xsd/OAGIS/9.0/Overlays/IBM/Commerce/BODs/ProcessOrder.xsd" />
			<xsd:include
				schemaLocation="../../xsd/OAGIS/9.0/Overlays/IBM/Commerce/BODs/AcknowledgeOrder.xsd" />
			<xsd:include
				schemaLocation="../../xsd/OAGIS/9.0/Overlays/IBM/Commerce/BODs/SyncOrder.xsd" />
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="ProcessOrder">
		<wsdl:part name="ProcessOrder" element="ord:ProcessOrder" />
	</wsdl:message>
	<wsdl:message name="AcknowledgeOrder">
		<wsdl:part name="AcknowledgeOrder" element="ord:AcknowledgeOrder" />
	</wsdl:message>

	<wsdl:message name="SyncOrder">
		<wsdl:part name="SyncOrder" element="ord:SyncOrder" />
	</wsdl:message>
	<wsdl:message name="ConfirmBOD">
		<wsdl:part name="ConfirmBOD" element="oa:ConfirmBOD" />
	</wsdl:message>

	<wsdl:portType name="OrderServicesPortType">
		<wsdl:operation name="ProcessOrder">
			<wsdl:input message="ord:ProcessOrder" name="ProcessOrder" />
			<wsdl:output message="ord:AcknowledgeOrder" name="AcknowledgeOrder" />
		</wsdl:operation>
		<wsdl:operation name="SyncOrder">
			<wsdl:input message="ord:SyncOrder" name="SyncOrder" />
			<wsdl:output message="ord:ConfirmBOD" name="ConfirmBOD" />
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="OrderServices" type="ord:OrderServicesPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="ProcessOrder">
			<soap:operation
				soapAction="http://www.ibm.com/xmlns/prod/WebSphereCommerce/WebSphereCommerce-OrderServices.wsdl" />
			<wsdl:input name="ProcessOrder">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="AcknowledgeOrder">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="SyncOrder">
			<soap:operation
				soapAction="http://www.ibm.com/xmlns/prod/WebSphereCommerce/WebSphereCommerce-OrderServices.wsdl" />
			<wsdl:input name="SyncOrder">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="ConfirmBOD">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="WebSphereCommerce-OrderServices">
		<wsdl:port binding="ord:OrderServices" name="OrderServices">
			<soap:address location="http://localhost/webapp/wcs/services/OrderServices" />
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>
