<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:oa="http://www.openapplications.org/oagis/9"
	xmlns:_ctr="http://www.ibm.com/xmlns/prod/commerce/9/contract"
	targetNamespace="http://www.ibm.com/xmlns/prod/commerce/9/contract"
	name="ContractServices">

	<wsdl:types>

		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			targetNamespace="http://www.ibm.com/xmlns/prod/commerce/9/contract">
			
			<xsd:include schemaLocation="../xsd/OAGIS/9.0/Overlays/IBM/Commerce/BODs/GetContract.xsd"/>
			<xsd:include schemaLocation="../xsd/OAGIS/9.0/Overlays/IBM/Commerce/BODs/ShowContract.xsd"/>
		</xsd:schema>
				
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			targetNamespace="http://www.openapplications.org/oagis/9">
			<xsd:include schemaLocation="../xsd/OAGIS/9.0/BODs/Developer/ConfirmBOD.xsd"/>
		</xsd:schema>
		
	</wsdl:types>

	<wsdl:message name="GetContract">
		<wsdl:part name="GetContract" element="_ctr:GetContract" />
	</wsdl:message>
	<wsdl:message name="ShowContract">
		<wsdl:part name="ShowContract" element="_ctr:ShowContract" />
	</wsdl:message>
	<wsdl:message name="ConfirmBOD">
		<wsdl:part name="ConfirmBOD" element="oa:ConfirmBOD" />
	</wsdl:message>

	<wsdl:portType name="ContractServicesPortType">

		<wsdl:operation name="GetContract">
			<wsdl:input message="_ctr:GetContract" name="GetContract" />
			<wsdl:output message="_ctr:ShowContract" name="ShowContract" />
		</wsdl:operation>

	</wsdl:portType>

	<wsdl:binding name="ContractServices"
		type="_ctr:ContractServicesPortType">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		
		<wsdl:operation name="GetContract">
			<soap:operation
				soapAction="http://localhost/services/ContractServices.wsdl" />
			<wsdl:input name="GetContract">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="ShowContract">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		
	</wsdl:binding>

	<wsdl:service name="ContractServices">
		<wsdl:port binding="_ctr:ContractServices" name="ContractServices">
			<soap:address
				location="http://localhost/webapp/wcs/component/contract/services/ContractServices" />
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>

