BEGIN_SYMBOL_DEFINITIONS
	
	<!-- The table for noun GiftList  -->
		<!-- Defining all columns of the table -->
		COLS:GREVNTTYPE  = GREVNTTYPE:* 	
		<!-- Defining the unique ID column of the table -->
		COLS:EVENTTYPE_ID = GREVNTTYPE:EVENTTYPE_ID 
		<!-- Defining the unique ID column of the table -->
		COLS:RULES = GRREGRULE:* 
END_SYMBOL_DEFINITIONS

BEGIN_SQL_STATEMENT
	name=IBM_GiftCenter_Enablement_Check
	base_table=SITE
	sql= SELECT * FROM SITE
END_SQL_STATEMENT

BEGIN_SQL_STATEMENT
  base_table=GREVNTTYPE
  name=IBM_Select_EventType_EventId
  sql=select GREVNTTYPE.$COLS:EVENTTYPE_ID$ 
  from 
	GREVNTTYPE 
  where 
	GREVNTTYPE.EVENTTYPENAME = ?eventTypeName?  AND 
	GREVNTTYPE.STOREID  = ?storeId? AND
	GREVNTTYPE.STATUS  = 1 
END_SQL_STATEMENT

BEGIN_SQL_STATEMENT
  base_table=GRREGRULE
  name=IBM_Select_Giftlist_Rules
  sql=
		SELECT 
			GRREGRULE.STOREID, GRREGRULE.NAME, GRREGRULE.EVENTTYPENAME, GRREGRULE.GRRULEVAL 
		FROM	
			GRREGRULE 
END_SQL_STATEMENT

BEGIN_SQL_STATEMENT
  base_table=GRGFTREG
  name=IBM_Select_Active_GiftList_For_Registrants
  sql=
		SELECT 
			COUNT(*) as countrows
		FROM 
			GRGFTREG , 
			GRRGSTRNT 
		WHERE 
			GRGFTREG.GIFTREGISTRY_ID = GRRGSTRNT.GIFTREGISTRY_ID AND
			GRGFTREG.STATUS IN (1, 5) AND GRGFTREG.REGTYPE = ?regType? AND	
			GRRGSTRNT.RGSTRNTTYPE = 0 AND	
			GRRGSTRNT.USERID = ?userId?
END_SQL_STATEMENT

BEGIN_SQL_STATEMENT
  base_table=GRGFTREG
  name=IBM_Select_GiftList_EventDate
  sql=
		SELECT 
			GRGFTREG.EVENTDATE
		FROM 
			GRGFTREG
		WHERE 
			GRGFTREG.GIFTREGISTRY_ID = ?giftListId?
END_SQL_STATEMENT

BEGIN_SQL_STATEMENT
  base_table=GRANNTMPLT
  name=IBM_Select_Template_Path
  sql=
		SELECT 
			GRANNTMPLT.PATH  
		FROM 
			GRANNTMPLT
		WHERE 
			GRANNTMPLT.TEMPLATENAME = ?templateName? AND 
			GRANNTMPLT.EVENTTYPE_ID = ?eventTypeId? 
END_SQL_STATEMENT

BEGIN_SQL_STATEMENT
  base_table=ORDERITEMGIFT
  name=IBM_Select_GiftList_OrderItemGifts
  sql=
	SELECT 
		ORDERITEMS_ID,
		GIFTMESSAGE,
		SHIPTORGSTRNT
	FROM 
		ORDERITEMGIFT  
	WHERE 
		ORDERITEMS_ID = ?orderItemsId? AND
		EXTERNAL_ID IN (SELECT GRGFTREG.EXTERNALID from GRGFTREG where GRGFTREG.GIFTREGISTRY_ID=?giftListId?)
END_SQL_STATEMENT

BEGIN_SQL_STATEMENT
	base_table=GREVNTTYPE
	name=IBM_Select_GiftList_EventName
	sql=
		SELECT 
			GREVNTTYPE.EVENTTYPENAME  
		FROM 
			GREVNTTYPE 
  		WHERE 
			GREVNTTYPE.EVENTTYPE_ID = ?eventId?
END_SQL_STATEMENT

BEGIN_SQL_STATEMENT
	base_table=GRPURREC
	name=IBM_Select_GiftList_PurchasedQuantity
	sql=
		SELECT 	GRPURREC.PURCHASEQUANTITY 
		FROM 	GRPURREC 
		WHERE	GRPURREC.GIFTREGISTRY_ID = ?giftListId? AND GRPURREC.GIFTITEM_ID = ?giftItemId?
END_SQL_STATEMENT

BEGIN_SQL_STATEMENT
	base_table=GRPURREC
	name=IBM_Select_GiftList_PurchaseRecord
	sql=
		SELECT 	COUNT(*) as COUNTROWS
		FROM 	GRPURREC 
		WHERE	GRPURREC.GIFTREGISTRY_ID = ?giftListId? AND GRPURREC.GIFTITEM_ID = ?giftItemId?
END_SQL_STATEMENT

BEGIN_SQL_STATEMENT
	base_table=GRGFTITM
	name=IBM_Select_GiftList_ItemCount
	sql=
		SELECT 	COUNT(*) as COUNTROWS
		FROM 	GRGFTITM 
		WHERE	GRGFTITM.GIFTREGISTRY_ID = ?giftListId?
END_SQL_STATEMENT

BEGIN_SQL_STATEMENT
	base_table=GRGFTITM
	name=IBM_Select_GiftList_ItemQty
	sql=
		SELECT 	GRGFTITM.QUANTITYREQUESTED 
		FROM 	GRGFTITM 
		WHERE	GRGFTITM.GIFTITEM_ID = ?giftItemId?
END_SQL_STATEMENT