<!-- ====================================================================== 
	Get all the catalog fitlers(s) for the store.   
=========================================================================== -->
BEGIN_SYMBOL_DEFINITIONS
	<!-- CATFILTER table -->
	COLS:CATFILTER=CATFILTER:*
	COLS:CATFILTER_BASE_ATTRS=CATFILTER:CATFILTER_ID,IDENTIFIER,STOREENT_ID,CATALOG_ID,USAGE
      COLS:CATFILTER_ID=CATFILTER:CATFILTER_ID
	<!-- CATFLTDSC table -->
	COLS:CATFLTDSC=CATFLTDSC:*
	<!-- CFPRODUCTSET table -->
	COLS:CFPRODUCTSET=CFPRODUCTSET:*
	<!-- CFCATGROUP table -->
	COLS:CFCATGROUP=CFCATGROUP:*
	<!-- CFCONDGRP table -->
	COLS:CFCONDGRP=CFCONDGRP:*
	<!-- CFCOND table -->
	COLS:CFCOND=CFCOND:*
	<!-- CFCONDVAL table -->
	COLS:CFCONDVAL=CFCONDVAL:*
	<!-- ATTR table -->
	COLS:ATTR=ATTR:*
	<!-- ATTRVAL table -->
	COLS:ATTRVAL=ATTRVAL:*
	<!-- ATTRVALDESC table -->
	COLS:ATTRVALDESC=ATTRVALDESC:*
	COLS:PRODUCTSET=PRODUCTSET:*
	COLS:PRSETCEREL=PRSETCEREL:*
END_SYMBOL_DEFINITIONS

BEGIN_ASSOCIATION_SQL_STATEMENT
	name=IBM_CatalogFilter
	base_table=CATFILTER
	additional_entity_objects=false
	sql=
		SELECT 
				CATFILTER.$COLS:CATFILTER_BASE_ATTRS$
		FROM
				CATFILTER
    WHERE
        CATFILTER.CATFILTER_ID IN ($ENTITY_PKS$) 
        	
END_ASSOCIATION_SQL_STATEMENT

BEGIN_ASSOCIATION_SQL_STATEMENT
	name=IBM_CatalogFilterDescription
	base_table=CATFILTER
	sql=
		SELECT 
			CATFILTER.$COLS:CATFILTER_ID$,
			CATFLTDSC.$COLS:CATFLTDSC$ 
		FROM
			CATFILTER,	CATFLTDSC
    WHERE
        CATFILTER.CATFILTER_ID IN ($ENTITY_PKS$) and CATFLTDSC.CATFILTER_ID = CATFILTER.CATFILTER_ID AND CATFLTDSC.LANGUAGE_ID = $CTX:LANG_ID$
END_ASSOCIATION_SQL_STATEMENT

BEGIN_ASSOCIATION_SQL_STATEMENT
	name=IBM_CatalogFilterProductSet
	base_table=CATFILTER
	sql=
		SELECT 
			CATFILTER.$COLS:CATFILTER_ID$,
			CFPRODUCTSET.$COLS:CFPRODUCTSET$,
			PRODUCTSET.$COLS:PRODUCTSET$,
			PRSETCEREL.$COLS:PRSETCEREL$
		FROM
			CATFILTER,		CFPRODUCTSET,  PRODUCTSET
			LEFT OUTER JOIN PRSETCEREL  ON (PRSETCEREL.PRODUCTSET_ID = PRODUCTSET.PRODUCTSET_ID)

    WHERE
        CFPRODUCTSET.CATFILTER_ID IN ($ENTITY_PKS$) and (CFPRODUCTSET.TYPE = 0 or CFPRODUCTSET.TYPE = 1) and CFPRODUCTSET.CATFILTER_ID = CATFILTER.CATFILTER_ID AND CFPRODUCTSET.PRODUCTSET_ID = PRODUCTSET.PRODUCTSET_ID
END_ASSOCIATION_SQL_STATEMENT

BEGIN_ASSOCIATION_SQL_STATEMENT
	name=IBM_CatalogFilterProductSetWithoutCatentries
	base_table=CATFILTER
	sql=
		SELECT 
			CATFILTER.$COLS:CATFILTER_ID$,
			CFPRODUCTSET.$COLS:CFPRODUCTSET$,
			PRODUCTSET.$COLS:PRODUCTSET$
		FROM
			CATFILTER,		CFPRODUCTSET,  PRODUCTSET
    WHERE
        CFPRODUCTSET.CATFILTER_ID IN ($ENTITY_PKS$)   and CFPRODUCTSET.CATFILTER_ID = CATFILTER.CATFILTER_ID AND CFPRODUCTSET.PRODUCTSET_ID = PRODUCTSET.PRODUCTSET_ID
END_ASSOCIATION_SQL_STATEMENT

BEGIN_ASSOCIATION_SQL_STATEMENT
	name=IBM_CatalogFilterCatGroupAndConditions
	base_table=CATFILTER
	sql=
		SELECT 
                  CATFILTER.$COLS:CATFILTER_ID$,
                  CFCATGROUP.$COLS:CFCATGROUP$,
                  CFCONDGRP.$COLS:CFCONDGRP$,
                  CFCOND.$COLS:CFCOND$,
                  CFCONDVAL.$COLS:CFCONDVAL$,
                  ATTR.$COLS:ATTR$,
                  ATTRVAL.$COLS:ATTRVAL$,
                  ATTRVALDESC.$COLS:ATTRVALDESC$
		FROM
			CATFILTER,	CFCATGROUP
                  LEFT OUTER JOIN CFCONDGRP ON CFCONDGRP.CFCATGROUP_ID = CFCATGROUP.CFCATGROUP_ID
                  LEFT OUTER JOIN CFCOND ON CFCOND.CFCONDGRP_ID = CFCONDGRP.CFCONDGRP_ID
                  LEFT OUTER JOIN CFCONDVAL ON CFCONDVAL.CFCOND_ID = CFCOND.CFCOND_ID
                  LEFT OUTER JOIN ATTR ON ATTR.ATTR_ID = CFCOND.ATTR_ID
                  LEFT OUTER JOIN ATTRVAL ON CFCONDVAL.ATTRVAL_ID = ATTRVAL.ATTRVAL_ID
                  LEFT OUTER JOIN ATTRVALDESC ON ( ATTRVALDESC.ATTRVAL_ID = ATTRVAL.ATTRVAL_ID AND ATTRVALDESC.LANGUAGE_ID = $CTX:LANG_ID$ )
    WHERE
        CFCATGROUP.CATFILTER_ID IN ($ENTITY_PKS$)   and CFCATGROUP.CATFILTER_ID = CATFILTER.CATFILTER_ID  
END_ASSOCIATION_SQL_STATEMENT

BEGIN_PROFILE 
	name=IBM_CatalogFilter_details
	BEGIN_ENTITY 
	  base_table=CATFILTER 
	  associated_sql_statement=IBM_CatalogFilter
	  associated_sql_statement=IBM_CatalogFilterDescription
	  associated_sql_statement=IBM_CatalogFilterProductSet
	  associated_sql_statement=IBM_CatalogFilterCatGroupAndConditions
  END_ENTITY
END_PROFILE

BEGIN_PROFILE 
	name=IBM_CatalogFilter_Details_WithoutCatentries
	BEGIN_ENTITY 
	  base_table=CATFILTER 
	  associated_sql_statement=IBM_CatalogFilter
	  associated_sql_statement=IBM_CatalogFilterDescription
	  associated_sql_statement=IBM_CatalogFilterProductSetWithoutCatentries
	  associated_sql_statement=IBM_CatalogFilterCatGroupAndConditions
  END_ENTITY
END_PROFILE

