<!-- ====================================================================== 
	Get all the catalog fitlers(s) for the store.   
=========================================================================== -->

BEGIN_SYMBOL_DEFINITIONS
	<!-- CATFILTER table -->
	COLS:CATFILTER=CATFILTER:*
	COLS:CATFILTER_ID=CATFILTER:CATFILTER_ID
	COLS:IDENTIFIER=CATFILTER:IDENTIFIER
	COLS:STOREENT_ID=CATFILTER:STOREENT_ID
	COLS:CATALOG_ID=CATFILTER:CATALOG_ID
	COLS:USAGE=CATFILTER:USAGE
	COLS:CATFILTER_BASE_ATTRS=CATFILTER:CATFILTER_ID,IDENTIFIER,STOREENT_ID,CATALOG_ID,USAGE
	<!-- CATFLTDSC table -->
	COLS:CATFLTDSC=CATFLTDSC:*
	COLS:CATFLTDSC_CATFILTER_ID=CATFLTDSC:CATFILTER_ID
	COLS:DESCRIPTION=CATFLTDSC:DESCRIPTION
END_SYMBOL_DEFINITIONS

BEGIN_XPATH_TO_SQL_STATEMENT
	name=/CatalogFilter
	base_table=CATFILTER
	sql=
		SELECT 
				CATFILTER.$COLS:CATFILTER_ID$
		FROM
				CATFILTER
    WHERE
        CATFILTER.STOREENT_ID IN ($STOREPATH:catalogfilter$)
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
	name=/CatalogFilter[CatalogFilterIdentifier[(UniqueID=)]]
	base_table=CATFILTER
	sql=
		SELECT 
				CATFILTER.$COLS:CATFILTER_ID$,
				CATFILTER.$COLS:IDENTIFIER$,
				CATFILTER.$COLS:STOREENT_ID$,
				CATFILTER.$COLS:CATALOG_ID$
		FROM
				CATFILTER
    WHERE
        CATFILTER.CATFILTER_ID IN (?UniqueID?)
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
	name=/CatalogFilter[search()]
	base_table=CATFILTER
	sql=
		SELECT 
				CATFILTER.$COLS:CATFILTER_ID$
		FROM
				CATFILTER, $ATTR_TBLS$
    WHERE
        CATFILTER.STOREENT_ID IN ($STOREPATH:catalogfilter$) AND $ATTR_CNDS$
END_XPATH_TO_SQL_STATEMENT

BEGIN_ASSOCIATION_SQL_STATEMENT
	name=IBM_Admin_CatalogFilterSummary
	base_table=CATFILTER
	additional_entity_objects=true
	sql=
		SELECT 
				CATFILTER.$COLS:CATFILTER_ID$,
				CATFILTER.$COLS:IDENTIFIER$,
				CATFILTER.$COLS:STOREENT_ID$,
				CATFILTER.$COLS:CATALOG_ID$,
				CATFLTDSC.$COLS:CATFLTDSC_CATFILTER_ID$,
				CATFLTDSC.$COLS:DESCRIPTION$
		FROM
				CATFILTER
						LEFT OUTER JOIN CATFLTDSC ON CATFILTER.CATFILTER_ID=CATFLTDSC.CATFILTER_ID AND CATFLTDSC.LANGUAGE_ID = $CTX:LANG_ID$
		WHERE
        CATFILTER.CATFILTER_ID IN ($ENTITY_PKS$)
END_ASSOCIATION_SQL_STATEMENT


BEGIN_PROFILE 
	name=IBM_Admin_Summary
	BEGIN_ENTITY 
	  base_table=CATFILTER 
      associated_sql_statement=IBM_Admin_CatalogFilterSummary
  END_ENTITY
END_PROFILE
