/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/licensePortions Copyright IBM Corp., 2009-2015.
*/
CKEDITOR.plugins.setLang("specialchar","es",{euro:"Símbolo del euro",lsquo:"Comilla simple de apertura",rsquo:"Comilla simple de cierre",ldquo:"Comillas dobles de apertura",rdquo:"Comillas dobles de cierre",ndash:"Guión corto",mdash:"Guión largo",iexcl:"Signo de exclamación de apertura",cent:"Símbolo del céntimo",pound:"Símbolo de la Libra",curren:"Símbolo de moneda",yen:"Símbolo del Yen",brvbar:"Barra quebrada",sect:"Símbolo de sección",uml:"Diéresis",copy:"Símbolo de copyright",ordf:"Indicador de ordinal femenino",
laquo:"Comillas angulares dobles de apertura",not:"Símbolo No",reg:"Símbolo Registrado",macr:"Raya horizontal superior",deg:"Símbolo Grados",sup2:"Superíndice 2",sup3:"Superíndice 3",acute:"Acento agudo",micro:"Símbolo Micro",para:"Símbolo de marca de párrafo",middot:"Punto medio",cedil:"Cedilla",sup1:"Superíndice uno",ordm:"Indicador ordinal masculino",raquo:"Comillas angulares dobles de cierre",frac14:"Fracción Un cuarto",frac12:"Fracción Mitad",frac34:"Fracción Tres cuartos",iquest:"Interrogación de apertura",
Agrave:"Letra A mayúscula con acento grave",Aacute:"Letra A mayúscula con acento agudo",Acirc:"Letra A mayúscula con circumflejo",Atilde:"Letra A mayúscula con virgulilla",Auml:"Letra A mayúscula con diéresis",Aring:"Letra A mayúscula con círculo arriba",AElig:"Letra Æ mayúscula ",Ccedil:"Letra C mayúscula con cedilla",Egrave:"Letra E mayúscula con acento grave",Eacute:"Letra E mayúscula con acento agudo",Ecirc:"Letra E mayúscula con circumflejo",Euml:"Letra E mayúscula con diéresis",Igrave:"Letra I mayúscula con acento grave",
Iacute:"Letra I mayúscula con acento agudo",Icirc:"Letra I mayúscula con circumflejo",Iuml:"Letra I mayúscula con diéresis",ETH:"Letra Eth mayúscula ",Ntilde:"Letra N mayúscula con virgulilla",Ograve:"Letra O mayúscula con acento grave",Oacute:"Letra O mayúscula con acento agudo",Ocirc:"Letra O mayúscula con circumflejo",Otilde:"Letra O mayúscula con virgulilla",Ouml:"Letra O mayúscula con diéresis",times:"Signo de multiplicación",Oslash:"Letra O mayúscula cruzada con barra inclinada",Ugrave:"Letra U mayúscula con acento grave",
Uacute:"Letra U mayúscula con acento agudo",Ucirc:"Letra U mayúscula con circumflejo",Uuml:"Letra U mayúscula con diéresis",Yacute:"Letra Y mayúscula con acento agudo",THORN:"Letra Thorn mayúscula ",szlig:"Letra minúscula Beta (s doble)",agrave:"Letra a minúscula con acento grave",aacute:"Letra a minúscula con acento agudo",acirc:"Letra a minúscula con circumflejo",atilde:"Letra a minúscula con tilde",auml:"Letra a minúscula con diéresis",aring:"Letra a minúscula con círculo encima",aelig:"Letra æ minúscula",
ccedil:"Letra c minúscula con cedilla",egrave:"Letra e minúscula con acento grave",eacute:"Letra e minúscula con acento agudo",ecirc:"Letra e minúscula con circumflejo",euml:"Letra e minúscula con diéresis",igrave:"Letra i minúscula con acento grave",iacute:"Letra i minúscula con acento agudo",icirc:"Letra i minúscula con circumflejo",iuml:"Letra i minúscula con diéresis",eth:"Letra eth minúscula",ntilde:"Letra n minúscula con tilde",ograve:"Letra o minúscula con acento grave",oacute:"Letra o minúscula con acento agudo",
ocirc:"Letra o minúscula con circumflejo",otilde:"Letra o minúscula con tilde",ouml:"Letra o minúscula con diéresis",divide:"Signo de división",oslash:"Letra o minúscula cruzada con barra inclinada",ugrave:"Letra u minúscula con acento grave",uacute:"Letra u minúscula con acento agudo",ucirc:"Letra u minúscula con circumflejo",uuml:"Letra u minúscula con diéresis",yacute:"Letra y minúscula con acento agudo",thorn:"Letra thorn minúscula",yuml:"Letra y minúscula con diéresis",OElig:"Letra OE mayúscula",
oelig:"Letra oe minúscula",372:"Letra W mayúscula con circumflejo",374:"Letra Y mayúscula con circumflejo",373:"Letra w minúscula con circumflejo",375:"Letra y minúscula con circumflejo",sbquo:"Comilla sencilla baja-9",8219:"Comilla sencilla alta-9 invertida",bdquo:"Comilla doble baja-9",hellip:"Puntos suspensivos horizontales",trade:"Símbolo de marca comercial",9658:"Puntero negro a derecha",bull:"Viñeta",rarr:"Flecha a derecha",rArr:"Flecha doble a derecha",hArr:"Flecha doble izquierda derecha",
diams:"Diamante negro",asymp:"Aproximación"});