/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/licensePortions Copyright IBM Corp., 2009-2015.
*/
CKEDITOR.plugins.setLang("specialchar","fi",{euro:"Euron merkki",lsquo:"Vasen puolilainausmerkki",rsquo:"Oikea puolilainausmerkki",ldquo:"Vasen kokolainausmerkki",rdquo:"Oikea kokolainausmerkki",ndash:"N-viiva",mdash:"M-viiva",iexcl:"Ylösalaisin oleva huutomerkki",cent:"Sentin merkki",pound:"Punnan merkki",curren:"Valuuttamerkki",yen:"Jenin merkki",brvbar:"Katkopystyviiva",sect:"Osan merkki",uml:"Treema",copy:"Copyright-merkki",ordf:"Järjestysluvun feminiinin ilmaisin",laquo:"Vasemmalle osoittava kaksinkertainen kulmalainausmerkki",
not:"Ei-merkki",reg:"Rekisteröity-merkki",macr:"Pituusmerkki",deg:"Astemerkki",sup2:"Numero 2 yläindeksissä",sup3:"Numero 3 yläindeksissä",acute:"Akuutti aksentti",micro:"Mikro-merkki",para:"Kappalemerkki",middot:"Rivinkeskinen piste",cedil:"Sedilji",sup1:"Numero 1 yläindeksissä",ordm:"Järjestysluvun maskuliinin ilmaisin",raquo:"Oikealle osoittava kaksinkertainen kulmalainausmerkki",frac14:"Murtoluku (neljäsosa)",frac12:"Murtoluku (puolikas)",frac34:"Murtoluku (kolme neljäsosaa)",iquest:"Ylösalaisin oleva kysymysmerkki",
Agrave:"iso A ja gravis",Aacute:"iso A ja akuutti",Acirc:"iso A ja sirkumfleksi\nversaali A ja sirkumfleksi",Atilde:"iso A ja tilde\nversaali A ja tilde\niso A ja aaltoviiva\nversaali A ja aaltoviiva",Auml:"iso Ä\nversaali Ä",Aring:"iso A, jonka yläpuolella on rengas",AElig:"iso Æ",Ccedil:"iso C ja sedilji\nversaali C ja sedilji",Egrave:"iso E ja gravis",Eacute:"iso E ja akuutti",Ecirc:"iso E ja sirkumfleksi\nversaali E ja sirkumfleksi",Euml:"iso E ja treema\nversaali E ja treema",Igrave:"iso I ja gravis",
Iacute:"iso I ja akuutti",Icirc:"iso I ja sirkumfleksi\nversaali I ja sirkumfleksi",Iuml:"iso I ja treema\nversaali I ja treema",ETH:"iso Eth",Ntilde:"iso N ja tilde\nversaali N ja tilde\niso N ja aaltoviiva\nversaali N ja aaltoviiva",Ograve:"iso O ja gravis",Oacute:"iso O ja akuutti",Ocirc:"iso O ja sirkumfleksi\nversaali O ja sirkumfleksi",Otilde:"iso O ja tilde\nversaali O ja tilde\niso O ja aaltoviiva\nversaali O ja aaltoviiva",Ouml:"iso O ja treema\nversaali O ja treema",times:"Kertomerkki",
Oslash:"iso O, jonka läpi kulkee viiva (tanskalainen Ö)",Ugrave:"iso U ja gravis",Uacute:"iso U ja akuutti",Ucirc:"iso U ja sirkumfleksi\nversaali U ja sirkumfleksi",Uuml:"iso U ja treema\nversaali U ja treema\niso saksalainen y\nversaali saksalainen y",Yacute:"iso Y ja akuutti",THORN:"pieni thorn",szlig:"pieni terävä s",agrave:"pieni a ja gravis",aacute:"pieni a ja akuutti",acirc:"pieni a ja sirkumfleksi\ngemena a ja sirkumfleksi",atilde:"pieni a ja tilde\ngemena a ja tilde\npieni a ja aaltoviiva\ngemena a ja aaltoviiva",
auml:"pieni ä\ngemena ä",aring:"pieni a, jonka yläpuolella on rengas",aelig:"pieni æ",ccedil:"pieni c ja sedilji\ngemena c ja sedilji",egrave:"pieni e ja gravis",eacute:"pieni e ja akuutti",ecirc:"pieni e ja sirkumfleksi\ngemena e ja sirkumfleksi",euml:"pieni e ja treema\ngemena e ja treema",igrave:"pieni i ja gravis",iacute:"pieni i ja akuutti",icirc:"pieni i ja sirkumfleksi\ngemena i ja sirkumfleksi",iuml:"pieni i ja treema\ngemena i ja treema",eth:"pieni eth\ngemena eth",ntilde:"pieni n ja tilde\ngemena n ja tilde\npieni n ja aaltoviiva\ngemena n ja aaltoviiva",
ograve:"pieni o ja gravis",oacute:"pieni o ja akuutti",ocirc:"pieni o ja sirkumfleksi\ngemena o ja sirkumfleksi",otilde:"pieni o ja tilde\ngemena o ja tilde\npieni o ja aaltoviiva\ngemena o ja aaltoviiva",ouml:"pieni ö\ngemena ö",divide:"Jakomerkki",oslash:"pieni o, jonka läpi kulkee viiva (tanskalainen ö)",ugrave:"pieni u ja gravis",uacute:"pieni u ja akuutti",ucirc:"pieni u ja sirkumfleksi\ngemena u ja sirkumfleksi",uuml:"pieni u ja treema\ngemena u ja treema\npieni saksalainen y\ngemena saksalainen y",
yacute:"pieni y ja akuutti",thorn:"pieni thorn\ngemena thorn",yuml:"pieni y ja treema\ngemena y ja treema",OElig:"iso ligatuuri OE\nversaaliligatuuri OE",oelig:"pieni ligatuuri oe\ngemenaligatuuri oe",372:"iso W ja sirkumfleksi",374:"iso Y ja sirkumfleksi",373:"pieni w ja sirkumfleksi",375:"pieni y ja sirkumfleksi",sbquo:"Alapuolinen lainausmerkki",8219:"Yläpuolinen ylösalainen lainausmerkki",bdquo:"Alapuolinen kaksinkertainen lainausmerkki",hellip:"Vaakasuuntainen ellipsi",trade:"Tavaramerkin merkki",
9658:"Musta oikealle osoittava osoitin",bull:"Luettelomerkki",rarr:"Oikealle osoittava nuoli",rArr:"Oikealle osoittava kaksinkertainen nuoli",hArr:"Vasemmalle ja oikealle osoittava kaksinkertainen nuoli",diams:"Musta korttipakan ruutu",asymp:"Pyöristysmerkki"});