/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/licensePortions Copyright IBM Corp., 2009-2015.
*/
CKEDITOR.plugins.setLang("specialchar","ko",{euro:"유로 부호",lsquo:"왼쪽 작은따옴표",rsquo:"오른쪽 작은따옴표",ldquo:"왼쪽 큰따옴표",rdquo:"오른쪽 큰따옴표",ndash:"En 대시",mdash:"Em 대시",iexcl:"역느낌표",cent:"센트 부호",pound:"파운드 부호",curren:"통화 부호",yen:"엔 부호",brvbar:"분할된 세로 막대 부호",sect:"섹션 부호",uml:"분음 기호",copy:"저작권 부호",ordf:"여성 표식",laquo:"왼쪽 방향 큰따옴표",not:"부정 부호",reg:"등록 상표 부호",macr:"장음 부호",deg:"온도 부호",sup2:"윗첨자 2",sup3:"윗첨자 3",acute:"양음 부호",micro:"마이크로 부호",para:"단락 부호",middot:"중간 점",cedil:"세딜라",sup1:"윗첨자 1",ordm:"남성 표식",raquo:"오른쪽 방향 큰따옴표",
frac14:"1/4",frac12:"1/2",frac34:"3/4",iquest:"역물음표",Agrave:"역음 부호가 있는 라틴 대문자 A",Aacute:"양음 부호가 있는 라틴 대문자 A",Acirc:"서컴플렉스가 있는 라틴 대문자 A",Atilde:"물결 기호가 있는 라틴 대문자 A",Auml:"분음 기호가 있는 라틴 대문자 A",Aring:"위에 고리 모양이 있는 라틴 대문자 A",AElig:"라틴 대문자 Æ",Ccedil:"Latin capital letter C with cedilla",Egrave:"Latin capital letter E with grave accent",Eacute:"Latin capital letter E with acute accent",Ecirc:"Latin capital letter E with circumflex",Euml:"Latin capital letter E with diaeresis",Igrave:"Latin capital letter I with grave accent",
Iacute:"Latin capital letter I with acute accent",Icirc:"Latin capital letter I with circumflex",Iuml:"Latin capital letter I with diaeresis",ETH:"Latin capital letter Eth",Ntilde:"Latin capital letter N with tilde",Ograve:"Latin capital letter O with grave accent",Oacute:"Latin capital letter O with acute accent",Ocirc:"Latin capital letter O with circumflex",Otilde:"Latin capital letter O with tilde",Ouml:"Latin capital letter O with diaeresis",times:"Multiplication sign",Oslash:"Latin capital letter O with stroke",
Ugrave:"Latin capital letter U with grave accent",Uacute:"Latin capital letter U with acute accent",Ucirc:"Latin capital letter U with circumflex",Uuml:"Latin capital letter U with diaeresis",Yacute:"Latin capital letter Y with acute accent",THORN:"Latin capital letter Thorn",szlig:"Latin small letter sharp s",agrave:"Latin small letter a with grave accent",aacute:"Latin small letter a with acute accent",acirc:"Latin small letter a with circumflex",atilde:"Latin small letter a with tilde",auml:"Latin small letter a with diaeresis",
aring:"Latin small letter a with ring above",aelig:"Latin small letter æ",ccedil:"세딜라가 있는 라틴 소문자 c",egrave:"역음 부호가 있는 라틴 소문자 e",eacute:"양음 부호가 있는 라틴 소문자 e",ecirc:"서컴플렉스가 있는 라틴 소문자 e",euml:"분음 기호가 있는 라틴 소문자 e",igrave:"역음 부호가 있는 라틴 소문자 i",iacute:"양음 부호가 있는 라틴 소문자 i",icirc:"서컴플렉스가 있는 라틴 소문자 i",iuml:"분음 기호가 있는 라틴 소문자 i",eth:"라틴 소문자 eth",ntilde:"물결 기호가 있는 라틴 소문자 n",ograve:"역음 부호가 있는 라틴 소문자 o",oacute:"양음 부호가 있는 라틴 소문자 o",ocirc:"서컴플렉스가 있는 라틴 소문자 o",otilde:"물결 기호가 있는 라틴 소문자 o",ouml:"분음 기호가 있는 라틴 소문자 o",divide:"/ 기호",
oslash:"스트로크가 있는 라틴 소문자 o",ugrave:"역음 부호가 있는 라틴 소문자 u",uacute:"양음 부호가 있는 라틴 소문자 u",ucirc:"서컴플렉스가 있는 라틴 소문자 u",uuml:"분음 기호가 있는 라틴 소문자 u",yacute:"양음 부호가 있는 라틴 소문자 y",thorn:"라틴 소문자 thorn",yuml:"분음 기호가 있는 라틴 소문자 y",OElig:"라틴 대문자 이중 모음 OE",oelig:"라틴 소문자 이중 모음 oe",372:"서컴플렉스가 있는 라틴 대문자 W",374:"서컴플렉스가 있는 라틴 대문자 Y",373:"서컴플렉스가 있는 라틴 소문자 w",375:"서컴플렉스가 있는 라틴 소문자 y",sbquo:"low-9 작은따옴표",8219:"high-reversed-9 작은따옴표",bdquo:"low-9 큰따옴표",hellip:"가운데 가로 생략 부호",trade:"상표 부호",9658:"검은색 오른쪽 방향 포인터",bull:"글머리 기호",rarr:"오른쪽 방향 화살표",
rArr:"오른쪽 방향 이중 화살표",hArr:"왼쪽 오른쪽 이중 화살표",diams:"검은색 다이아몬드",asymp:"유사함"});