/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/licensePortions Copyright IBM Corp., 2009-2015.
*/
CKEDITOR.plugins.setLang("specialchar","nl",{euro:"Euroteken",lsquo:"Enkel aanhalingsteken links",rsquo:"Enkel aanhalingsteken rechts",ldquo:"Dubbel aanhalingsteken links",rdquo:"Dubbel aanhalingsteken rechts",ndash:"En-streepje",mdash:"Em-streepje",iexcl:"Omgekeerd uitroepteken",cent:"Dollarcent-teken",pound:"Pond-teken",curren:"Valutateken",yen:"Yen-teken",brvbar:"Onderbroken balk",sect:"Paragraafteken",uml:"Trema",copy:"Copyright-teken",ordf:"Superscript a",laquo:"Dubbel aanhalingsteken naar links",
not:"Is niet-teken",reg:"Registered-teken",macr:"Lengteteken",deg:"Graden-teken",sup2:"Superscript 2",sup3:"Superscript 3",acute:"Accent aigu",micro:"Micro-teken",para:"Alineateken",middot:"Midden-punt",cedil:"Cedille",sup1:"Superscript 1",ordm:"Superscript o",raquo:"Dubbel aanhalingsteken naar rechts",frac14:"Gewone breuk 1/4",frac12:"Gewone breuk 1/2",frac34:"Gewone breuk 3/4",iquest:"Omgekeerd vraagteken",Agrave:"Hoofdletter A met accent grave",Aacute:"Hoofdletter A met accent aigu",Acirc:"Hoofdletter A met accent circonflexe",
Atilde:"Hoofdletter A met tilde",Auml:"Hoofdletter A met trema",Aring:"Hoofdletter A met ring",AElig:"Hoofdletter AE-ligatuur",Ccedil:"Hoofdletter C met cedille",Egrave:"Hoofdletter E met accent grave",Eacute:"Hoofdletter E met accent aigu",Ecirc:"Hoofdletter E met accent circonflexe",Euml:"Hoofdletter E met trema",Igrave:"Hoofdletter I met accent grave",Iacute:"Hoofdletter I met accent aigu",Icirc:"Hoofdletter I met accent circonflexe",Iuml:"Hoofdletter I met trema",ETH:"Hoofdletter ETH-ligatuur",
Ntilde:"Hoofdletter N met tilde",Ograve:"Hoofdletter O met accent grave",Oacute:"Hoofdletter O met accent aigu",Ocirc:"Hoofdletter O met accent circonflexe",Otilde:"Hoofdletter O met tilde",Ouml:"Hoofdletter O met trema",times:"Vermenigvuldigingsteken",Oslash:"Hoofdletter O met streepje",Ugrave:"Hoofdletter U met accent grave",Uacute:"Hoofdletter U met accent aigu",Ucirc:"Hoofdletter U met accent circonflexe",Uuml:"Hoofdletter U met trema",Yacute:"Hoofdletter Y met accent aigu",THORN:"Hoofdletter Thorn",
szlig:"Ringel-S",agrave:"Kleine letter a met accent grave",aacute:"Kleine letter a met accent aigu",acirc:"Kleine letter a met accent circonflexe",atilde:"Kleine letter a met tilde",auml:"Kleine letter a met trema",aring:"Kleine letter a met ring",aelig:"Kleine letter ae-ligatuur",ccedil:"Kleine letter c met cedille",egrave:"Kleine letter e met accent grave",eacute:"Kleine letter e met accent aigu",ecirc:"Kleine letter e met accent circonflexe",euml:"Kleine letter e met trema",igrave:"Kleine letter i met accent grave",
iacute:"Kleine letter i met accent aigu",icirc:"Kleine letter i met accent circonflexe",iuml:"Kleine letter i met trema",eth:"Kleine letter eth",ntilde:"Kleine letter n met tilde",ograve:"Kleine letter o met accent grave",oacute:"Kleine letter o met accent aigu",ocirc:"Kleine letter o met accent circonflexe",otilde:"Kleine letter o met tilde",ouml:"Kleine letter o met trema",divide:"Deelteken",oslash:"Kleine letter o met streepje",ugrave:"Kleine letter u met accent grave",uacute:"Kleine letter u met accent aigu",
ucirc:"Kleine letter u met accent circonflexe",uuml:"Kleine letter u met trema",yacute:"Kleine letter y met accent aigu",thorn:"Kleine letter thorn",yuml:"Kleine letter y met trema",OElig:"Hoofdletter OE-ligatuur",oelig:"Kleine letter oe-ligatuur",372:"Hoofdletter W met accent circonflexe",374:"Hoofdletter Y met accent circonflexe",373:"Kleine letter w met accent circonflexe",375:"Kleine letter y met accent circonflexe",sbquo:"Enkel omgekeerd laag aanhalingsteken",8219:"Enkel omgekeerd hoog aanhalingsteken",
bdquo:"Dubbel omgekeerd laag aanhalingsteken",hellip:"Horizontaal weglatingsteken",trade:"Trade Mark-teken",9658:"Zwarte wijzer naar rechts",bull:"Opsommingsteken",rarr:"Pijl naar rechts",rArr:"Dubbele pijl naar rechts",hArr:"Dubbele pijl links/rechts",diams:"Zwarte ruiten",asymp:"Bijna gelijk aan"});