/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/licensePortions Copyright IBM Corp., 2009-2015.
*/
CKEDITOR.plugins.setLang("specialchar","pl",{euro:"Znak euro",lsquo:"Lewy apostrof",rsquo:"Prawy apostrof",ldquo:"Lewy cudzysłów",rdquo:"Prawy cudzysłów",ndash:"Półpauza",mdash:"Myślnik",iexcl:"Odwrócony wykrzyknik",cent:"Znak centa",pound:"Znak funta",curren:"Znak waluty",yen:"Znak jena",brvbar:"Przerwana pionowa kreska",sect:"Znak sekcji",uml:"Diereza",copy:"Znak praw autorskich",ordf:"Znak liczby rodzaju żeńskiego",laquo:"Lewy cudzysłów trójkątny",not:"Znak negacji",reg:"Znak zastrzeżonego znaku towarowego",
macr:"Makron",deg:"Znak stopnia",sup2:"Cyfra dwa w indeksie górnym",sup3:"Cyfra trzy w indeksie górnym",acute:"Akcent ostry",micro:"Znak mikro",para:"Znak pilcrow",middot:"Kropka środkowa",cedil:"Cedilla",sup1:"Cyfra jeden w indeksie górnym",ordm:"Znak liczby rodzaju męskiego",raquo:"Prawy cudzysłów trójkątny",frac14:"Znak ułamka jedna czwarta",frac12:"Znak ułamka jedna druga",frac34:"Znak ułamka trzy czwarte",iquest:"Odwrócony znak zapytania",Agrave:"Łacińska wielka litera A z akcentem ciężkim",
Aacute:"Łacińska wielka litera A z akcentem ostrym",Acirc:"Łacińska wielka litera A z daszkiem",Atilde:"Łacińska wielka litera A z tyldą",Auml:"Łacińska wielka litera A z dierezą",Aring:"Łacińska wielka litera A z pierścieniem powyżej",AElig:"Łacińska wielka litera Æ",Ccedil:"Łacińska wielka litera C z cedillą",Egrave:"Łacińska wielka litera E z akcentem ciężkim",Eacute:"Łacińska wielka litera E z akcentem ostrym",Ecirc:"Łacińska wielka litera E z daszkiem",Euml:"Łacińska wielka litera E z dierezą",
Igrave:"Łacińska wielka litera I z akcentem ciężkim",Iacute:"Łacińska wielka litera I z akcentem ostrym",Icirc:"Łacińska wielka litera I z daszkiem",Iuml:"Łacińska wielka litera I z dierezą",ETH:"Łacińska wielka litera Eth",Ntilde:"Łacińska wielka litera N z tyldą",Ograve:"Łacińska wielka litera O z akcentem ciężkim",Oacute:"Łacińska wielka litera O z akcentem ostrym",Ocirc:"Łacińska wielka litera O z daszkiem",Otilde:"Łacińska wielka litera O z tyldą",Ouml:"Łacińska wielka litera O z dierezą",times:"Znak mnożenia",
Oslash:"Łacińska wielka litera O z przekreśleniem",Ugrave:"Łacińska wielka litera U z akcentem ciężkim",Uacute:"Łacińska wielka litera U z akcentem ostrym",Ucirc:"Łacińska wielka litera U z daszkiem",Uuml:"Łacińska wielka litera U z dierezą",Yacute:"Łacińska wielka litera Y z akcentem ostrym",THORN:"Łacińska wielka litera Thorn",szlig:"Łacińska mała litera ostre s",agrave:"Łacińska mała litera a z akcentem ciężkim",aacute:"Łacińska mała litera a z akcentem ostrym",acirc:"Łacińska mała litera a z daszkiem",
atilde:"Łacińska mała litera a z tyldą",auml:"Łacińska mała litera a z dierezą",aring:"Łacińska mała litera a z pierścieniem powyżej",aelig:"Łacińska mała litera æ",ccedil:"Łacińska mała litera c z cedillą",egrave:"Łacińska mała litera e z akcentem ciężkim",eacute:"Łacińska mała litera e z akcentem ostrym",ecirc:"Łacińska mała litera e z daszkiem",euml:"Łacińska mała litera e z dierezą",igrave:"Łacińska mała litera i z akcentem ciężkim",iacute:"Łacińska mała litera i z akcentem ostrym",icirc:"Łacińska mała litera i z daszkiem",
iuml:"Łacińska mała litera i z dierezą",eth:"Łacińska mała litera eth",ntilde:"Łacińska mała litera n z tyldą",ograve:"Łacińska mała litera o z akcentem ciężkim",oacute:"Łacińska mała litera o z akcentem ostrym",ocirc:"Łacińska mała litera o z daszkiem",otilde:"Łacińska mała litera o z tyldą",ouml:"Łacińska mała litera o z dierezą",divide:"Znak dzielenia",oslash:"Łacińska mała litera o z przekreśleniem",ugrave:"Łacińska mała litera u z akcentem ciężkim",uacute:"Łacińska mała litera u z akcentem ostrym",
ucirc:"Łacińska mała litera u z daszkiem",uuml:"Łacińska mała litera u z dierezą",yacute:"Łacińska mała litera y z akcentem ostrym",thorn:"Łacińska mała litera thorn",yuml:"Łacińska mała litera y z dierezą",OElig:"Łacińska ligatura wielkich liter OE",oelig:"Łacińska ligatura małych liter oe",372:"Łacińska wielka litera W z daszkiem",374:"Łacińska wielka litera Y z daszkiem",373:"Łacińska mała litera w z daszkiem",375:"Łacińska mała litera y z daszkiem",sbquo:"Apostrof dolny",8219:"Apostrof górny",
bdquo:"Cudzysłów dolny",hellip:"Wielokropek",trade:"Symbol znaku towarowego",9658:"Czarny wskaźnik w prawo",bull:"Znacznik podpunktu",rarr:"Strzałka w prawo",rArr:"Podwójna strzałka w prawo",hArr:"Podwójna strzałka w lewo i w prawo",diams:"Czarny symbol karo",asymp:"Prawie równa się"});