/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/licensePortions Copyright IBM Corp., 2009-2015.
*/
CKEDITOR.plugins.setLang("specialchar","sl",{euro:"Znak za evro",lsquo:"Levi opuščaj",rsquo:"Desni opuščaj",ldquo:"Levi narekovaj",rdquo:"Desni narekovaj",ndash:"Pomišljaj",mdash:"Vezaj",iexcl:"Obrnjeni klicaj",cent:"Znak za cente",pound:"Znak za funte",curren:"Znak za valuto",yen:"Znak za jen",brvbar:"Prekinjena črtica",sect:"Znak za razdelek",uml:"Diereza",copy:"Znak za avtorske pravice",ordf:"Indikator ženskega spola",laquo:"Dvojni levi narekovaj",not:"Znak Not",reg:"Registriran znak",macr:"Makron",
deg:"Znak za stopinje",sup2:"Nadpisano dve",sup3:"Nadpisano tri",acute:"Ostrivec",micro:"Mikro znak",para:"Znak za odstavek",middot:"Sredinska pika",cedil:"Cedila",sup1:"Nadpisano ena",ordm:"Indikator moškega spola",raquo:"Desni dvojni oglati narekovaj",frac14:"Navaden ulomek ena četrtina",frac12:"Navaden ulomek ena polovica",frac34:"Navaden ulomek tri četrtine",iquest:"Obrnjeni vprašaj",Agrave:"Latinska velika črka A s krativcem",Aacute:"Latinska velika črka A z ostrivcem",Acirc:"Latinska velika črka A s strešico",
Atilde:"Latinska velika črka A s tildo",Auml:"Latinska velika črka A z dierezo",Aring:"Latinska velika črka A s krogcem zgoraj",AElig:"Latinska velika črka Æ",Ccedil:"Latinska velika črka C s cedilo",Egrave:"Latinska velika črka E s krativcem",Eacute:"Latinska velika črka E z ostrivcem",Ecirc:"Latinska velika črka E s strešico",Euml:"Latinska velika črka E z dierezo",Igrave:"Latinska velika črka I s krativcem",Iacute:"Latinska velika črka I z ostrivcem",Icirc:"Latinska velika črka I s strešico",Iuml:"Latinska velika črka I z dierezo",
ETH:"Latinska velika črka Eth",Ntilde:"Latinska velika črka N s tildo",Ograve:"Latinska velika črka O s krativcem",Oacute:"Latinska velika črka O z ostrivcem",Ocirc:"Latinska velika črka O s strešico",Otilde:"Latinska velika črka O s tildo",Ouml:"Latinska velika črka O z dierezo",times:"Znak za množenje",Oslash:"Latinska velika črka O črtico",Ugrave:"Latinska velika črka U s krativcem",Uacute:"Latinska velika črka U z ostrivcem",Ucirc:"Latinska velika črka U s strešico",Uuml:"Latinska velika črka U z dierezo",
Yacute:"Latinska velika črka Y z ostrivcem",THORN:"Latinska velika črka Thorn",szlig:"Latinska mala črka ostri s",agrave:"Latinska mala črka s krativcem",aacute:"Latinska mala črka z ostrivcem",acirc:"Latinska mala črka s strešico",atilde:"Latinska mala črka s tildo",auml:"Latinska mala črka z dierezo",aring:"Latinska mala črka s krogcem zgoraj",aelig:"Latinska mala črka s",ccedil:"Latinska mala črka s cedilo",egrave:"Latinska mala črka e s krativcem",eacute:"Latinska mala črka e z ostrivcem",ecirc:"Latinska mala črka e s strešico",
euml:"Latinska mala črka e z dierezo",igrave:"Latinska mala črka i s krativcem",iacute:"Latinska mala črka i z ostrivcem",icirc:"Latinska mala črka i s strešico",iuml:"Latinska mala črka i z dierezo",eth:"Latinska mala črka eth",ntilde:"Latinska mala črka n s tildo",ograve:"Latinska mala črka o s krativcem",oacute:"Latinska mala črka o z ostrivcem",ocirc:"Latinska mala črka o s strešico",otilde:"Latinska mala črka o s tildo",ouml:"Latinska mala črka o z dierezo",divide:"Znak za deljenje",oslash:"Latinska mala črka o s črtico",
ugrave:"Latinska mala črka u s krativcem",uacute:"Latinska mala črka u z ostrivcem",ucirc:"Latinska mala črka u s strešico",uuml:"Latinska mala črka u z dierezo",yacute:"Latinska mala črka y z ostrivcem",thorn:"Latinska mala črka thorn",yuml:"Latinska mala črka y z dierezo",OElig:"Latinska velika vezava OE",oelig:"Latinska mala vezava oe",372:"Latinska velika črka W s strešico",374:"Latinska velika črka Y s strešico",373:"Latinska mala črka w s strešico",375:"Latinska mala črka y s strešico",sbquo:"Enojni narekovaj low-9",
8219:"Enojni narekovaj high-reversed-9",bdquo:"Dvojni narekovaj low-9",hellip:"Vodoravne trik pike",trade:"Znak za blagovno znamko",9658:"Črna kazalka v desno",bull:"Naštevna oznaka",rarr:"Puščica v desno",rArr:"Dvojna puščica v desno",hArr:"Dvojna puščica v levo in desno",diams:"Črna kara",asymp:"Skoraj enako kot"});