/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/licensePortions Copyright IBM Corp., 2009-2015.
*/
CKEDITOR.plugins.setLang("specialchar","tr",{euro:"Euro işareti",lsquo:"Sol tek tırnak işareti",rsquo:"Sağ tek tırnak işareti",ldquo:"Sol çift tırnak işareti",rdquo:"Sağ çift tırnak işareti",ndash:"Kısa tire",mdash:"Uzun tire",iexcl:"Ters ünlem işareti",cent:"Sent işareti",pound:"Pound işareti",curren:"Para birimi işareti",yen:"Yen işareti",brvbar:"Kırık çubuk",sect:"Bölüm işareti",uml:"Çift nokta işareti",copy:"Telif hakkı işareti",ordf:"Dişi sıra göstergesi",laquo:"Açık köşeli çift tırnak",not:"Değildir işareti",
reg:"Tescilli marka işareti",macr:"Uzatma işareti",deg:"Derece işareti",sup2:"Üst simge iki",sup3:"Üst simge üç",acute:"Vurgu işareti",micro:"Mikro işareti",para:"Pilcrow işareti",middot:"Orta nokta",cedil:"Çengel",sup1:"Üst simge bir",ordm:"Erkek sıra göstergesi",raquo:"Kapalı köşeli çift tırnak",frac14:"Bayağı kesir dörtte bir",frac12:"Bayağı kesir yarım",frac34:"Bayağı kesir dörtte üç",iquest:"Ters soru işareti",Agrave:"Aksan işaretli Latin büyük harf A",Aacute:"Vurgu işaretli Latin büyük harf A",
Acirc:"İnceltme işaretli Latin büyük harf A",Atilde:"Tilde işaretli Latin büyük harf A",Auml:"Çift nokta işaretli Latin büyük harf A",Aring:"Üstte halka işaretli Latin büyük harf A",AElig:"Latin Büyük Harf Æ",Ccedil:"Çengel işaretli Latin büyük harf C",Egrave:"Aksan işaretli Latin büyük harf E",Eacute:"Vurgu işaretli Latin büyük harf E",Ecirc:"İnceltme işaretli Latin büyük harf E",Euml:"Çift nokta işaretli Latin büyük harf E",Igrave:"Aksan işaretli Latin büyük harf I",Iacute:"Vurgu işaretli Latin büyük harf I",
Icirc:"İnceltme işaretli Latin büyük harf I",Iuml:"Çift nokta işaretli Latin büyük harf I",ETH:"Latin büyük harf Eth",Ntilde:"Tilde işaretli Latin büyük harf N",Ograve:"Aksan işaretli Latin büyük harf O",Oacute:"Vurgu işaretli Latin büyük harf O",Ocirc:"İnceltme işaretli Latin büyük harf O",Otilde:"Tilde işaretli Latin büyük harf O",Ouml:"Çift nokta işaretli Latin büyük harf O",times:"Çarpma işareti",Oslash:"Bölü işaretli Latin büyük harf O",Ugrave:"Aksan işaretli Latin büyük harf U",Uacute:"Vurgu işaretli Latin büyük harf U",
Ucirc:"İnceltme işaretli Latin büyük harf U",Uuml:"Çift nokta işaretli Latin büyük harf U",Yacute:"Vurgu işaretli Latin büyük harf Y",THORN:"Latin büyük harf Thorn",szlig:"Latin küçük harf sivri s",agrave:"Aksan işaretli Latin küçük harf a",aacute:"Vurgu işaretli Latin küçük harf a",acirc:"İnceltme işaretli Latin küçük harf a",atilde:"Tilde işaretli Latin küçük harf a",auml:"Çift nokta işaretli Latin küçük harf a",aring:"Üstte halka işaretli Latin küçük harf a",aelig:"Latin küçük harf æ",ccedil:"Çengel işaretli Latin küçük harf c",
egrave:"Aksan işaretli Latin küçük harf e",eacute:"Vurgu işaretli Latin küçük harf e",ecirc:"İnceltme işaretli Latin küçük harf e",euml:"Çift nokta işaretli Latin Latin küçük harf e",igrave:"Aksan işaretli Latin küçük harf i",iacute:"Vurgu işaretli Latin küçük harf i",icirc:"İnceltme işaretli Latin küçük harf i",iuml:"Çift nokta işaretli Latin küçük harf i",eth:"Latin küçük harf eth",ntilde:"Tilde işaretli Latin küçük harf n",ograve:"Aksan işaretli Latin küçük harf o",oacute:"Vurgu işaretli Latin küçük harf o",
ocirc:"İnceltme işaretli Latin küçük harf o",otilde:"Tilde işaretli Latin küçük harf o",ouml:"Çift nokta işaretli Latin küçük harf o",divide:"Bölme işareti",oslash:"Bölü işaretli Latin küçük harf o",ugrave:"Aksan işaretli Latin küçük harf u",uacute:"Vurgu işaretli Latin küçük harf u",ucirc:"İnceltme işaretli Latin küçük harf u",uuml:"Çift nokta işaretli Latin küçük harf u",yacute:"Vurgu işaretli Latin küçük harf y",thorn:"Latin küçük harf thorn",yuml:"Çift nokta işaretli Latin küçük harf y",OElig:"Latin büyük bağlı OE",
oelig:"Latin küçük bağlı oe",372:"İnceltme işaretli Latin büyük harf W",374:"İnceltme işareti Latin büyük harf Y",373:"İnceltme işaretli Latin küçük harf w",375:"İnceltme işaretli Latin küçük harf y",sbquo:"Tek düşük 9 tırnak işareti",8219:"Tek yüksek ters 9 tırnak işareti",bdquo:"Çift düşük 9 tırnak işareti",hellip:"Yatay üç nokta",trade:"Ticari marka işareti",9658:"Sağ yönü gösteren siyah ok",bull:"Madde işareti",rarr:"Sağ ok",rArr:"Sağ çift ok",hArr:"Sol sağ çift ok",diams:"Siyah baklava biçimi",
asymp:"Hemen hemen eşit"});