(function(){function u(b,h){for(var g=-1,a=0;a<b.length;a++)if(b[a][h]){g=a;break}if(-1!=g){a=new CKEDITOR.dom.element(b[g][h]);if(a=a.getStyle("width")?a.getStyle("width"):a.getAttribute("width")){if(s.exec(a))return;t.exec(a)&&(a+="px")}else a="0px";for(var d=p.exec(a),a=d[1],k=d[2],l,g=g+1;g<b.length;g++)if(d=b[g][h]?new CKEDITOR.dom.element(b[g][h]):null){var e=d.getStyle("width")?d.getStyle("width"):d.getAttribute("width");if(e){if(s.exec(e))return;t.exec(e)&&(e+="px");d=p.exec(e);l=d[1];d=d[2];
d!=k&&("px"!=d&&(l=CKEDITOR.tools.convertToPx(e)),"px"!=k&&(a=CKEDITOR.tools.convertToPx(a+k),k="px"));l>a&&(a=l)}}return a+k}}function v(b,h,g){var a=p.exec(b),d=a[1],k=a[2],l=m.getStyle("width")?m.getStyle("width"):m.getAttribute("width");if(s.exec(l))return l;t.exec(l)&&(l+="px");if(a=p.exec(l))var e=a[1],a=a[2];else return l;if(k!=a&&("px"!=k&&(d=CKEDITOR.tools.convertToPx(b)),"px"!=a))var e=CKEDITOR.tools.convertToPx(l),j=a,a="px";e=parseFloat(e);d=parseFloat(d);b=g?e>d?e-d:e:e+d*h;if(j){var c;
switch(j){case "in":c=b*w;break;case "cm":c=b*x;break;case "mm":c=b*y;break;case "em":c=b*z;break;case "ex":c=b*A;break;case "pt":c=b*B;break;case "pc":c=b*C}b=Math.round(c*Math.pow(10,2))/Math.pow(10,2);a=j}return b+a}function r(b,h){for(var g=h?Infinity:0,a=0;a<b.length;a++){var d;d=b[a];for(var k=h,l=d.getParent().$.cells,e=0,j=0;j<l.length;j++){var c=l[j],e=e+(k?1:c.colSpan);if(c==d.$)break}d=e-1;if(h?d<g:d>g)g=d}return g}var m,o,p=/^(\d+(?:\.\d+)?)(px|in|cm|mm|em|ex|pt|pc)$/,t=/^(\d+(?:\.\d+)?)$/,
s=/^(\d+(?:\.\d+)?)%$/,w,x,y,z,A,B,C;CKEDITOR.plugins.add("ibmtabletools",{lang:"ar,ca,cs,da,de,el,en,es,fi,fr,he,hr,hu,it,iw,ja,kk,ko,nb,nl,no,pl,pt,pt-br,ro,ru,sk,sl,sv,th,tr,uk,zh,zh-cn,zh-tw",requires:["colordialog"],init:function(b){function h(j){var c=j,b=/^<table(.|\n)+<\/table>(<br[^>]*>)?$/i,i=/^<tr(.|\n)+<\/tr>$/i,f=/^<(td|th)(.|\n)+<\/(td|th)>$/gi;this.parse=function(){return!i.test(c)&&!f.test(c)&&!b.test(c)?!1:!0};this.insertRowBefore=function(j){var i=j.getSelection(),f=i.getSelectedElement();
i=f&&f instanceof CKEDITOR.dom.element&&"tr"==f.getName()?f:(i=i.getCommonAncestor())&&i instanceof CKEDITOR.dom.element&&"tr"==i.getName()?i:i.getAscendant("tr")?i.getAscendant("tr"):null;if(i){b.test(c);/<tr(.|\s)+<\/tr>/i.test(c)||(c="<tr>"+c+"</tr>");b.test(c)||(c="<table>"+c+"</table>");for(var j=CKEDITOR.dom.element.createFromHtml(c,j.document),e,f=0;f<j.getChildCount();f++)if(j.getChild(f)instanceof CKEDITOR.dom.element&&("tbody"==j.getChild(f).getName()||"thead"==j.getChild(f).getName())){for(var a=
j.getChild(f),d=0;d<a.getChildCount();d++)if(a.getChild(d)instanceof CKEDITOR.dom.element&&"tr"==a.getChild(d).getName()){e=a.getChild(d);break}if(e)break}for(f=0;f<e.getChildCount();f++)if(e.getChild(f)instanceof CKEDITOR.dom.element&&("td"==e.getChild(f).getName()||"th"==e.getChild(f).getName()))if(1<(e.getChild(f).hasAttribute("rowSpan")?e.getChild(f).getAttribute("rowSpan"):0))return!1;e.insertBefore(i);return!0}return!1}}function g(j){var c=j.data;if("table"==c.getName()){var b=c.hasAttribute("fixedwidthcolumns")?
c.getAttribute("fixedwidthcolumns"):!1;c.removeAttribute("fixedwidthcolumns");if(j.editor.config.ibmModernTable.enable&&CKEDITOR.env.ie&&9>CKEDITOR.env.version){c.setStyle("border-collapse","collapse");c.setStyle("border-color","#696969");for(var i=c.getElementsByTag("*"),f=0;f<i.count();f++)"td"==i.getItem(f).getName().toLowerCase()&&(oldStyle=i.getItem(f).getAttribute("style"),null!=oldStyle&&-1!=oldStyle.indexOf("color")&&(e=k),oldStyle=oldStyle?oldStyle:"",i.getItem(f).setAttribute("style",oldStyle+
" "+l),e=d)}j.editor.config.ibmModernTable.enable&&!(CKEDITOR.env.ie&&9>CKEDITOR.env.version)&&c.setAttribute("class","border_collapse");if(b){c.setStyle("table-layout","fixed");c.setStyle("word-wrap","break-word");var j=c.$.rows,f=c.getStyle("width"),c=j[0].childNodes.length,f=/^(\d+(?:\.\d+)?)(px|%|in|cm|mm|em|ex|pt|pc)$/.exec(f),n,a;f&&(n=f[1],a=f[2]);n="%"==a?100:parseFloat(n);"px"!=a&&"pt"!=a&&"mm"!=a?(f=Math.floor(n/c*Math.pow(10,2))/Math.pow(10,2),b=Math.round((n-f*c)*Math.pow(10,2))/Math.pow(10,
2)):(f=Math.floor(n/c),b=n%c);n=f+a;a=Math.round((f+b)*Math.pow(10,2))/Math.pow(10,2)+a;for(b=0;b<j.length;b++){i=(new CKEDITOR.dom.element(j[b])).$.cells;for(f=0;f<c-1;f++)(new CKEDITOR.dom.element(i[f])).setStyle("width",n);(new CKEDITOR.dom.element(i[c-1])).setStyle("width",a)}}}}function a(j,c){if(c.config.ibmModernTable.enable){var b=new CKEDITOR.dom.element("style");CKEDITOR.env.ie&&9>CKEDITOR.env.version?b.$.cssText="table.border_collapse{ "+j+"}table.border_collapse td{ "+l+"}":b.setHtml("table.border_collapse{ "+
j+"}table.border_collapse td{ "+l+"}");b.setAttribute("id","border-collapse-css");c.document.getHead().append(b)}c.config.ibmModernTable.enforceStyle&&(b=new CKEDITOR.dom.element("style"),CKEDITOR.env.ie&&9>CKEDITOR.env.version?b.$.cssText="table{ "+j+"}td,tr,th{ "+l+"}":b.setHtml("table{ "+j+"}td,tr,th{ "+l+"}"),b.setAttribute("id","border-collapse-css"),c.document.getHead().append(b))}w=1/CKEDITOR.tools.convertToPx("1in");z=1/CKEDITOR.tools.convertToPx("1em");A=1/CKEDITOR.tools.convertToPx("1ex");
C=1/CKEDITOR.tools.convertToPx("1pc");x=100/CKEDITOR.tools.convertToPx("100cm");y=100/CKEDITOR.tools.convertToPx("100mm");B=100/CKEDITOR.tools.convertToPx("100pt");b.addCommand("selectTable",new CKEDITOR.command(b,{requiredContent:"table",exec:function(j){var j=j.getSelection(),c=j.getCommonAncestor();(c=c?c.getAscendant("table"):null)&&j.selectElement(c)},modes:{wysiwyg:1}}));b.contextMenu.addListener(function(j){return j.hasAscendant("table",1)?b.config.enableTableSort?{select_table:CKEDITOR.TRISTATE_OFF,
table_sort:CKEDITOR.TRISTATE_OFF}:{select_table:CKEDITOR.TRISTATE_OFF}:null});b.addCommand("selectTableRow",new CKEDITOR.command(b,{requiredContent:"table",exec:function(j){var j=j.getSelection(),c=j.getCommonAncestor();(c=c&&c.getName&&"tr"==c.getName()?c:c.getAscendant("tr"))&&j.selectElement(c)},modes:{wysiwyg:1}}));b.addCommand("insertMultipleRows",{requiredContent:"table",exec:function(j,c){for(var b=j.getSelection(),i="before"==c.insertLocation?!0:!1,f=c.noOfRows,a=CKEDITOR.plugins.tabletools.getSelectedCells(b),
b=a[0],e=b.getAscendant("table"),b=b.getDocument(),d=a[0].getParent(),l=d.$.rowIndex,a=a[a.length-1],q=a.getParent().$.rowIndex+a.$.rowSpan-1,a=new CKEDITOR.dom.element(e.$.rows[q]),l=i?l:q,d=i?d:a,a=CKEDITOR.tools.buildTableMap(e),e=a[l],l=i?a[l-1]:a[l+1],a=a[0].length,q=0;q<f;q++){for(var k=b.createElement("tr"),h=0;e[h]&&h<a;h++){var g;1<e[h].rowSpan&&l&&e[h]==l[h]?(g=e[h],g.rowSpan+=1):(g=(new CKEDITOR.dom.element(e[h])).clone(),g.removeAttribute("rowSpan"),g.appendBogus(),k.append(g),g=g.$);
h+=g.colSpan-1}i?k.insertBefore(d):k.insertAfter(d)}}});b.addCommand("insertMultipleColumns",{requiredContent:"table",exec:function(b,c){for(var a=b.getSelection(),e="before"==c.insertLocation?!0:!1,f=c.noOfCols,d=CKEDITOR.plugins.tabletools.getSelectedCells(a),a=d[0].getAscendant("table"),l=r(d,1),d=r(d),h=e?l:d,g=CKEDITOR.tools.buildTableMap(a),a=[],l=[],d=g.length,k=0;k<d;k++){a.push(g[k][h]);var m=e?g[k][h-1]:g[k][h+1];m&&l.push(m)}for(h=0;h<f;h++)for(k=0;k<d;k++)void 0!=a[k]&&(1<a[k].colSpan&&
l.length&&l[k]==a[k]?(g=a[k],g.colSpan+=1):(g=(new CKEDITOR.dom.element(a[k])).clone(),g.removeAttribute("colSpan"),!CKEDITOR.env.ie&&g.appendBogus(),g[e?"insertBefore":"insertAfter"].call(g,new CKEDITOR.dom.element(a[k])),g=g.$),k+=g.rowSpan-1)}});CKEDITOR.dialog.add("insertRows",this.path+"dialogs/insertRows.js");b.addCommand("insertRows",new CKEDITOR.dialogCommand("insertRows",{requiredContent:"table"}));CKEDITOR.dialog.add("insertColumns",this.path+"dialogs/insertColumns.js");b.addCommand("insertCols",
new CKEDITOR.dialogCommand("insertColumns",{requiredContent:"table"}));CKEDITOR.dialog.add("columnProperties",this.path+"dialogs/columnProperties.js");b.addCommand("columnProps",new CKEDITOR.dialogCommand("columnProperties",{allowedContent:"td th{width}",requiredContent:"table{width}"}));CKEDITOR.dialog.add("tablesort",this.path+"dialogs/tablesort.js");b.addCommand("tablesort",new CKEDITOR.dialogCommand("tablesort",{requiredContent:"table"}));b.on("paste",function(b){var c=new h(b.data.dataValue);
c.parse()&&c.insertRowBefore(b.editor)&&b.cancel()});var d="border-collapse : collapse; border-color : #696969;",k="",l="border-color : #696969;",e=d;b.on("instanceReady",function(){b.on("insertElement",g);a(e,b);b.on("beforeGetData",function(a){if(a.editor&&a.editor.document&&!(CKEDITOR.env.ie&&9>CKEDITOR.env.version)){var c;if(b.config.ibmModernTable.enforceStyle){c=a.editor.document.getElementsByTag("table");for(var g=0;g<c.count();g++){"border_collapse"==c.getItem(g).getAttribute("class")&&c.getItem(g).removeAttribute("class");
var i=c.getItem(g).getAttribute("style");null!=i&&-1!=i.indexOf("color")&&(e="border-collapse : collapse; ");c.getItem(g).setAttribute("style",i+" "+e);e=d;for(var f=c.getItem(g).getElementsByTag("*"),h=0;h<f.count();h++)"td"==f.getItem(h).getName().toLowerCase()&&(i=f.getItem(h).getAttribute("style"),e=null!=i&&-1!=i.indexOf("color")?k:l,i=i?i:"",f.getItem(h).setAttribute("style",i+" "+e),e=d)}}if(b.config.ibmModernTable.enable&&!b.config.ibmModernTable.enforceStyle){c=a.editor.document.$.getElementsByClassName("border_collapse");
for(var m in c){if(c[m].getElementsByTagName)for(iter in i=c[m].getAttribute("style"),null!=i&&-1!=i.indexOf("color")&&(e="border-collapse : collapse; "),c[m].setAttribute("style",i+" "+e),e=d,f=c[m].getElementsByTagName("*"),f)f[iter].setAttribute&&"td"==f[iter].tagName.toLowerCase()&&(i=f[iter].getAttribute("style"),e=null!=i&&-1!=i.indexOf("color")?k:l,i=i?i:"",f[iter].setAttribute("style",i+" "+e),e=d);c[m].removeAttribute&&c[m].removeAttribute("class")}}}},null,null,0);b.on("dataReady",function(b){b.editor.document&&
null==b.editor.document.getById("border-collapsed-css")&&a(e,b.editor)})});b.on("beforeCommandExec",function(b){if("columnDelete"==b.data.name){var b=b.editor.getSelection(),c=CKEDITOR.plugins.tabletools.getSelectedCells(b);a:{var b=c[0],a=c[c.length-1];m=b.getAscendant("table");for(var c=CKEDITOR.tools.buildTableMap(m),e,f,d=0,g=c.length;d<g;d++)for(var k=0,l=c[d].length;k<l;k++)c[d][k]==b.$&&(e=k),c[d][k]==a.$&&(f=k);for(var b=0,h,d=e;d<=f;d++){h=u(c,d);if(!h){o=void 0;break a}b+=parseFloat(h)}e=
p.exec(h)[2];o=b+e}}});b.on("afterCommandExec",function(a){if("columnInsertAfter"==a.data.name||"columnInsertBefore"==a.data.name||"insertMultipleColumns"==a.data.name){var c=a.editor.getSelection(),e=CKEDITOR.plugins.tabletools.getSelectedCells(c),c=a.data.commandData&&a.data.commandData.noOfCols?a.data.commandData.noOfCols:1,d="columnInsertBefore"==a.data.name?!0:!1,f=e[0],g=r(e,1),e=r(e),d=d?g:e;m=f.getAscendant("table");f=CKEDITOR.tools.buildTableMap(m);if((o=u(f,d))&&"0px"!=o)m.setStyle("width",
v(o,c)),b.fire("updateSnapshot")}else"columnDelete"==a.data.name&&(o&&"0px"!=o)&&(m.setStyle("width",v(o,null,!0)),b.fire("updateSnapshot"));if("cellInsertBefore"==a.data.name||"cellInsertAfter"==a.data.name||"cellDelete"==a.data.name){a=a.editor.getSelection();f=CKEDITOR.plugins.tabletools.getSelectedCells(a)[0].getAscendant("table");a=f.getElementsByTag("td");d=f.getElementsByTag("tbody").getItem(0).getChildren();for(c=g=0;c<d.count();c++)g=d.getItem(c).getChildren().count()>g?d.getItem(c).getChildren().count():
g;f=f.getStyle("width").split("px")[0]/g;for(c=0;c<a.count();c++)a.getItem(c).setStyle("width",f+"px");b.fire("updateSnapshot")}})},afterInit:function(b){if(b.addMenuItems){b.addMenuGroup("tablecolumnproperties");b.addMenuItems({select_table:{label:b.lang.ibmtabletools.selectTable,command:"selectTable",group:"table",order:2},table_sort:{label:b.lang.ibmtabletools.sortTableContextMenuOption,command:"tablesort",group:"table",order:2},select_tablerow:{label:b.lang.ibmtabletools.selectRow,command:"selectTableRow",
group:"tablerow",order:20},insert_rows:{label:b.lang.ibmtabletools.insertMultipleRows,group:"tablerow",command:"insertRows",order:1},insert_cols:{label:b.lang.ibmtabletools.insertMultipleCols,group:"tablecolumn",command:"insertCols",order:1},column_properties:{label:b.lang.ibmtabletools.columnTitle,group:"tablecolumnproperties",command:"columnProps",order:20}});var h=b.getMenuItem("tablerow"),g=h.getItems;h.getItems=function(){var a=g();a.insert_rows=CKEDITOR.TRISTATE_OFF;a.select_tablerow=CKEDITOR.TRISTATE_OFF;
for(var d in a){var e=b.getMenuItem(d);if(-1<e.className.indexOf(" submenuItem"))break;e.className+=" submenuItem"}return a};var h=b.getMenuItem("tablecolumn"),a=h.getItems;h.getItems=function(){var d=a();d.insert_cols=CKEDITOR.TRISTATE_OFF;d.column_properties=CKEDITOR.TRISTATE_OFF;for(var g in d){var e=b.getMenuItem(g);if(-1<e.className.indexOf(" submenuItem"))break;e.className+=" submenuItem"}return d};var h=b.getMenuItem("tablecell"),d=h.getItems;h.getItems=function(){var a=d(),g;for(g in a){var e=
b.getMenuItem(g);if(-1<e.className.indexOf(" submenuItem"))break;e.className+=" submenuItem"}return a}}}})})();