//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 11:14:39 AM CST 
//


package com.ibm.commerce.foundation.common.entities;

import com.ibm.commerce.copyright.IBMCopyright;



/**
 * <p>Java class for AssociatedPromotion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssociatedPromotion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PromotionIdentifier" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}PromotionIdentifier" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}Description" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class AssociatedPromotion {

	/**
	 * IBM copyright notice field.
	 */
	@SuppressWarnings("unused")
	private static final String COPYRIGHT = IBMCopyright.SHORT_COPYRIGHT;
	
    protected PromotionIdentifier promotionIdentifier;
    protected Description description;

    /**
     * Gets the value of the promotionIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link PromotionIdentifier }
     *     
     */
    public PromotionIdentifier getPromotionIdentifier() {
        return promotionIdentifier;
    }

    /**
     * Sets the value of the promotionIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link PromotionIdentifier }
     *     
     */
    public void setPromotionIdentifier(PromotionIdentifier value) {
        this.promotionIdentifier = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link Description }
     *     
     */
    public Description getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description }
     *     
     */
    public void setDescription(Description value) {
        this.description = value;
    }

}
