//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 11:14:39 AM CST 
//


package com.ibm.commerce.foundation.common.entities;

import java.util.ArrayList;
import java.util.List;

import com.ibm.commerce.copyright.IBMCopyright;


/**
 * <p>Java class for AttachmentReference complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AttachmentReference">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AttachmentReferenceIdentifier" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}AttachmentReferenceIdentifier" minOccurs="0"/>
 *         &lt;element name="AttachmentIdentifier" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}AttachmentIdentifier" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}AttachmentAsset" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}AttachmentUsage" minOccurs="0"/>
 *         &lt;element name="DisplaySequence" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}AttachmentDescription" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}AttachmentReferenceDescription" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}UserData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class AttachmentReference {

	/**
	 * IBM copyright notice field.
	 */
	@SuppressWarnings("unused")
	private static final String COPYRIGHT = IBMCopyright.SHORT_COPYRIGHT;
	
    protected AttachmentReferenceIdentifier attachmentReferenceIdentifier;
    protected AttachmentIdentifier attachmentIdentifier;
    protected List<AttachmentAsset> attachmentAsset;
    protected AttachmentUsage attachmentUsage;
    protected String displaySequence;
    protected List<AttachmentDescription> attachmentDescription;
    protected List<AttachmentDescription> attachmentReferenceDescription;
    protected UserData userData;

    /**
     * Gets the value of the attachmentReferenceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link AttachmentReferenceIdentifier }
     *     
     */
    public AttachmentReferenceIdentifier getAttachmentReferenceIdentifier() {
        return attachmentReferenceIdentifier;
    }

    /**
     * Sets the value of the attachmentReferenceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttachmentReferenceIdentifier }
     *     
     */
    public void setAttachmentReferenceIdentifier(AttachmentReferenceIdentifier value) {
        this.attachmentReferenceIdentifier = value;
    }

    /**
     * Gets the value of the attachmentIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link AttachmentIdentifier }
     *     
     */
    public AttachmentIdentifier getAttachmentIdentifier() {
        return attachmentIdentifier;
    }

    /**
     * Sets the value of the attachmentIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttachmentIdentifier }
     *     
     */
    public void setAttachmentIdentifier(AttachmentIdentifier value) {
        this.attachmentIdentifier = value;
    }

    /**
     * 
     * 						The Attachment Assets that belongs to that Attachment which is associated to the business object in this relation.
     * 					Gets the value of the attachmentAsset property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attachmentAsset property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttachmentAsset().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttachmentAsset }
     * 
     * 
     */
    public List<AttachmentAsset> getAttachmentAsset() {
        if (attachmentAsset == null) {
            attachmentAsset = new ArrayList<AttachmentAsset>();
        }
        return this.attachmentAsset;
    }

    /**
     * 
     * 						The usage of the attachment that is associated with the business object.
     * 					
     * 
     * @return
     *     possible object is
     *     {@link AttachmentUsage }
     *     
     */
    public AttachmentUsage getAttachmentUsage() {
        return attachmentUsage;
    }

    /**
     * Sets the value of the attachmentUsage property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttachmentUsage }
     *     
     */
    public void setAttachmentUsage(AttachmentUsage value) {
        this.attachmentUsage = value;
    }

    /**
     * Gets the value of the displaySequence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplaySequence() {
        return displaySequence;
    }

    /**
     * Sets the value of the displaySequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplaySequence(String value) {
        this.displaySequence = value;
    }

    /**
     * 
     * 						The description of the attachment.
     * 					Gets the value of the attachmentDescription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attachmentDescription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttachmentDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttachmentDescription }
     * 
     * 
     */
    public List<AttachmentDescription> getAttachmentDescription() {
        if (attachmentDescription == null) {
            attachmentDescription = new ArrayList<AttachmentDescription>();
        }
        return this.attachmentDescription;
    }

    /**
     * 
     * 						The description of the relation between the business object and the attachment.
     * 					Gets the value of the attachmentReferenceDescription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attachmentReferenceDescription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttachmentReferenceDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttachmentDescription }
     * 
     * 
     */
    public List<AttachmentDescription> getAttachmentReferenceDescription() {
        if (attachmentReferenceDescription == null) {
            attachmentReferenceDescription = new ArrayList<AttachmentDescription>();
        }
        return this.attachmentReferenceDescription;
    }

    /**
     * The user data area.
     * 
     * @return
     *     possible object is
     *     {@link UserData }
     *     
     */
    public UserData getUserData() {
        return userData;
    }

    /**
     * Sets the value of the userData property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserData }
     *     
     */
    public void setUserData(UserData value) {
        this.userData = value;
    }

}
