//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 11:14:39 AM CST 
//


package com.ibm.commerce.foundation.common.entities;

import com.ibm.commerce.copyright.IBMCopyright;



/**
 * The external identifier type of catalog filter condition value.
 * 
 * <p>Java class for CatalogFilterConditionValueExternalIdentifier complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CatalogFilterConditionValueExternalIdentifier">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CatalogFilterConditionIdentifier" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}CatalogFilterConditionIdentifier" minOccurs="0"/>
 *         &lt;element name="Identifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class CatalogFilterConditionValueExternalIdentifier {

	/**
	 * IBM copyright notice field.
	 */
	@SuppressWarnings("unused")
	private static final String COPYRIGHT = IBMCopyright.SHORT_COPYRIGHT;
	
    protected CatalogFilterConditionIdentifier catalogFilterConditionIdentifier;
    protected String identifier;

    /**
     * Gets the value of the catalogFilterConditionIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogFilterConditionIdentifier }
     *     
     */
    public CatalogFilterConditionIdentifier getCatalogFilterConditionIdentifier() {
        return catalogFilterConditionIdentifier;
    }

    /**
     * Sets the value of the catalogFilterConditionIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogFilterConditionIdentifier }
     *     
     */
    public void setCatalogFilterConditionIdentifier(CatalogFilterConditionIdentifier value) {
        this.catalogFilterConditionIdentifier = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

}
