//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 11:14:39 AM CST 
//


package com.ibm.commerce.foundation.common.entities;

import com.ibm.commerce.copyright.IBMCopyright;



/**
 * <p>Java class for ChequeDeliveryMethodCodeEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ChequeDeliveryMethodCodeEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="MLDB"/>
 *     &lt;enumeration value="MLCD"/>
 *     &lt;enumeration value="MLFA"/>
 *     &lt;enumeration value="CRDB"/>
 *     &lt;enumeration value="CRCD"/>
 *     &lt;enumeration value="CRFA"/>
 *     &lt;enumeration value="PUDB"/>
 *     &lt;enumeration value="PUCD"/>
 *     &lt;enumeration value="PUFA"/>
 *     &lt;enumeration value="RGDB"/>
 *     &lt;enumeration value="RGCD"/>
 *     &lt;enumeration value="RGFA"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
public enum ChequeDeliveryMethodCodeEnumeration {


    /**
     * 
     * 						Mail to Debitor
     * 					
     * 
     */
    MLDB,

    /**
     * 
     * 						Mail to Creditor
     * 					
     * 
     */
    MLCD,

    /**
     * 
     * 						Mail to Final agent
     * 					
     * 
     */
    MLFA,

    /**
     * 
     * 						Courier to debtor
     * 					
     * 
     */
    CRDB,

    /**
     * 
     * 						Courier to creditor
     * 					
     * 
     */
    CRCD,

    /**
     * 
     * 						Courier to final agent
     * 					
     * 
     */
    CRFA,

    /**
     * 
     * 						Pickup by debtor
     * 					
     * 
     */
    PUDB,

    /**
     * 
     * 						Pickup by creditor
     * 					
     * 
     */
    PUCD,

    /**
     * 
     * 						Pickup by final agent
     * 					
     * 
     */
    PUFA,

    /**
     * 
     * 						Registered mail to debtor
     * 					
     * 
     */
    RGDB,

    /**
     * 
     * 						Registered mail to creditor
     * 					
     * 
     */
    RGCD,

    /**
     * 
     * 						Registered mail to final agent
     * 					
     * 
     */
    RGFA;

    /**
	 * IBM copyright notice field.
	 */
	@SuppressWarnings("unused")
	private static final String COPYRIGHT = IBMCopyright.SHORT_COPYRIGHT;
	
    public String value() {
        return name();
    }

    public static ChequeDeliveryMethodCodeEnumeration fromValue(String v) {
        return valueOf(v);
    }

}
