//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 11:14:39 AM CST 
//


package com.ibm.commerce.foundation.common.entities;

import com.ibm.commerce.copyright.IBMCopyright;



/**
 * <p>Java class for ControlAssertionEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ControlAssertionEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="Completeness"/>
 *     &lt;enumeration value="Existence or Occurance"/>
 *     &lt;enumeration value="Presentation and Disclosure"/>
 *     &lt;enumeration value="Rights and Obligations"/>
 *     &lt;enumeration value="Valuation or Measurement"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
public enum ControlAssertionEnumeration {

    COMPLETENESS("Completeness"),
    EXISTENCE_OR_OCCURANCE("Existence or Occurance"),
    PRESENTATION_AND_DISCLOSURE("Presentation and Disclosure"),
    RIGHTS_AND_OBLIGATIONS("Rights and Obligations"),
    VALUATION_OR_MEASUREMENT("Valuation or Measurement");
    private final String value;

    ControlAssertionEnumeration(String v) {
        value = v;
    }

    /**
	 * IBM copyright notice field.
	 */
	@SuppressWarnings("unused")
	private static final String COPYRIGHT = IBMCopyright.SHORT_COPYRIGHT;
	
    public String value() {
        return value;
    }

    public static ControlAssertionEnumeration fromValue(String v) {
        for (ControlAssertionEnumeration c: ControlAssertionEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
