//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 11:14:39 AM CST 
//


package com.ibm.commerce.foundation.common.entities;

import com.ibm.commerce.copyright.IBMCopyright;



/**
 * <p>Java class for FinalAgentInstructionCodeEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FinalAgentInstructionCodeEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="CHQB"/>
 *     &lt;enumeration value="HOLD"/>
 *     &lt;enumeration value="PHOB"/>
 *     &lt;enumeration value="TELB"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
public enum FinalAgentInstructionCodeEnumeration {


    /**
     * 
     * 						Pay creditor only by cheque. The creditor's
     * 						account number must not be specified.
     * 					
     * 
     */
    CHQB,

    /**
     * 
     * 						Hold cash for creditor. Creditor will call; pay
     * 						upon identification.
     * 					
     * 
     */
    HOLD,

    /**
     * 
     * 						Please advise/contact beneficiary/claimant by
     * 						phone.
     * 					
     * 
     */
    PHOB,

    /**
     * 
     * 						Please advise/contact beneficiary/claimant by
     * 						the most efficient means of telecommunication.
     * 					
     * 
     */
    TELB;

    /**
	 * IBM copyright notice field.
	 */
	@SuppressWarnings("unused")
	private static final String COPYRIGHT = IBMCopyright.SHORT_COPYRIGHT;
	
    public String value() {
        return name();
    }

    public static FinalAgentInstructionCodeEnumeration fromValue(String v) {
        return valueOf(v);
    }

}
