//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 11:14:39 AM CST 
//


package com.ibm.commerce.foundation.common.entities;

import com.ibm.commerce.copyright.IBMCopyright;



/**
 * <p>Java class for GiftListIdentifier complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GiftListIdentifier">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UniqueID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GiftListExternalIdentifier" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}GiftListExternalIdentifier"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class GiftListIdentifier {

	/**
	 * IBM copyright notice field.
	 */
	@SuppressWarnings("unused")
	private static final String COPYRIGHT = IBMCopyright.SHORT_COPYRIGHT;
	
    protected String uniqueID;
    protected GiftListExternalIdentifier giftListExternalIdentifier;

    /**
     * Gets the value of the uniqueID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniqueID() {
        return uniqueID;
    }

    /**
     * Sets the value of the uniqueID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniqueID(String value) {
        this.uniqueID = value;
    }

    /**
     * Gets the value of the giftListExternalIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link GiftListExternalIdentifier }
     *     
     */
    public GiftListExternalIdentifier getGiftListExternalIdentifier() {
        return giftListExternalIdentifier;
    }

    /**
     * Sets the value of the giftListExternalIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link GiftListExternalIdentifier }
     *     
     */
    public void setGiftListExternalIdentifier(GiftListExternalIdentifier value) {
        this.giftListExternalIdentifier = value;
    }

}
