//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 11:14:39 AM CST 
//


package com.ibm.commerce.foundation.common.entities;

import java.util.ArrayList;
import java.util.List;

import com.ibm.commerce.copyright.IBMCopyright;


/**
 * Type definition of the order's charges.
 * 
 * <p>Java class for OrderCharges complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderCharges">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GrandTotal" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}MonetaryAmount" minOccurs="0"/>
 *         &lt;element name="TotalProductPrice" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}MonetaryAmount" minOccurs="0"/>
 *         &lt;element name="TotalAdjustment" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}MonetaryAmount" minOccurs="0"/>
 *         &lt;element name="GenericTotal" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}GenericTotal" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Adjustment" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}Adjustment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TotalShippingCharge" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}MonetaryAmount" minOccurs="0"/>
 *         &lt;element name="TotalSalesTax" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}MonetaryAmount" minOccurs="0"/>
 *         &lt;element name="TotalShippingTax" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}MonetaryAmount" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}TotalTaxByTaxCategory" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}UserData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class OrderCharges {

	/**
	 * IBM copyright notice field.
	 */
	@SuppressWarnings("unused")
	private static final String COPYRIGHT = IBMCopyright.SHORT_COPYRIGHT;
	
    protected MonetaryAmount grandTotal;
    protected MonetaryAmount totalProductPrice;
    protected MonetaryAmount totalAdjustment;
    protected List<GenericTotal> genericTotal;
    protected List<Adjustment> adjustment;
    protected MonetaryAmount totalShippingCharge;
    protected MonetaryAmount totalSalesTax;
    protected MonetaryAmount totalShippingTax;
    protected List<TaxByTaxCategory> totalTaxByTaxCategory;
    protected UserData userData;

    /**
     * Gets the value of the grandTotal property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryAmount }
     *     
     */
    public MonetaryAmount getGrandTotal() {
        return grandTotal;
    }

    /**
     * Sets the value of the grandTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryAmount }
     *     
     */
    public void setGrandTotal(MonetaryAmount value) {
        this.grandTotal = value;
    }

    /**
     * Gets the value of the totalProductPrice property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryAmount }
     *     
     */
    public MonetaryAmount getTotalProductPrice() {
        return totalProductPrice;
    }

    /**
     * Sets the value of the totalProductPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryAmount }
     *     
     */
    public void setTotalProductPrice(MonetaryAmount value) {
        this.totalProductPrice = value;
    }

    /**
     * Gets the value of the totalAdjustment property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryAmount }
     *     
     */
    public MonetaryAmount getTotalAdjustment() {
        return totalAdjustment;
    }

    /**
     * Sets the value of the totalAdjustment property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryAmount }
     *     
     */
    public void setTotalAdjustment(MonetaryAmount value) {
        this.totalAdjustment = value;
    }

    /**
     * Gets the value of the genericTotal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the genericTotal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGenericTotal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GenericTotal }
     * 
     * 
     */
    public List<GenericTotal> getGenericTotal() {
        if (genericTotal == null) {
            genericTotal = new ArrayList<GenericTotal>();
        }
        return this.genericTotal;
    }

    /**
     * Gets the value of the adjustment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the adjustment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdjustment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Adjustment }
     * 
     * 
     */
    public List<Adjustment> getAdjustment() {
        if (adjustment == null) {
            adjustment = new ArrayList<Adjustment>();
        }
        return this.adjustment;
    }

    /**
     * Gets the value of the totalShippingCharge property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryAmount }
     *     
     */
    public MonetaryAmount getTotalShippingCharge() {
        return totalShippingCharge;
    }

    /**
     * Sets the value of the totalShippingCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryAmount }
     *     
     */
    public void setTotalShippingCharge(MonetaryAmount value) {
        this.totalShippingCharge = value;
    }

    /**
     * Gets the value of the totalSalesTax property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryAmount }
     *     
     */
    public MonetaryAmount getTotalSalesTax() {
        return totalSalesTax;
    }

    /**
     * Sets the value of the totalSalesTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryAmount }
     *     
     */
    public void setTotalSalesTax(MonetaryAmount value) {
        this.totalSalesTax = value;
    }

    /**
     * Gets the value of the totalShippingTax property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryAmount }
     *     
     */
    public MonetaryAmount getTotalShippingTax() {
        return totalShippingTax;
    }

    /**
     * Sets the value of the totalShippingTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryAmount }
     *     
     */
    public void setTotalShippingTax(MonetaryAmount value) {
        this.totalShippingTax = value;
    }

    /**
     * The total tax amount for each tax category.Gets the value of the totalTaxByTaxCategory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the totalTaxByTaxCategory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTotalTaxByTaxCategory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaxByTaxCategory }
     * 
     * 
     */
    public List<TaxByTaxCategory> getTotalTaxByTaxCategory() {
        if (totalTaxByTaxCategory == null) {
            totalTaxByTaxCategory = new ArrayList<TaxByTaxCategory>();
        }
        return this.totalTaxByTaxCategory;
    }

    /**
     * The user data area.
     * 
     * @return
     *     possible object is
     *     {@link UserData }
     *     
     */
    public UserData getUserData() {
        return userData;
    }

    /**
     * Sets the value of the userData property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserData }
     *     
     */
    public void setUserData(UserData value) {
        this.userData = value;
    }

}
