//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 11:14:39 AM CST 
//


package com.ibm.commerce.foundation.common.entities;

import com.ibm.commerce.copyright.IBMCopyright;



/**
 * <p>Java class for PaymentBasisCodeEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PaymentBasisCodeEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="InvoiceDate"/>
 *     &lt;enumeration value="ShippingDate"/>
 *     &lt;enumeration value="DeliveryDate"/>
 *     &lt;enumeration value="PurchaseOrderDate"/>
 *     &lt;enumeration value="ReceiptOfGoodsDate"/>
 *     &lt;enumeration value="AcceptanceOfGoodsDate"/>
 *     &lt;enumeration value="AcceptanceOfOrderDate"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
public enum PaymentBasisCodeEnumeration {

    INVOICE_DATE("InvoiceDate"),
    SHIPPING_DATE("ShippingDate"),
    DELIVERY_DATE("DeliveryDate"),
    PURCHASE_ORDER_DATE("PurchaseOrderDate"),
    RECEIPT_OF_GOODS_DATE("ReceiptOfGoodsDate"),
    ACCEPTANCE_OF_GOODS_DATE("AcceptanceOfGoodsDate"),
    ACCEPTANCE_OF_ORDER_DATE("AcceptanceOfOrderDate");
    private final String value;

    /**
	 * IBM copyright notice field.
	 */
	@SuppressWarnings("unused")
	private static final String COPYRIGHT = IBMCopyright.SHORT_COPYRIGHT;
	
    PaymentBasisCodeEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PaymentBasisCodeEnumeration fromValue(String v) {
        for (PaymentBasisCodeEnumeration c: PaymentBasisCodeEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
