//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 11:14:39 AM CST 
//


package com.ibm.commerce.foundation.common.entities;

import com.ibm.commerce.copyright.IBMCopyright;



/**
 * <p>Java class for RemitLocationMethodCodeEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RemitLocationMethodCodeEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="FAX"/>
 *     &lt;enumeration value="EDI"/>
 *     &lt;enumeration value="URI"/>
 *     &lt;enumeration value="EML"/>
 *     &lt;enumeration value="PST"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
public enum RemitLocationMethodCodeEnumeration {


    /**
     * 
     * 						Remittance advice information needs to be faxed.
     * 					
     * 
     */
    FAX,

    /**
     * 
     * 						Remittance advice information needs to be sent
     * 						through Electronic Data Interchange.
     * 					
     * 
     */
    EDI,

    /**
     * 
     * 						Remittance advice information needs to be sent
     * 						to a Uniform Resource Identifier (URI). URI is a
     * 						compact string of characters that uniquely
     * 						identify an abstract or physical resource. URI's
     * 						are the super-set of identifiers, such as URLs,
     * 						email addresses, ftp sites, etc, and as such,
     * 						provide the syntax for all of the identification
     * 						schemes.
     * 					
     * 
     */
    URI,
    EML,
    PST;

    /**
	 * IBM copyright notice field.
	 */
	@SuppressWarnings("unused")
	private static final String COPYRIGHT = IBMCopyright.SHORT_COPYRIGHT;
	
    public String value() {
        return name();
    }

    public static RemitLocationMethodCodeEnumeration fromValue(String v) {
        return valueOf(v);
    }

}
