//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 11:14:39 AM CST 
//


package com.ibm.commerce.foundation.common.entities;

import com.ibm.commerce.copyright.IBMCopyright;



/**
 * <p>Java class for RiskEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RiskEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="Compliance with applicable laws and regulations"/>
 *     &lt;enumeration value="Effectiveness and efficiency of operations"/>
 *     &lt;enumeration value="Reliability of Financial Statements"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
public enum RiskEnumeration {

    COMPLIANCE_WITH_APPLICABLE_LAWS_AND_REGULATIONS("Compliance with applicable laws and regulations"),
    EFFECTIVENESS_AND_EFFICIENCY_OF_OPERATIONS("Effectiveness and efficiency of operations"),
    RELIABILITY_OF_FINANCIAL_STATEMENTS("Reliability of Financial Statements");
    private final String value;

    /**
	 * IBM copyright notice field.
	 */
	@SuppressWarnings("unused")
	private static final String COPYRIGHT = IBMCopyright.SHORT_COPYRIGHT;
	
    RiskEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RiskEnumeration fromValue(String v) {
        for (RiskEnumeration c: RiskEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
