//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 11:14:39 AM CST 
//


package com.ibm.commerce.foundation.common.entities;

import com.ibm.commerce.copyright.IBMCopyright;



/**
 * <p>Java class for SEOSiteMapInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SEOSiteMapInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Priority" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="ChangeFrequency" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}SEOURLChangeFrequencyType" minOccurs="0"/>
 *         &lt;element name="MobilePriority" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="MobileChangeFrequency" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}SEOURLChangeFrequencyType" minOccurs="0"/>
 *         &lt;element name="UserData" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}UserData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class SEOSiteMapInfo {

	/**
	 * IBM copyright notice field.
	 */
	@SuppressWarnings("unused")
	private static final String COPYRIGHT = IBMCopyright.SHORT_COPYRIGHT;
	
    protected Double priority;
    protected String changeFrequency;
    protected Double mobilePriority;
    protected String mobileChangeFrequency;
    protected UserData userData;

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPriority(Double value) {
        this.priority = value;
    }

    /**
     * Gets the value of the changeFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangeFrequency() {
        return changeFrequency;
    }

    /**
     * Sets the value of the changeFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangeFrequency(String value) {
        this.changeFrequency = value;
    }

    /**
     * Gets the value of the mobilePriority property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMobilePriority() {
        return mobilePriority;
    }

    /**
     * Sets the value of the mobilePriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMobilePriority(Double value) {
        this.mobilePriority = value;
    }

    /**
     * Gets the value of the mobileChangeFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobileChangeFrequency() {
        return mobileChangeFrequency;
    }

    /**
     * Sets the value of the mobileChangeFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobileChangeFrequency(String value) {
        this.mobileChangeFrequency = value;
    }

    /**
     * Gets the value of the userData property.
     * 
     * @return
     *     possible object is
     *     {@link UserData }
     *     
     */
    public UserData getUserData() {
        return userData;
    }

    /**
     * Sets the value of the userData property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserData }
     *     
     */
    public void setUserData(UserData value) {
        this.userData = value;
    }

}
