//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 11:14:39 AM CST 
//


package com.ibm.commerce.foundation.common.entities;

import java.util.ArrayList;
import java.util.List;

import com.ibm.commerce.copyright.IBMCopyright;


/**
 * <p>Java class for SEOURL complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SEOURL">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="URLKeywordID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TokenValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Usage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ParentStoreIdentifier" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}StoreIdentifier" minOccurs="0"/>
 *         &lt;element name="URLKeyword" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}SEOURLKeyword" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SiteMapInfo" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}SEOSiteMapInfo" minOccurs="0"/>
 *         &lt;element name="UserData" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}UserData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class SEOURL {

	/**
	 * IBM copyright notice field.
	 */
	@SuppressWarnings("unused")
	private static final String COPYRIGHT = IBMCopyright.SHORT_COPYRIGHT;
	
    protected String urlKeywordID;
    protected String tokenValue;
    protected String usage;
    protected StoreIdentifier parentStoreIdentifier;
    protected List<SEOURLKeyword> urlKeyword;
    protected SEOSiteMapInfo siteMapInfo;
    protected UserData userData;

    /**
     * Gets the value of the urlKeywordID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURLKeywordID() {
        return urlKeywordID;
    }

    /**
     * Sets the value of the urlKeywordID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURLKeywordID(String value) {
        this.urlKeywordID = value;
    }

    /**
     * Gets the value of the tokenValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenValue() {
        return tokenValue;
    }

    /**
     * Sets the value of the tokenValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenValue(String value) {
        this.tokenValue = value;
    }

    /**
     * Gets the value of the usage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsage() {
        return usage;
    }

    /**
     * Sets the value of the usage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsage(String value) {
        this.usage = value;
    }

    /**
     * Gets the value of the parentStoreIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link StoreIdentifier }
     *     
     */
    public StoreIdentifier getParentStoreIdentifier() {
        return parentStoreIdentifier;
    }

    /**
     * Sets the value of the parentStoreIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link StoreIdentifier }
     *     
     */
    public void setParentStoreIdentifier(StoreIdentifier value) {
        this.parentStoreIdentifier = value;
    }

    /**
     * Gets the value of the urlKeyword property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the urlKeyword property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getURLKeyword().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SEOURLKeyword }
     * 
     * 
     */
    public List<SEOURLKeyword> getURLKeyword() {
        if (urlKeyword == null) {
            urlKeyword = new ArrayList<SEOURLKeyword>();
        }
        return this.urlKeyword;
    }

    /**
     * Gets the value of the siteMapInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SEOSiteMapInfo }
     *     
     */
    public SEOSiteMapInfo getSiteMapInfo() {
        return siteMapInfo;
    }

    /**
     * Sets the value of the siteMapInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SEOSiteMapInfo }
     *     
     */
    public void setSiteMapInfo(SEOSiteMapInfo value) {
        this.siteMapInfo = value;
    }

    /**
     * Gets the value of the userData property.
     * 
     * @return
     *     possible object is
     *     {@link UserData }
     *     
     */
    public UserData getUserData() {
        return userData;
    }

    /**
     * Sets the value of the userData property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserData }
     *     
     */
    public void setUserData(UserData value) {
        this.userData = value;
    }

}
