//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 11:14:39 AM CST 
//


package com.ibm.commerce.foundation.common.entities;

import com.ibm.commerce.copyright.IBMCopyright;



/**
 * The type definition of a wallet item's external identifier.
 * 
 * <p>Java class for WalletItemExternalIdentifier complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WalletItemExternalIdentifier">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="WalletIdentifier" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}WalletIdentifier" minOccurs="0"/>
 *         &lt;element name="FolderIdentifier" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}WalletItemIdentifier" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Path" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class WalletItemExternalIdentifier {

	/**
	 * IBM copyright notice field.
	 */
	@SuppressWarnings("unused")
	private static final String COPYRIGHT = IBMCopyright.SHORT_COPYRIGHT;
	
    protected WalletIdentifier walletIdentifier;
    protected WalletItemIdentifier folderIdentifier;
    protected String name;
    protected String path;

    /**
     * Gets the value of the walletIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link WalletIdentifier }
     *     
     */
    public WalletIdentifier getWalletIdentifier() {
        return walletIdentifier;
    }

    /**
     * Sets the value of the walletIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link WalletIdentifier }
     *     
     */
    public void setWalletIdentifier(WalletIdentifier value) {
        this.walletIdentifier = value;
    }

    /**
     * Gets the value of the folderIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link WalletItemIdentifier }
     *     
     */
    public WalletItemIdentifier getFolderIdentifier() {
        return folderIdentifier;
    }

    /**
     * Sets the value of the folderIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link WalletItemIdentifier }
     *     
     */
    public void setFolderIdentifier(WalletItemIdentifier value) {
        this.folderIdentifier = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

}
