/*
 Copyright (c) 2003-2015, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
(function(){function u(a){return CKEDITOR.env.ie?a.$.clientWidth:parseInt(a.getComputedStyle("width"),10)}function p(a,c,b){var c=a.getComputedStyle("border-"+c+"-width"),l={thin:"0px",medium:"1px",thick:"2px"};0>c.indexOf("px")&&(c=c in l&&"none"!=a.getComputedStyle("border-style")?l[c]:0);return b&&b.config.ibmModernTable&&b.config.ibmModernTable.enable?Math.max(parseInt(c,10),2):parseInt(c,10)}function w(a,c){var b=[],l=-1,e="rtl"==a.getComputedStyle("direction"),h;h=a.$.rows;for(var f=0,g,d,m,
j=0,k=h.length;j<k;j++)m=h[j],g=m.cells.length,g>f&&(f=g,d=m);h=d;f=new CKEDITOR.dom.element(a.$.tBodies[0]);g=f.getDocumentPosition();d=0;for(m=h.cells.length;d<m;d++){var j=new CKEDITOR.dom.element(h.cells[d]),k=h.cells[d+1]&&new CKEDITOR.dom.element(h.cells[d+1]),l=l+(j.$.colSpan||1),q,i,n=j.getDocumentPosition().x;e?i=n+p(j,"left",c):q=n+j.$.offsetWidth-p(j,"right",c);k?(n=k.getDocumentPosition().x,e?q=n+k.$.offsetWidth-p(k,"right",c):i=n+p(k,"left",c)):(n=a.getDocumentPosition().x,e?q=n:i=n+
a.$.offsetWidth);j=Math.max(i-q,3);b.push({table:a,index:l,x:q,y:g.y,width:j,height:f.$.offsetHeight,rtl:e})}return b}function v(a){(a.data||a).preventDefault()}function A(a){function c(){m=0;d.setOpacity(0);k&&b();var a=f.table;setTimeout(function(){a.removeCustomData("_cke_table_pillars")},0);g.removeListener("dragstart",v)}function b(){for(var z=f.rtl,d=z?x.length:q.length,c=0;c<d;c++){var e=q[c],b=x[c],g=f.table;CKEDITOR.tools.setTimeout(function(a,c,d,e,b,f){a&&a.setStyle("width",i(Math.max(c+
f,1)));d&&d.setStyle("width",i(Math.max(e-f,1)));b&&g.setStyle("width",i(b+f*(z?-1:1)))},0,this,[e,e&&u(e),b,b&&u(b),(!e||!b)&&u(g)+p(g,"left",a)+p(g,"right",a),k])}}function l(a){v(a);for(var a=f.index,c=CKEDITOR.tools.buildTableMap(f.table),b=[],l=[],i=Number.MAX_VALUE,p=i,t=f.rtl,s=0,w=c.length;s<w;s++){var o=c[s],r=o[a+(t?1:0)],o=o[a+(t?0:1)],r=r&&new CKEDITOR.dom.element(r),o=o&&new CKEDITOR.dom.element(o);if(!r||!o||!r.equals(o))r&&(i=Math.min(i,u(r))),o&&(p=Math.min(p,u(o))),b.push(r),l.push(o)}q=
b;x=l;n=f.x-i;y=f.x+p;d.setOpacity(0.5);j=parseInt(d.getStyle("left"),10);k=0;m=1;d.on("mousemove",h);g.on("dragstart",v);g.on("mouseup",e,this)}function e(a){a.removeListener();c()}function h(a){s(a.data.getPageOffset().x)}var f,g,d,m,j,k,q,x,n,y;g=a.document;d=CKEDITOR.dom.element.createFromHtml('<div data-cke-temp=1 contenteditable=false unselectable=on style="position:absolute;cursor:col-resize;filter:alpha(opacity=0);opacity:0;padding:0;background-color:#004;background-image:none;border:0px none;z-index:10"></div>',
g);a.on("destroy",function(){d.remove()});t||g.getDocumentElement().append(d);this.attachTo=function(a){m||(t&&(g.getBody().append(d),k=0),f=a,d.setStyles({width:i(a.width),height:i(a.height),left:i(a.x),top:i(a.y)}),t&&d.setOpacity(0.25),d.on("mousedown",l,this),g.getBody().setStyle("cursor","col-resize"),d.show())};var s=this.move=function(a){if(!f)return 0;if(!m&&(a<f.x||a>f.x+f.width))return f=null,m=k=0,g.removeListener("mouseup",e),d.removeListener("mousedown",l),d.removeListener("mousemove",
h),g.getBody().setStyle("cursor","auto"),t?d.remove():d.hide(),0;a-=Math.round(d.$.offsetWidth/2);if(m){if(a==n||a==y)return 1;a=Math.max(a,n);a=Math.min(a,y);k=a-j}d.setStyle("left",i(a));return 1}}function s(a){var c=a.data.getTarget();if("mouseout"==a.name){if(!c.is("table"))return;for(var b=new CKEDITOR.dom.element(a.data.$.relatedTarget||a.data.$.toElement);b&&b.$&&!b.equals(c)&&!b.is("body");)b=b.getParent();if(!b||b.equals(c))return}c.getAscendant("table",1).removeCustomData("_cke_table_pillars");
a.removeListener()}var i=CKEDITOR.tools.cssLength,t=CKEDITOR.env.ie&&(CKEDITOR.env.ie7Compat||CKEDITOR.env.quirks);CKEDITOR.plugins.add("tableresize",{requires:"tabletools",init:function(a){a.on("contentDom",function(){var c,b=a.editable();b.attachListener(b.isInline()?b:a.document,"mousemove",function(b){var b=b.data,e=b.getTarget();if(e.type==CKEDITOR.NODE_ELEMENT){var h=b.getPageOffset().x;if(c&&c.move(h))v(b);else if(e.is("table")||e.getAscendant("tbody",1))if(e=e.getAscendant("table",1),a.editable().contains(e)){if(!(b=
e.getCustomData("_cke_table_pillars")))e.setCustomData("_cke_table_pillars",b=w(e,a)),e.on("mouseout",s),e.on("mousedown",s);a:{for(var e=0,f=b.length;e<f;e++){var g=b[e];if(h>=g.x&&h<=g.x+g.width){h=g;break a}}h=null}h&&(!c&&(c=new A(a)),c.attachTo(h))}}})})}})})();