/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license

Portions Copyright IBM Corp., 2009-2015.
*/
CKEDITOR.plugins.setLang("specialchar","cs",{euro:"Znak euro",lsquo:"Levý apostrof",rsquo:"Pravý apostrof",ldquo:"Levé uvozovky",rdquo:"Pravé uvozovky",ndash:"Krátká pomlčka",mdash:"Dlouhá pomlčka",iexcl:"Obrácený vykřičník",cent:"Znak cent",pound:"Znak libra",curren:"Znak měna",yen:"Znak yen",brvbar:"Přerušovaná svislá čára",sect:"Znak paragraf",uml:"Přehláska",copy:"Znak copyright",ordf:"Indikátor ženského rodu",laquo:"Dvojitá levá uvozovka",not:"Znak negace",reg:"Registrační známka",macr:"Vodorovná čárka",
deg:"Znak stupeň",sup2:"Horní index dva",sup3:"Horní index tři",acute:"Háček",micro:"Znak mikro",para:"Symbol odstavce",middot:"Tečka uprostřed",cedil:"Akcent cédille",sup1:"Horní index jedna",ordm:"Indikátor mužského rodu",raquo:"Dvojitá pravá uvozovka",frac14:"Jednoduchý zlomek jedna čtvrtina",frac12:"Jednoduchý zlomek jedna polovina",frac34:"Jednoduchý zlomek tři čtvrtiny",iquest:"Obrácený otazník",Agrave:"Velké písmeno A s vlnovkou",Aacute:"Velké písmeno A s čárkou",Acirc:"Velké písmeno A se stříškou",
Atilde:"Velké písmeno A s vlnovkou",Auml:"Velké písmeno A s přehláskou",Aring:"Velké písmeno A s kruhem",AElig:"Velké písmeno Æ",Ccedil:"Velké písmeno C se spodním háčkem",Egrave:"Velké písmeno E s obrácenou čárkou",Eacute:"Velké písmeno E s čárkou",Ecirc:"Velké písmeno E se stříškou",Euml:"Velké písmeno E s přehláskou",Igrave:"Velké písmeno I s obrácenou čárkou",Iacute:"Velké písmeno I s obrácenou čárkou",Icirc:"Velké písmeno I se stříškou",Iuml:"Velké písmeno I s přehláskou",ETH:"Velké písmeno Eth",
Ntilde:"Velké písmeno N s vlnovkou",Ograve:"Velké písmeno O s obrácenou čárkou",Oacute:"Velké písmeno O s čárkou",Ocirc:"Velké písmeno O se stříškou",Otilde:"Velké písmeno O s vlnovkou",Ouml:"Velké písmeno O s přehláskou",times:"Znak násobení",Oslash:"Velké písmeno O se stříškou",Ugrave:"Velké písmeno U s obrácenou čárkou",Uacute:"Velké písmeno U s čárkou",Ucirc:"Velké písmeno U se stříškou",Uuml:"Velké písmeno U s přehláskou",Yacute:"Velké písmeno Y s čárkou",THORN:"Velké písmeno Thorn",szlig:"Malá písmeno sharp",
agrave:"Malé písmeno a s obrácenou čárkou",aacute:"Malé písmeno a s čárkou",acirc:"Malé písmeno a se stříškou",atilde:"Malé písmeno a s vlnovkou",auml:"Malé písmeno a s přehláskou",aring:"Malé písmeno a s kruhem",aelig:"Malé písmeno æ",ccedil:"Malé písmeno c se spodním háčkem",egrave:"Malé písmeno e s obrácenou čárkou",eacute:"Malé písmeno e s obrácenou čárkou",ecirc:"Malé písmeno e se stříškou",euml:"Malé písmeno e s přehláskou",igrave:"Malé písmeno i s obrácenou čárkou",iacute:"Malé písmeno i s čárkou",
icirc:"Malé písmeno i se stříškou",iuml:"Malé písmeno i s přehláskou",eth:"Malé písmeno eth",ntilde:"Malé písmeno n s vlnovkou",ograve:"Malé písmeno o s obrácenou čárkou",oacute:"Malé písmeno o a s čárkou",ocirc:"Malé písmeno o se stříškou",otilde:"Malé písmeno o s vlnovkou",ouml:"Malé písmeno o s přehláskou",divide:"Znak dělení",oslash:"Malé písmeno o se stříškou",ugrave:"Malé písmeno u s obrácenou čárkou",uacute:"Malé písmeno u s čárkou",ucirc:"Malé písmeno u se stříškou",uuml:"Malé písmeno u s přehláskou",
yacute:"Malé písmeno y s čárkou",thorn:"Malé písmeno thorn",yuml:"Malé písmeno y s přehláskou",OElig:"Slitek OE, velký",oelig:"Slitek oe, malý",372:"Velké písmeno W se stříškou",374:"Velké písmeno Y se stříškou",373:"Malé písmeno w se stříškou",375:"Malé písmeno y se stříškou",sbquo:"Dolní apostrof",8219:"Dolní apostrof",bdquo:"Dolní uvozovky",hellip:"Vodorovné tečky",trade:"Znak ochranná známka",9658:"Černý ukazatel vpravo",bull:"Odrážka",rarr:"Šipka doprava",rArr:"Dvojitá šipka doprava",hArr:"Dvojitá šipka doleva a doprava",
diams:"Káry",asymp:"Přibližně rovno"});