/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license

Portions Copyright IBM Corp., 2009-2015.
*/
CKEDITOR.plugins.setLang("specialchar","fr",{euro:"Signe Euro",lsquo:"Apostrophe dactylographique gauche",rsquo:"Apostrophe dactylographique droite",ldquo:"Guillemets dactylographique gauches",rdquo:"Guillemets dactylographique droits",ndash:"Demi tiret cadratin",mdash:"Tiret cadratin",iexcl:"Point d'exclamation inversé",cent:"Symbole centime",pound:"Symbole livre",curren:"Symbole monétaire",yen:"Symbole Yen",brvbar:"Barre brisée",sect:"Symbole de section",uml:"Tréma",copy:"Symbole de copyright",
ordf:"Indicateur ordinal féminin",laquo:"Guillemets typographiques gauches",not:"Symbole non",reg:"Symbole Déposé",macr:"Macron",deg:"Symbole degré",sup2:"Exposant deux",sup3:"Exposant trois",acute:"Accent aigu",micro:"Symbole micro",para:"Symbole de marque de paragraphe",middot:"Point médian",cedil:"Cédille",sup1:"Exposant un",ordm:"Indicateur ordinal masculin",raquo:"Guillemets typographiques droits",frac14:"Fraction ordinaire un quart",frac12:"Fraction ordinaire un demi",frac34:"Fraction ordinaire trois quarts",
iquest:"Point d'interrogation inversé",Agrave:"Majuscule latine A avec accent grave",Aacute:"Majuscule latine A avec accent aigu",Acirc:"Majuscule latine A avec accent circonflexe",Atilde:"Majuscule latine A avec tilde",Auml:"Majuscule latine A avec tréma",Aring:"Majuscule latine A surmontée d'un rond",AElig:"Majuscule latine Æ",Ccedil:"Majuscule latine C avec cédille",Egrave:"Majuscule latine E avec accent grave",Eacute:"Majuscule latine E avec accent aigu",Ecirc:"Majuscule latine E avec accent circonflexe",
Euml:"Majuscule latine E avec tréma",Igrave:"Majuscule latine I avec accent grave",Iacute:"Majuscule latine I avec accent aigu",Icirc:"Majuscule latine I avec accent circonflexe",Iuml:"Majuscule latine I avec tréma",ETH:"Majuscule latine Eth",Ntilde:"Majuscule latine N avec tilde",Ograve:"Majuscule latine O avec accent grave",Oacute:"Majuscule latine O avec accent aigu",Ocirc:"Majuscule latine O avec accent circonflexe",Otilde:"Majuscule latine O avec tilde",Ouml:"Majuscule latine O avec tréma",times:"Signe de multiplication",
Oslash:"Majuscule latine O avec un trait",Ugrave:"Majuscule latine U avec accent grave",Uacute:"Majuscule latine U avec accent aigu",Ucirc:"Majuscule latine U avec accent circonflexe",Uuml:"Majuscule latine U avec tréma",Yacute:"Majuscule latine Y avec accent aigu",THORN:"Majuscule latine Thorn",szlig:"Minuscule latine eszett (ß)",agrave:"Minuscule latine a avec accent grave",aacute:"Minuscule latine a avec accent aigu",acirc:"Minuscule latine a avec accent circonflexe",atilde:"Minuscule latine a avec tilde",
auml:"Minuscule latine a avec tréma",aring:"Majuscule latine a surmontée d'un rond",aelig:"Minuscule latine æ",ccedil:"Minuscule latine c avec cédille",egrave:"Minuscule latine e avec accent grave",eacute:"Minuscule latine e avec accent aigu",ecirc:"Minuscule latine e avec accent circonflexe",euml:"Minuscule latine e avec tréma",igrave:"Minuscule latine i avec accent grave",iacute:"Minuscule latine i avec accent aigu",icirc:"Minuscule latine i avec accent circonflexe",iuml:"Minuscule latine i avec tréma",
eth:"Minuscule latine eth",ntilde:"Minuscule latine n avec tilde",ograve:"Minuscule latine o avec accent grave",oacute:"Minuscule latine o avec accent aigu",ocirc:"Minuscule latine o avec accent circonflexe",otilde:"Minuscule latine o avec tilde",ouml:"Minuscule latine o avec tréma",divide:"Signe de division",oslash:"Minuscule latine o avec un trait",ugrave:"Minuscule latine u avec accent grave",uacute:"Minuscule latine u avec accent aigu",ucirc:"Minuscule latine u avec accent circonflexe",uuml:"Minuscule latine u avec tréma",
yacute:"Minuscule latine y avec accent aigu",thorn:"Minuscule latine thorn",yuml:"Minuscule latine y avec tréma",OElig:"Majuscule latine ligature OE",oelig:"Minuscule latine ligature oe",372:"Majuscule latine W avec accent circonflexe",374:"Majuscule latine Y avec accent circonflexe",373:"Minuscule latine w avec accent circonflexe",375:"Minuscule latine y avec accent circonflexe",sbquo:"Apostrophe typographique gauche",8219:"Apostrophe typographique droite",bdquo:"Guillemets typographiques anglais gauches",
hellip:"Points de suspension horizontaux",trade:"Symbole de marque déposée",9658:"Pointeur noir vers la droite",bull:"Puce",rarr:"Flèche vers la droite",rArr:"Double flèche vers la droite",hArr:"Double flèche vers la droite et la gauche",diams:"Losange noir",asymp:"Presque égal à"});