/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license

Portions Copyright IBM Corp., 2009-2015.
*/
CKEDITOR.plugins.setLang("specialchar","hr",{euro:"Znak euro",lsquo:"Lijevi jednostruki navodnik",rsquo:"Desni jednostruki navodnik",ldquo:"Lijevi dvostruki navodnik",rdquo:"Desni dvostruki navodnik",ndash:"Kratka crtica",mdash:"Duga crtica",iexcl:"Preokrenuti znak upitnika",cent:"Znak centa",pound:"Znak funte",curren:"Znak valute",yen:"Znak yena",brvbar:"Prekinuta traka",sect:"Znak odjeljka",uml:"Dijereza",copy:"Znak autorskog prava",ordf:"Ženski indikator rednog broja",laquo:"Lijevi mnogo manji",
not:"Znak ne",reg:"Znak registrirano",macr:"Makron",deg:"Znak stupnja",sup2:"Eksponent dva",sup3:"Eksponent tri",acute:"Dugi naglasak",micro:"Znak mikro",para:"Oznaka paragrafa",middot:"Srednja točka",cedil:"Sedilja",sup1:"Eksponent jedan",ordm:"Muški indikator rednog broja",raquo:"Navodnik s dvostrukim kutom koji pokazuje desno",frac14:"Običan razlomak jedne četvrtine",frac12:"Običan razlomak jedne polovine",frac34:"Običan razlomak tri četvrtine",iquest:"Preokrenuti zna upitnika",Agrave:"Latinično veliko slovo A s dugosilaznim naglaskom",
Aacute:"Latinično veliko slovo A s dugouzlaznim naglaskom",Acirc:"Latinično veliko slovo A s dugim naglaskom",Atilde:"Latinično veliko slovo A s tildom",Auml:"Latinično veliko slovo A s dijerezom",Aring:"Latinično veliko slovo A s prstenom",AElig:"Latinično veliko slovo Æ",Ccedil:"Latinično veliko slovo C sa sediljom",Egrave:"Latinično veliko slovo E s dugosilaznim naglaskom",Eacute:"Latinično veliko slovo E s dugouzlaznim naglaskom",Ecirc:"Latinično veliko slovo E s dugim naglaskom",Euml:"Latinično veliko slovo E s dijerezom",
Igrave:"Latinično veliko slovo I s dugosilaznim naglaskom",Iacute:"Latinično veliko slovo I s dugouzlaznim naglaskom",Icirc:"Latinično veliko slovo I s dugim naglaskom",Iuml:"Latinično veliko slovo I s dijerezom",ETH:"Latinično veliko slovo Eth",Ntilde:"Latinično veliko slovo N s tildom",Ograve:"Latinično veliko slovo O s dugosilaznim naglaskom",Oacute:"Latinično veliko slovo O s dugouzlaznim naglaskom",Ocirc:"Latinično veliko slovo O s dugim naglaskom",Otilde:"Latinično veliko slovo O s tildom",
Ouml:"Latinično veliko slovo O s dijerezom",times:"Znak množenja",Oslash:"Latinično veliko slovo O s rubom",Ugrave:"Latinično veliko slovo U s dugosilaznim naglaskom",Uacute:"Latinično veliko slovo U s dugouzlaznim naglaskom",Ucirc:"Latinično veliko slovo U s dugim naglaskom",Uuml:"Latinično veliko slovo U s dijerezom",Yacute:"Latinično veliko slovo Y s dugouzlaznim naglaskom",THORN:"Latinično veliko slovo Thorn",szlig:"Latinično malo slovo oštro s",agrave:"Latinično malo slovo a s dugosilaznim naglaskom",
aacute:"Latinično malo slovo a s dugosilaznim naglaskom",acirc:"Latinično malo slovo a s dugim naglaskom",atilde:"Latinično malo slovo a s tildom",auml:"Latinično malo slovo a s dijerezom",aring:"Latinično malo slovo a s prstenom",aelig:"Latinično malo slovo æ",ccedil:"Latinično malo slovo c sa sediljom",egrave:"Latinično malo slovo e s dugosilaznim naglaskom",eacute:"Latinično malo slovo e s dugouzlaznim naglaskom",ecirc:"Latinično malo slovo e s dugim naglaskom",euml:"Latinično malo slovo e s dijerezom",
igrave:"Latinično malo slovo i s dugosilaznim naglaskom",iacute:"Latinično malo slovo i s dugouzlaznim naglaskom",icirc:"Latinično malo slovo i s dugim naglaskom",iuml:"Latinično malo slovo i s dijerezom",eth:"Latinično malo slovo eth",ntilde:"Latinično malo slovo n s tildom",ograve:"Latinično malo slovo o s dugosilaznim naglaskom",oacute:"Latinično malo slovo o s dugouzlaznim naglaskom",ocirc:"Latinično malo slovo o s dugim naglaskom",otilde:"Latinično malo slovo o s tildom",ouml:"Latinično malo slovo o s dugim naglaskom",
divide:"Znak dijeljenja",oslash:"Latinično malo slovo o s crtom",ugrave:"Latinično malo slovo u s dugosilaznim naglaskom",uacute:"Latinično malo slovo u s dugouzlaznim naglaskom",ucirc:"Latinično malo slovo u s dugim naglaskom",uuml:"Latinično malo slovo u s dijerezom",yacute:"Latinično malo slovo y s dugouzlaznim naglaskom",thorn:"Latinično malo slovo thorn",yuml:"Latinično malo slovo y s dijerezom",OElig:"Latinična velika spojnica OE",oelig:"Latinična mala spojnica oe",372:"Latinično veliko slovo W s dugim naglaskom",
374:"Latinično veliko slovo Y s dugim naglaskom",373:"Latinično malo slovo w s dugim naglaskom",375:"Latinično malo slovo y s dugim naglaskom",sbquo:"Jednostruki donji navodnik",8219:"Jednostruki obrnuti gornji navodnik",bdquo:"Dvostruki donji navodnik",hellip:"Znak za ispuštanje",trade:"Znak proizvođača",9658:"Crni pokazivač koji pokazuje desno",bull:"Oznaka",rarr:"Strelica desno",rArr:"Dvostruka strelica desno",hArr:"Dvostruka strelica lijevo i desno",diams:"Crni dijamant",asymp:"Približno"});