/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license

Portions Copyright IBM Corp., 2009-2015.
*/
CKEDITOR.plugins.setLang("specialchar","id",{euro:"Tanda Euro",lsquo:"Tanda petik tunggal kiri",rsquo:"Tanda petik tunggal kanan",ldquo:"Tanda petik ganda kiri",rdquo:"Tanda petik ganda kanan",ndash:"En dash",mdash:"Em dash",iexcl:"Tanda seru terbalik",cent:"Tanda sen",pound:"Tanda Pound",curren:"Tanda mata uang",yen:"Tanda Yen",brvbar:"Garis putus",sect:"Tanda pemisah",uml:"Diaeresis",copy:"Tanda hak cipta",ordf:"Indikator ordinal feminin",laquo:"Tanda petik menyudut ganda mengarah ke kiri",not:"Tanda tidak",
reg:"Tanda terdaftar",macr:"Makron",deg:"Tanda derajat",sup2:"Superskrip dua",sup3:"Superskrip tiga",acute:"Aksen tirus",micro:"Tanda mikro",para:"Tanda pilcrow",middot:"Titik tengah",cedil:"Cedilla",sup1:"Superskrip satu",ordm:"Indikator ordinal maskulin",raquo:"Tanda petik menyudut ganda mengarah ke kanan",frac14:"Satu perempat fraksi vulgar",frac12:"Satu setengah fraksi vulgar",frac34:"Tiga perempat fraksi vulgar",iquest:"Tanda tanya terbalik",Agrave:"Huruf kapital Latin A dengan aksen grave",
Aacute:"Huruf kapital Latin A dengan aksen tirus",Acirc:"Huruf kapital Latin A dengan sirkumfleks",Atilde:"Huruf kapital Latin A dengan tilde",Auml:"Huruf kapital Latin A dengan diaeresis",Aring:"Huruf kapital Latin A dengan cincin atas",AElig:"Huruf kapital latin Æ",Ccedil:"Huruf kapital Latin C dengan cedilla",Egrave:"Huruf kapital Latin E dengan aksen grave",Eacute:"Huruf kapital Latin E dengan aksen tirus",Ecirc:"Huruf kapital Latin E dengan sirkumfleks",Euml:"Huruf kapital Latin E dengan diaeresis",
Igrave:"Huruf kapital Latin I dengan aksen grave",Iacute:"Huruf kapital Latin I dengan aksen tirus",Icirc:"Huruf kapital Latin I dengan sirkumfleks",Iuml:"Huruf kapital Latin I dengan diaeresis",ETH:"Huruf kapital Latin Eth",Ntilde:"Huruf kapital Latin N dengan tilde",Ograve:"Huruf kapital Latin O dengan aksen grave",Oacute:"Huruf kapital Latin O dengan aksen tirus",Ocirc:"Huruf kapital Latin O dengan sirkumfleks",Otilde:"Huruf kapital Latin O dengan tilde",Ouml:"Huruf kapital Latin O dengan diaeresis",
times:"Tanda perkalian",Oslash:"Huruf kapital Latin O dengan stroke",Ugrave:"Huruf kapital Latin U dengan aksen grave",Uacute:"Huruf kapital Latin U dengan aksen tirus",Ucirc:"Huruf kapital Latin U dengan sirkumfleks",Uuml:"Huruf kapital Latin U dengan diaeresis",Yacute:"Huruf kapital Latin Y dengan aksen tirus",THORN:"Huruf kapital Latin Thorn",szlig:"Huruf kecil Latin sharp s",agrave:"Huruf kapital Latin a dengan aksen grave",aacute:"Huruf kecil Latin a dengan aksen tirus",acirc:"Huruf kecil Latin a dengan sirkumfleks",
atilde:"Huruf kecil Latin a dengan tilde",auml:"Huruf kecil Latin a dengan diaeresis",aring:"Huruf kecil Latin a dengan cincin atas",aelig:"Huruf kecil Latin æ",ccedil:"Huruf kecil Latin c dengan cedilla",egrave:"Huruf kecil Latin e dengan aksen grave",eacute:"Huruf kecil Latin e dengan aksen tirus",ecirc:"Huruf kecil Latin e dengan sirkumfleks",euml:"Huruf kecil Latin e dengan diaeresis",igrave:"Huruf kecil Latin i dengan aksen grave",iacute:"Huruf kecil Latin i dengan aksen tirus",icirc:"Huruf kecil Latin i dengan sirkumfleks",
iuml:"Huruf kecil Latin i dengan diaeresis",eth:"Huruf kecil Latin eth",ntilde:"Huruf kecil Latin n dengan tilde",ograve:"Huruf kecil Latin o dengan aksen grave",oacute:"Huruf kecil Latin o dengan aksen tirus",ocirc:"Huruf kecil Latin o dengan sirkumfleks",otilde:"Huruf kecil Latin o dengan tilde",ouml:"Huruf kecil Latin o dengan diaeresis",divide:"Tanda pembagian",oslash:"Huruf kecil Latin o dengan stroke",ugrave:"Huruf kecil Latin u dengan aksen grave",uacute:"Huruf kecil Latin u dengan aksen tirus",
ucirc:"Huruf kecil Latin u dengan sirkumfleks",uuml:"Huruf kecil Latin u dengan diaeresis",yacute:"Huruf kecil Latin y dengan aksen tirus",thorn:"Huruf kecil Latin thorn",yuml:"Huruf kecil Latin y dengan diaeresis",OElig:"Huruf kapital Latin OE ligature",oelig:"Huruf kecil Latin oe ligature",372:"Huruf kapital Latin W dengan sirkumfleks",374:"Huruf kapital Latin Y dengan sirkumfleks",373:"Huruf kecil Latin w dengan sirkumfleks",375:"Huruf kecil Latin y dengan sirkumfleks",sbquo:"Tanda petik rendah-9 tunggal",
8219:"Tanda petik tinggi-terbalik-9 tunggal",bdquo:"Tanda petik tinggi-9 ganda",hellip:"Elipsis horizontal",trade:"Tanda merek dagang",9658:"Penunjuk hitam mengarah ke kanan",bull:"Poin",rarr:"Tanda panah kanan",rArr:"Tanda panah kanan ganda",hArr:"Tanda panah ganda kanan kiri",diams:"Wajik hitam",asymp:"Hampir sama dengan"});