/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license

Portions Copyright IBM Corp., 2009-2015.
*/
CKEDITOR.plugins.setLang("specialchar","ja",{euro:"ユーロ記号",lsquo:"左単一引用符",rsquo:"右単一引用符",ldquo:"左二重引用符",rdquo:"右二重引用符",ndash:"En ダッシュ",mdash:"Em ダッシュ",iexcl:"逆感嘆符",cent:"セント記号",pound:"ポンド記号",curren:"通貨記号",yen:"円記号",brvbar:"破線バー",sect:"セクション記号",uml:"分音符号",copy:"著作権記号",ordf:"女性序数標識",laquo:"左二重角引用符",not:"否定記号",reg:"登録記号",macr:"長音符号",deg:"角度記号",sup2:"上付き文字 2",sup3:"上付き文字 3",acute:"揚音符号",micro:"マイクロ記号",para:"段落記号",middot:"中黒",cedil:"セディーユ",sup1:"上付き文字 1",ordm:"男性序数標識",raquo:"右二重角引用符",frac14:"分数の 4 分の 1",
frac12:"分数の 2 分の 1",frac34:"分数の 4 分の 3",iquest:"逆疑問符",Agrave:"ラテン語の抑音アクセント付き大文字 A",Aacute:"ラテン語の揚音アクセント付き大文字 A",Acirc:"ラテン語の曲折アクセント記号付き大文字 A",Atilde:"ラテン語の波形記号付き大文字 A",Auml:"ラテン語の分音符号付き大文字 A",Aring:"ラテン語の上リング付き大文字",AElig:"ラテン語の大文字 Æ",Ccedil:"ラテン語のセディーユ付き大文字 C",Egrave:"ラテン語の抑音アクセント付き大文字 E",Eacute:"ラテン語の揚音アクセント付き大文字 E",Ecirc:"ラテン語の曲折アクセント記号付き大文字 E",Euml:"ラテン語の分音符号付き大文字 E",Igrave:"ラテン語の抑音アクセント付き大文字 I",Iacute:"ラテン語の揚音アクセント付き大文字 I",Icirc:"ラテン語の曲折アクセント記号付き大文字 I",Iuml:"ラテン語の分音符号付き大文字 I",ETH:"ラテン語の大文字 ETH",
Ntilde:"ラテン語の波形記号付き大文字 N",Ograve:"ラテン語の抑音アクセント付き大文字 O",Oacute:"ラテン語の揚音アクセント付き大文字 O",Ocirc:"ラテン語の曲折アクセント記号付き大文字 O",Otilde:"ラテン語の波形記号付き大文字 O",Ouml:"ラテン語の分音符号付き大文字 O",times:"乗算記号",Oslash:"ラテン語の斜線付き大文字 O",Ugrave:"ラテン語の抑音アクセント付き大文字 U",Uacute:"ラテン語の揚音アクセント付き大文字 U",Ucirc:"ラテン語の曲折アクセント記号付き大文字 U",Uuml:"ラテン語の分音符号付き大文字 U",Yacute:"ラテン語の揚音アクセント付き大文字 Y",THORN:"ラテン語の大文字 THORN",szlig:"ラテン語の小文字のシャープ s",agrave:"ラテン語の抑音アクセント付き小文字 a",aacute:"ラテン語の揚音アクセント付き小文字 a",acirc:"ラテン語の曲折アクセント記号付き小文字 a",atilde:"ラテン語の波形記号付き小文字 a",
auml:"ラテン語の分音符号付き小文字 a",aring:"ラテン語の上リング付き小文字 a",aelig:"ラテン語の小文字 æ",ccedil:"Latin small letter c with cedilla",egrave:"Latin small letter e with grave accent",eacute:"Latin small letter e with acute accent",ecirc:"Latin small letter e with circumflex",euml:"Latin small letter e with diaeresis",igrave:"Latin small letter i with grave accent",iacute:"Latin small letter i with acute accent",icirc:"Latin small letter i with circumflex",iuml:"Latin small letter i with diaeresis",eth:"Latin small letter eth",
ntilde:"Latin small letter n with tilde",ograve:"Latin small letter o with grave accent",oacute:"Latin small letter o with acute accent",ocirc:"Latin small letter o with circumflex",otilde:"Latin small letter o with tilde",ouml:"Latin small letter o with diaeresis",divide:"Division sign",oslash:"Latin small letter o with stroke",ugrave:"Latin small letter u with grave accent",uacute:"Latin small letter u with acute accent",ucirc:"Latin small letter u with circumflex",uuml:"Latin small letter u with diaeresis",
yacute:"Latin small letter y with acute accent",thorn:"Latin small letter thorn",yuml:"Latin small letter y with diaeresis",OElig:"Latin capital ligature OE",oelig:"Latin small ligature oe",372:"Latin capital letter W with circumflex",374:"Latin capital letter Y with circumflex",373:"Latin small letter w with circumflex",375:"Latin small letter y with circumflex",sbquo:"Single low-9 quotation mark",8219:"Single high-reversed-9 quotation mark",bdquo:"Double low-9 quotation mark",hellip:"Horizontal ellipsis",
trade:"Trade mark sign",9658:"Black right-pointing pointer",bull:"Bullet",rarr:"Rightwards arrow",rArr:"Rightwards double arrow",hArr:"Left right double arrow",diams:"Black diamond suit",asymp:"Almost equal to"});