/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license

Portions Copyright IBM Corp., 2009-2015.
*/
CKEDITOR.plugins.setLang("specialchar","sv",{euro:"Eurotecken",lsquo:"Enkelt vänstercitattecken",rsquo:"Enkelt högercitattecken",ldquo:"Dubbelt vänstercitattecken",rdquo:"Dubbelt högercitattecken",ndash:"Kort tankstreck",mdash:"Långt tankstreck",iexcl:"Inverterat utropstecken",cent:"Centtecken",pound:"Pundtecken",curren:"Valutatecken",yen:"Yentecken",brvbar:"Bruten stapel",sect:"Avsnittstecken",uml:"Trema",copy:"Copyrighttecken",ordf:"Feminin ordningsändelse",laquo:"Dubbelt vänstervinkelcitattecken",
not:"Icke-tecken",reg:"Registrerat varumärke-tecken",macr:"Makron",deg:"Gradtecken",sup2:"Upphöjd tvåa",sup3:"Upphöjd trea",acute:"Akut accent",micro:"Mikrotecken",para:"Alinea",middot:"Halvhög punkt",cedil:"Cedilj",sup1:"Upphöjd etta",ordm:"Maskulin ordningsändelse",raquo:"Dubbelt högervinkelcitattecken",frac14:"En fjärdedel",frac12:"En halv",frac34:"Tre fjärdedelar",iquest:"Inverterat frågetecken",Agrave:"Versalt latinskt A med grav accent",Aacute:"Versalt latinskt A med akut accent",Acirc:"Versalt latinskt A med cirkumflex",
Atilde:"Versalt latinskt A med tilde",Auml:"Versalt latinskt A med trema",Aring:"Versalt latinskt A med ring",AElig:"Versalt latinskt Æ",Ccedil:"Versalt latinskt C med cedilj",Egrave:"Versalt latinskt E med grav accent",Eacute:"Versalt latinskt E med akut accent",Ecirc:"Versalt latinskt E med cirkumflex",Euml:"Versalt latinskt E med trema",Igrave:"Versalt latinskt I med grav accent",Iacute:"Versalt latinskt I med akut accent",Icirc:"Versalt latinskt I med cirkumflex",Iuml:"Versalt latinskt I med trema",
ETH:"Versalt latinskt Ð",Ntilde:"Versalt latinskt N med tilde",Ograve:"Versalt latinskt O med grav accent",Oacute:"Versalt latinskt O med akut accent",Ocirc:"Versalt latinskt O med cirkumflex",Otilde:"Versalt latinskt O med tilde",Ouml:"Versalt latinskt O med trema",times:"Multiplikationstecken",Oslash:"Versalt latinskt O med snedstreck",Ugrave:"Versalt latinskt U med grav accent",Uacute:"Versalt latinskt U med akut accent",Ucirc:"Versalt latinskt U med cirkumflex",Uuml:"Versalt latinskt U med trema",
Yacute:"Versalt latinskt Y med akut accent",THORN:"Versalt latinskt þ",szlig:"Gement latinskt ß",agrave:"Gement latinskt a med grav accent",aacute:"Gement latinskt a med akut accent",acirc:"Gement latinskt a med cirkumflex",atilde:"Gement latinskt a med tilde",auml:"Gement latinskt a med trema",aring:"Gement latinskt a med ring",aelig:"Gement latinskt æ",ccedil:"Gement latinskt c med cedilj",egrave:"Gement latinskt e med grav accent",eacute:"Gement latinskt e med akut accent",ecirc:"Gement latinskt e med cirkumflex",
euml:"Gement latinskt e med trema",igrave:"Gement latinskt i med grav accent",iacute:"Gement latinskt i med akut accent",icirc:"Gement latinskt i med cirkumflex",iuml:"Gement latinskt i med trema",eth:"Gement latinskt ð",ntilde:"Gement latinskt n med tilde",ograve:"Gement latinskt o med grav accent",oacute:"Gement latinskt o med akut accent",ocirc:"Gement latinskt o med cirkumflex",otilde:"Gement latinskt o med tilde",ouml:"Gement latinskt o med trema",divide:"Divisionstecken",oslash:"Gement latinskt o med snedstreck",
ugrave:"Gement latinskt u med grav accent",uacute:"Gement latinskt u med akut accent",ucirc:"Gement latinskt u med cirkumflex",uuml:"Gement latinskt u med trema",yacute:"Gement latinskt y med akut accent",thorn:"Gement latinskt Þ",yuml:"Gement latinskt y med trema",OElig:"Versalt latinskt Œ",oelig:"Gement latinskt œ",372:"Versalt latinskt W med cirkumflex",374:"Versalt latinskt Y med cirkumflex",373:"Gement latinskt w med cirkumflex",375:"Gement latinskt y med cirkumflex",sbquo:"Nedsänkt enkelt vänstercitattecken",
8219:"Enkelt högercitattecken",bdquo:"Nedsänkt dubbelt vänstercitattecken",hellip:"Tre punkter",trade:"Varumärkestecken",9658:"Svart högerpil",bull:"Punkt",rarr:"Högerpil",rArr:"Högerdubbelpil",hArr:"Vänsterdubbelpil",diams:"Svart ruter",asymp:"Nästan lika med"});