void 0===CKEDITOR.ibm&&(CKEDITOR.ibm={});
CKEDITOR.ibm.dialogs=CKEDITOR.tools.createClass({$:function(){},statics:{customDialogs:"table,image,flash,link,cellProperties,find,paste,pastetext,specialchar,bulletedListStyle,numberedListStyle,smiley,iframe,anchor,colordialog,tableProperties,a11yHelp,embedBase",styleWidth100Pc:"width:100%;",customizeListener:function(a){for(var c=a.data,a=a.editor,b=c.definition,d=false,f=function(a){for(var c=a.length;c--;)if(a[c].children)f(a[c].children);else if(a[c].required&&a[c].label){a[c].label="*"+a[c].label;
d=true}},e=0;e<b.contents.length;e++){d=false;b.contents[e].elements&&f(b.contents[e].elements);d&&b.contents[e].add({type:"html",id:"requiredLabel",style:"color: #666666;font-size: 0.9em;padding-top:10px;",html:"<div>* "+a.lang.ibm.common.required+" </div>"})}c=c.name;c==="replace"&&(c="find");this.applyCommonCustomizations(b,a);if((a.config.ibmCustomDialogs!=void 0?a.config.ibmCustomDialogs:this.customDialogs).indexOf(c)!==-1){b.minWidth="";b.minHeight="";if(typeof this[c]==="function")this[c](b,
a)}},applyCommonCustomizations:function(a){a.resizable=CKEDITOR.DIALOG_RESIZE_NONE},getDialogWidth:function(a){var c=a.getName(),b=a.parts.contents,d=CKEDITOR.skin,d=d.dialogDimensions&&d.dialogDimensions[c]?d.dialogDimensions[c][0]:a.definition.minWidth;CKEDITOR.env.quirks&&CKEDITOR.env.ie&&(d=d+this.getWidthAdjustment(b,d));return c==="image"||c==="smiley"||c==="a11yHelp"?d:Math.min(Math.max(d,a.parts.contents.$.offsetWidth,a.parts.title.$.offsetWidth),d*1.25)},getDialogHeight:function(a){for(var c=
a.getName(),b=a.parts.contents,d=CKEDITOR.skin,a=d.dialogDimensions&&d.dialogDimensions[c]?d.dialogDimensions[c][1]:a.definition.minHeight,c=b.getChildCount();c--;)a=Math.max(a,b.getChild(c).getChild(0).$.offsetHeight);CKEDITOR.env.quirks&&CKEDITOR.env.ie&&(a=a+this.getHeightAdjustment(b,a));return a},getHeightAdjustment:function(a,c){var b=this.getAdjustmentValue(a.$.currentStyle.paddingTop,c),b=b+this.getAdjustmentValue(a.$.currentStyle.paddingBottom,c);a.$.currentStyle.marginTop!="auto"&&(b=b+
this.getAdjustmentValue(a.$.currentStyle.marginTop,c));a.$.currentStyle.marginBottom!="auto"&&(b=b+this.getAdjustmentValue(a.$.currentStyle.marginBottom,c));var d=a.$.currentStyle.borderTopWidth;d!="thin"&&(d!="medium"&&d!="thick")&&(b=b+this.getAdjustmentValue(d,c));d=a.$.currentStyle.borderBottomWidth;d!="thin"&&(d!="medium"&&d!="thick")&&(b=b+this.getAdjustmentValue(d,c));return b},getWidthAdjustment:function(a,c){var b=this.getAdjustmentValue(a.$.currentStyle.paddingRight,c),b=b+this.getAdjustmentValue(a.$.currentStyle.paddingLeft,
c);a.$.currentStyle.marginTop!="auto"&&(b=b+this.getAdjustmentValue(a.$.currentStyle.marginRight,c));a.$.currentStyle.marginBottom!="auto"&&(b=b+this.getAdjustmentValue(a.$.currentStyle.marginLeft,c));var d=a.$.currentStyle.borderLeftWidth;d!="thin"&&(d!="medium"&&d!="thick")&&(b=b+this.getAdjustmentValue(d,c));d=a.$.currentStyle.borderRightWidth;d!="thin"&&(d!="medium"&&d!="thick")&&(b=b+this.getAdjustmentValue(d,c));return b},getAdjustmentValue:function(a,c){var b;if(a.indexOf("%")!=-1){a=Math.abs(parseInt(a,
10))/100;b=c*a}else b=a=Math.abs(parseInt(a,10));return b},dialogSizeListener:function(a){a.data.definition.dialog.on("load",function(a){var a=a.sender,b=CKEDITOR.document.getWindow().getViewPaneSize();a.parts.contents.setStyles({width:CKEDITOR.ibm.dialogs.getDialogWidth(a)+"px",height:CKEDITOR.ibm.dialogs.getDialogHeight(a)+"px"});var d=a.getSize();a.move((b.width-d.width)/2,(b.height-d.height)/2)})}}});
(function(){var a=function(a){return!CKEDITOR.hasListeners("dialogDefinition")?false:CKEDITOR._.events.dialogDefinition.getListenerIndex(a)>=0};CKEDITOR.plugins.add("ibmcustomdialogs",{icons:"bidiltr-rtl,bidirtl-rtl,subscript-rtl,superscript-rtl",init:function(c){c.config.extraAllowedContent={"ol ul":{propertiesOnly:true,styles:"font-size"}};var b=CKEDITOR.ibm.dialogs;if(!a(b.customizeListener))CKEDITOR.on("dialogDefinition",b.customizeListener,b,null,1);if(!a(b.dialogSizeListener))CKEDITOR.on("dialogDefinition",
b.dialogSizeListener,b,null,1);c.on("doubleclick",function(a){if(typeof a.data.dialog!=="undefined"&&a.data.dialog!=="")a.data.dialog=""},null,null,900);c.config.dialog_buttonsOrder=c.lang.dir},afterInit:function(a){if(a.ui.items.Find)a.ui.items.Find.args[0].label=a.lang.find.title}})})();