BEGIN_SYMBOL_DEFINITIONS
	COLS:WALLET = WALLET:*
	COLS:WALLET_ID = WALLET:WALLET_ID
END_SYMBOL_DEFINITIONS

BEGIN_XPATH_TO_SQL_STATEMENT
	name=/Wallet[WalletIdentifier/ExternalIdentifier[@ownerID= and Name= and StoreIdentifier[UniqueID=]]]+IBM_IdResolve
	base_table=WALLET
	dbtype=oracle
	sql=
		SELECT
			WALLET.$COLS:WALLET_ID$
		FROM
			WALLET
		WHERE
			WALLET.STOREENT_ID = ?UniqueID? AND WALLET.MEMBER_ID = ?ownerID? AND (WALLET.NAME = ?Name? OR WALLET.NAME IS NULL AND ?Name? IS NULL)
	dbtype=any
	sql=
		SELECT
			WALLET.$COLS:WALLET_ID$
		FROM
			WALLET
		WHERE
			WALLET.STOREENT_ID = ?UniqueID? AND WALLET.MEMBER_ID = ?ownerID? AND WALLET.NAME = ?Name?
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
	name=/Wallet[WalletIdentifier[(UniqueID=)]]+IBM_Update
	base_table=WALLET
	sql=
		SELECT
			WALLET.$COLS:WALLET$
		FROM
			WALLET
		WHERE
			WALLET.WALLET_ID IN (?UniqueID?)
END_XPATH_TO_SQL_STATEMENT
