BEGIN_SYMBOL_DEFINITIONS
	COLS:WALLETITEM = WALLETITEM:*
	COLS:WALLET = WALLET:*
END_SYMBOL_DEFINITIONS

BEGIN_XPATH_TO_SQL_STATEMENT
	name=/WalletItem[WalletItemIdentifier[(UniqueID=)]]+IBM_Store_Details
	base_table=WALLETITEM
	sql=
		SELECT
			WALLETITEM.$COLS:WALLETITEM$, WALLET.$COLS:WALLET$
		FROM
			WALLETITEM, WALLET
		WHERE
			WALLETITEM.WALLETITEM_ID IN (?UniqueID?) AND
			WALLETITEM.WALLET_ID = WALLET.WALLET_ID
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
	name=/WalletItem[WalletItemIdentifier/ExternalIdentifier[Name= and WalletIdentifier[UniqueID=]]]+IBM_Store_Details
	base_table=WALLETITEM
	sql=
		SELECT
			WALLETITEM.$COLS:WALLETITEM$, WALLET.$COLS:WALLET$
		FROM
			WALLETITEM, WALLET
		WHERE
			WALLETITEM.WALLET_ID = ?UniqueID? AND WALLETITEM.NAME = ?Name? AND
			WALLETITEM.WALLET_ID = WALLET.WALLET_ID
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
	name=/WalletItem[WalletItemIdentifier/ExternalIdentifier/WalletIdentifier[UniqueID=]]+IBM_Store_Details
	base_table=WALLETITEM
	sql=
		SELECT
			WALLETITEM.$COLS:WALLETITEM$, WALLET.$COLS:WALLET$
		FROM
			WALLETITEM, WALLET
		WHERE
			WALLETITEM.WALLET_ID = ?UniqueID? AND
			WALLETITEM.WALLET_ID = WALLET.WALLET_ID
END_XPATH_TO_SQL_STATEMENT


BEGIN_XPATH_TO_SQL_STATEMENT
	name=/WalletItem[Type= and WalletItemIdentifier/ExternalIdentifier/WalletIdentifier[UniqueID=]]+IBM_Store_Details
	base_table=WALLETITEM
	sql=
		SELECT
			WALLETITEM.$COLS:WALLETITEM$, WALLET.$COLS:WALLET$
		FROM
			WALLETITEM, WALLET
		WHERE
			WALLETITEM.WALLET_ID = ?UniqueID? AND
			WALLETITEM.TYPE = (CASE WHEN ?Type? = 'Coupon' THEN -2 ELSE 0 END) AND
			WALLETITEM.WALLET_ID = WALLET.WALLET_ID
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
	name=/WalletItem[Data[Status=] and Type= and WalletItemIdentifier/ExternalIdentifier/WalletIdentifier[UniqueID=]]+IBM_Store_Details
	base_table=WALLETITEM
	dbtype=oracle
	sql=
		SELECT
			WALLETITEM.$COLS:WALLETITEM$, WALLET.$COLS:WALLET$
		FROM
			WALLETITEM, PX_COUPON, WALLET
		WHERE
			CAST(WALLETITEM.CONTENT AS NUMBER) = PX_COUPON.PX_COUPON_ID AND
			WALLETITEM.WALLET_ID = ?UniqueID? AND
			WALLETITEM.TYPE = (CASE WHEN ?Type? = 'Coupon' THEN -2 ELSE 0 END) AND
			PX_COUPON.STATUS = ?Status? AND
			WALLETITEM.WALLET_ID = WALLET.WALLET_ID
	dbtype=any
	sql=
		SELECT
			WALLETITEM.$COLS:WALLETITEM$, WALLET.$COLS:WALLET$
		FROM
			WALLETITEM, PX_COUPON, WALLET
		WHERE
			CAST(WALLETITEM.CONTENT AS BIGINT) = PX_COUPON.PX_COUPON_ID AND
			WALLETITEM.WALLET_ID = ?UniqueID? AND
			WALLETITEM.TYPE = (CASE WHEN ?Type? = 'Coupon' THEN -2 ELSE 0 END) AND
			PX_COUPON.STATUS = ?Status? AND
			WALLETITEM.WALLET_ID = WALLET.WALLET_ID
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
	name=/WalletItem[Data/OrderIdentifier[UniqueID=] and Type= and WalletItemIdentifier/ExternalIdentifier/WalletIdentifier[UniqueID=]]+IBM_Store_Details
	base_table=WALLETITEM
	dbtype=oracle
	sql=
		SELECT
			WALLETITEM.$COLS:WALLETITEM$, WALLET.$COLS:WALLET$
		FROM
			WALLETITEM, PX_COUPON, WALLET
		WHERE
			CAST(WALLETITEM.CONTENT AS NUMBER) = PX_COUPON.PX_COUPON_ID AND
			WALLETITEM.WALLET_ID = ?UniqueID.2? AND
			WALLETITEM.TYPE = (CASE WHEN ?Type? = 'Coupon' THEN -2 ELSE 0 END) AND
			PX_COUPON.ORDERS_ID = ?UniqueID.1? AND
			WALLETITEM.WALLET_ID = WALLET.WALLET_ID
	dbtype=any
	sql=
		SELECT
			WALLETITEM.$COLS:WALLETITEM$, WALLET.$COLS:WALLET$
		FROM
			WALLETITEM, PX_COUPON, WALLET
		WHERE
			CAST(WALLETITEM.CONTENT AS BIGINT) = PX_COUPON.PX_COUPON_ID AND
			WALLETITEM.WALLET_ID = ?UniqueID.2? AND
			WALLETITEM.TYPE = (CASE WHEN ?Type? = 'Coupon' THEN -2 ELSE 0 END) AND
			PX_COUPON.ORDERS_ID = ?UniqueID.1? AND
			WALLETITEM.WALLET_ID = WALLET.WALLET_ID
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
	name=/WalletItem[Content= and Type=]+IBM_Store_Details
	base_table=WALLETITEM
	dbtype=oracle
	sql=
		SELECT
			WALLETITEM.$COLS:WALLETITEM$, WALLET.$COLS:WALLET$
		FROM
			WALLETITEM, PX_COUPON, WALLET
		WHERE
			WALLETITEM.CONTENT= ?Content? AND
			CAST(WALLETITEM.CONTENT AS NUMBER) = PX_COUPON.PX_COUPON_ID AND
			WALLETITEM.TYPE = (CASE WHEN ?Type? = 'Coupon' THEN -2 ELSE 0 END) AND
			WALLETITEM.WALLET_ID = WALLET.WALLET_ID
	dbtype=any
	sql=
		SELECT
			WALLETITEM.$COLS:WALLETITEM$, WALLET.$COLS:WALLET$
		FROM
			WALLETITEM, PX_COUPON, WALLET
		WHERE
			WALLETITEM.CONTENT= ?Content? AND
			CAST(WALLETITEM.CONTENT AS BIGINT) = PX_COUPON.PX_COUPON_ID AND
			WALLETITEM.TYPE = (CASE WHEN ?Type? = 'Coupon' THEN -2 ELSE 0 END) AND
			WALLETITEM.WALLET_ID = WALLET.WALLET_ID
END_XPATH_TO_SQL_STATEMENT
