BEGIN_SYMBOL_DEFINITIONS
	COLS:WALLETITEM = WALLETITEM:*
	COLS:WALLETITEM_ID = WALLETITEM:WALLETITEM_ID
	COLS:WALLET = WALLET:*
END_SYMBOL_DEFINITIONS

BEGIN_XPATH_TO_SQL_STATEMENT
	name=/WalletItem[WalletItemIdentifier/ExternalIdentifier[Name= and WalletIdentifier[UniqueID=]]]+IBM_IdResolve
	base_table=WALLETITEM
	sql=
		SELECT
			WALLETITEM.$COLS:WALLETITEM_ID$
		FROM
			WALLETITEM
		WHERE
			WALLETITEM.WALLET_ID = ?UniqueID? AND WALLETITEM.NAME = ?Name?
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
	name=/WalletItem[WalletItemIdentifier[(UniqueID=)]]+IBM_Update
	base_table=WALLETITEM
	sql=
		SELECT
			WALLETITEM.$COLS:WALLETITEM$, WALLET.$COLS:WALLET$
		FROM
			WALLETITEM, WALLET
		WHERE
			WALLETITEM.WALLETITEM_ID IN (?UniqueID?) AND
			WALLETITEM.WALLET_ID = WALLET.WALLET_ID
END_XPATH_TO_SQL_STATEMENT

BEGIN_XPATH_TO_SQL_STATEMENT
	name=/WalletItem[WalletItemIdentifier/ExternalIdentifier/WalletIdentifier[UniqueID=]]+IBM_Update
	base_table=WALLETITEM
	sql=
		SELECT
			WALLETITEM.$COLS:WALLETITEM$
		FROM
			WALLETITEM
		WHERE
			WALLETITEM.WALLET_ID = ?UniqueID?
END_XPATH_TO_SQL_STATEMENT
