//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.21 at 02:34:02 PM CST 
//


package com.ibm.commerce.member.entities;
/*
 *-----------------------------------------------------------------
 * IBM Confidential
 *
 * OCO Source Materials
 *
 * WebSphere Commerce
 *
 * (C) Copyright IBM Corp. 2015, 2016
 *
 * The source code for this program is not published or otherwise
 * divested of its trade secrets, irrespective of what has
 * been deposited with the U.S. Copyright Office.
 *-----------------------------------------------------------------
 */
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.ibm.commerce.copyright.IBMCopyright;
import com.ibm.commerce.foundation.common.entities.ContactInfo;
import com.ibm.commerce.foundation.common.entities.OrganizationIdentifier;
import com.ibm.commerce.foundation.common.entities.PersonIdentifier;
import com.ibm.commerce.foundation.common.entities.UserData;


/**
 * 
 * 	        		Represents a human. It can be a guest, a registered user or an administrator.
 * 			
 * 
 * <p>Java class for Person complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Person">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PersonIdentifier" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}PersonIdentifier" minOccurs="0"/>
 *         &lt;element name="ParentOrganizationIdentifier" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}OrganizationIdentifier" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/member}Credential" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/member}PersonalProfile" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/member}BusinessProfile" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/member}ContactInfo" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/member}AddressBook" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/member}ContextAttribute" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Attributes" type="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}NameValuePair" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/member}CheckoutProfile" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/commerce/9/foundation}UserData" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="registrationStatus" type="{http://www.ibm.com/xmlns/prod/commerce/9/member}RegistrationStatus" />
 *       &lt;attribute name="registrationApprovalStatus" type="{http://www.ibm.com/xmlns/prod/commerce/9/member}RegistrationApprovalStatusType" />
 *       &lt;attribute name="profileType" type="{http://www.ibm.com/xmlns/prod/commerce/9/member}Profile" />
 *       &lt;attribute name="passwordExpired" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="accountStatus" type="{http://www.ibm.com/xmlns/prod/commerce/9/member}AccountStatus" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class Person {

	/**
	 * IBM copyright notice field.
	 */
	@SuppressWarnings("unused")
	private static final String COPYRIGHT = IBMCopyright.SHORT_COPYRIGHT;

    protected PersonIdentifier personIdentifier;
    protected OrganizationIdentifier parentOrganizationIdentifier;
    protected Credential credential;
    protected PersonalProfile personalProfile;
    protected BusinessProfile businessProfile;
    protected ContactInfo contactInfo;
    protected AddressBook addressBook;
    protected List<Attribute> contextAttribute;
    protected Map<String, String> attributes;
    protected List<CheckoutProfile> checkoutProfile;
    protected UserData userData;
    protected String registrationStatus;
    protected String registrationApprovalStatus;
    protected Profile profileType;
    protected Boolean passwordExpired;
    protected String accountStatus;

    /**
     * Gets the value of the personIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link PersonIdentifier }
     *     
     */
    public PersonIdentifier getPersonIdentifier() {
        return personIdentifier;
    }

    /**
     * Sets the value of the personIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonIdentifier }
     *     
     */
    public void setPersonIdentifier(PersonIdentifier value) {
        this.personIdentifier = value;
    }

    /**
     * Gets the value of the parentOrganizationIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationIdentifier }
     *     
     */
    public OrganizationIdentifier getParentOrganizationIdentifier() {
        return parentOrganizationIdentifier;
    }

    /**
     * Sets the value of the parentOrganizationIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationIdentifier }
     *     
     */
    public void setParentOrganizationIdentifier(OrganizationIdentifier value) {
        this.parentOrganizationIdentifier = value;
    }

    /**
     * The credential information.
     * 
     * @return
     *     possible object is
     *     {@link Credential }
     *     
     */
    public Credential getCredential() {
        return credential;
    }

    /**
     * Sets the value of the credential property.
     * 
     * @param value
     *     allowed object is
     *     {@link Credential }
     *     
     */
    public void setCredential(Credential value) {
        this.credential = value;
    }

    /**
     * The personal profile.
     * 
     * @return
     *     possible object is
     *     {@link PersonalProfile }
     *     
     */
    public PersonalProfile getPersonalProfile() {
        return personalProfile;
    }

    /**
     * Sets the value of the personalProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonalProfile }
     *     
     */
    public void setPersonalProfile(PersonalProfile value) {
        this.personalProfile = value;
    }

    /**
     * The business profile.
     * 
     * @return
     *     possible object is
     *     {@link BusinessProfile }
     *     
     */
    public BusinessProfile getBusinessProfile() {
        return businessProfile;
    }

    /**
     * Sets the value of the businessProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessProfile }
     *     
     */
    public void setBusinessProfile(BusinessProfile value) {
        this.businessProfile = value;
    }

    /**
     * The primary contact information.
     * 
     * @return
     *     possible object is
     *     {@link ContactInfo }
     *     
     */
    public ContactInfo getContactInfo() {
        return contactInfo;
    }

    /**
     * Sets the value of the contactInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactInfo }
     *     
     */
    public void setContactInfo(ContactInfo value) {
        this.contactInfo = value;
    }

    /**
     * A list of the contact information.
     * 
     * @return
     *     possible object is
     *     {@link AddressBook }
     *     
     */
    public AddressBook getAddressBook() {
        return addressBook;
    }

    /**
     * Sets the value of the addressBook property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressBook }
     *     
     */
    public void setAddressBook(AddressBook value) {
        this.addressBook = value;
    }

    /**
     * Store specific attributes of the person.Gets the value of the contextAttribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contextAttribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContextAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Attribute }
     * 
     * 
     */
    public List<Attribute> getContextAttribute() {
        if (contextAttribute == null) {
            contextAttribute = new ArrayList<Attribute>();
        }
        return this.contextAttribute;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NameValuePair }
     * 
     * 
     */
    public Map<String, String> getAttributes() {
        if (attributes == null) {
            attributes = new HashMap<String, String>();
        }
        return this.attributes;
    }

    /**
     * Gets the value of the checkoutProfile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the checkoutProfile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCheckoutProfile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CheckoutProfile }
     * 
     * 
     */
    public List<CheckoutProfile> getCheckoutProfile() {
        if (checkoutProfile == null) {
            checkoutProfile = new ArrayList<CheckoutProfile>();
        }
        return this.checkoutProfile;
    }

    /**
     * User data.
     * 
     * @return
     *     possible object is
     *     {@link UserData }
     *     
     */
    public UserData getUserData() {
        return userData;
    }

    /**
     * Sets the value of the userData property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserData }
     *     
     */
    public void setUserData(UserData value) {
        this.userData = value;
    }

    /**
     * Gets the value of the registrationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link RegistrationStatus }
     *     
     */
    public String getRegistrationStatus() {
        return registrationStatus;
    }

    /**
     * Sets the value of the registrationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegistrationStatus }
     *     
     */
    public void setRegistrationStatus(String value) {
        this.registrationStatus = value;
    }

    /**
     * Gets the value of the registrationApprovalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrationApprovalStatus() {
        return registrationApprovalStatus;
    }

    /**
     * Sets the value of the registrationApprovalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrationApprovalStatus(String value) {
        this.registrationApprovalStatus = value;
    }

    /**
     * Gets the value of the profileType property.
     * 
     * @return
     *     possible object is
     *     {@link Profile }
     *     
     */
    public Profile getProfile() {
        return profileType;
    }

    /**
     * Sets the value of the profileType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Profile }
     *     
     */
    public void setProfile(Profile value) {
        this.profileType = value;
    }

    /**
     * Gets the value of the passwordExpired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPasswordExpired() {
        return passwordExpired;
    }

    /**
     * Sets the value of the passwordExpired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPasswordExpired(Boolean value) {
        this.passwordExpired = value;
    }

    /**
     * Gets the value of the accountStatus property.
     * 
     * @return
     *     possible object is
     *     {@link AccountStatus }
     *     
     */
    public String getAccountStatus() {
        return accountStatus;
    }

    /**
     * Sets the value of the accountStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountStatus }
     *     
     */
    public void setAccountStatus(String value) {
        this.accountStatus = value;
    }

}
